<?php
/**
 * Created by PhpStorm.
 * User: dupeng
 * Date: 2018/4/3
 * Time: 下午7:00
 */

namespace App\Utility;
use EasySwoole\Config;
use EasySwoole\Core\Swoole\Coroutine\AbstractInterface\CoroutinePool;
use EasySwoole\Core\Swoole\Coroutine\Client\Redis;

class RedisPool extends CoroutinePool
{
    public function __construct($min, $max)
    {
        parent::__construct($min, $max);
    }
    public function getObj($timeOut = 0.1):?Redis
    {
        return parent::getObj($timeOut); // TODO: Change the autogenerated stub
    }
    protected function createObject()
    {
        $conf = Config::getInstance()->getConf('REDIS_SERVER');
        var_dump($conf);
        $redis = new Redis($conf['host'], $conf['port'], $conf['serialize'], $conf['auth']);
        var_dump($redis);
        if (is_callable($conf['errorHandler'])) {
            $redis->setErrorHandler($conf['errorHandler']);
        }
        $redis->exec('select', $conf['dbname']);
        return $redis;
    }
}