<?php
return [
    [
        'type' => 'send',
        'message' => 'AddItemReq',
        'msgid' => '1000',
        'desc' => ' 添加道具进背包请求',
    ],
    [
        'type' => 'send',
        'message' => 'ChangeAvatarReq',
        'msgid' => '1002',
        'desc' => '',
    ],
    [
        'type' => 'send',
        'message' => 'ConnectingReq',
        'msgid' => '1004',
        'desc' => ' 客户端请求接入服务器',
    ],
    [
        'type' => 'send',
        'message' => 'CreateBuildReq',
        'msgid' => '1005',
        'desc' => '',
    ],
    [
        'type' => 'send',
        'message' => 'CreateCompanyReq',
        'msgid' => '1006',
        'desc' => '',
    ],
    [
        'type' => 'send',
        'message' => 'CreateRoleReq',
        'msgid' => '1007',
        'desc' => ' NewRoleResult',
    ],
    [
        'type' => 'send',
        'message' => 'DeleteRoleReq',
        'msgid' => '1008',
        'desc' => '',
    ],
    [
        'type' => 'send',
        'message' => 'DestoryBuildReq',
        'msgid' => '1010',
        'desc' => '',
    ],
    [
        'type' => 'send',
        'message' => 'GetMapReq',
        'msgid' => '1011',
        'desc' => '',
    ],
    [
        'type' => 'send',
        'message' => 'JoinGameReq',
        'msgid' => '1012',
        'desc' => ' 客户端请求加入游戏',
    ],
    [
        'type' => 'send',
        'message' => 'RemoveItemReq',
        'msgid' => '1013',
        'desc' => '',
    ],
    [
        'type' => 'send',
        'message' => 'SellItemReq',
        'msgid' => '1014',
        'desc' => '',
    ],
    [
        'type' => 'send',
        'message' => 'UseItemReq',
        'msgid' => '1015',
        'desc' => ' 使用物品',
    ],
    [
        'type' => 'send',
        'message' => 'AchievementReq',
        'msgid' => '1069',
        'desc' => ' 请求成就列表',
    ],
    [
        'type' => 'rec',
        'message' => 'AchievementResult',
        'msgid' => '1100',
        'desc' => ' 请求成就返回',
    ],
    [
        'type' => 'rec',
        'message' => 'TCAchievementResult',
        'msgid' => '1101',
        'desc' => ' 主动下发成就完成状态',
    ],
    [
        'type' => 'send',
        'message' => 'ActiveAchievementReq',
        'msgid' => '1070',
        'desc' => ' 激活成就请求',
    ],
    [
        'type' => 'rec',
        'message' => 'ActiveAchievementResult',
        'msgid' => '1102',
        'desc' => ' 激活成就返回',
    ],
    [
        'type' => 'send',
        'message' => 'GetAchievementRewardReq',
        'msgid' => '1072',
        'desc' => ' 领取成就奖励请求',
    ],
    [
        'type' => 'rec',
        'message' => 'GetAchievementRewardResult',
        'msgid' => '1104',
        'desc' => ' 领取成就奖励返回',
    ],
    [
        'type' => 'send',
        'message' => 'UnLoadAchievementReq',
        'msgid' => '1073',
        'desc' => ' 卸载成就称号请求',
    ],
    [
        'type' => 'rec',
        'message' => 'UnLoadAchievementResult',
        'msgid' => '1105',
        'desc' => ' 卸载成就称号返回',
    ],
    [
        'type' => 'send',
        'message' => 'AppointManagerReq',
        'msgid' => '1088',
        'desc' => ' 任命主管',
    ],
    [
        'type' => 'rec',
        'message' => 'AppointManagerResult',
        'msgid' => '1123',
        'desc' => ' 任命主管返回',
    ],
    [
        'type' => 'send',
        'message' => 'ChangeManagerReq',
        'msgid' => '1089',
        'desc' => ' 换主管请求',
    ],
    [
        'type' => 'rec',
        'message' => 'ChangeManagerResult',
        'msgid' => '1124',
        'desc' => ' 换主管返回',
    ],
    [
        'type' => 'send',
        'message' => 'GetManagerInfoReq',
        'msgid' => '1090',
        'desc' => ' 请求详细信息列表',
    ],
    [
        'type' => 'rec',
        'message' => 'GetManagerInfoResult',
        'msgid' => '1125',
        'desc' => ' 请求详细信息列表',
    ],
    [
        'type' => 'send',
        'message' => 'AuctionShopReq',
        'msgid' => '1136',
        'desc' => ' 获取拍卖店铺信息',
    ],
    [
        'type' => 'rec',
        'message' => 'AuctionShopResult',
        'msgid' => '1183',
        'desc' => ' 返回拍卖店铺信息',
    ],
    [
        'type' => 'send',
        'message' => 'RoleAuctionShopReq',
        'msgid' => '1140',
        'desc' => ' 自己竞拍过的所有店铺',
    ],
    [
        'type' => 'rec',
        'message' => 'RoleAuctionShopResult',
        'msgid' => '1189',
        'desc' => ' 自己竞拍过的所有店铺',
    ],
    [
        'type' => 'rec',
        'message' => 'UpdataRoleShopResult',
        'msgid' => '1190',
        'desc' => ' 主动推送拍卖店铺信息',
    ],
    [
        'type' => 'send',
        'message' => 'ShopAuctionReq',
        'msgid' => '1139',
        'desc' => ' 私有店铺拍卖',
    ],
    [
        'type' => 'rec',
        'message' => 'ShopAuctionResult',
        'msgid' => '1187',
        'desc' => ' 私有店铺拍卖',
    ],
    [
        'type' => 'send',
        'message' => 'TestReq',
        'msgid' => '1137',
        'desc' => ' 私有店铺拍卖',
    ],
    [
        'type' => 'rec',
        'message' => 'TestResult',
        'msgid' => '1191',
        'desc' => ' 私有店铺拍卖',
    ],
    [
        'type' => 'send',
        'message' => 'PublicRoleShopReq',
        'msgid' => '1141',
        'desc' => ' 个人拍卖获得的公有店铺',
    ],
    [
        'type' => 'rec',
        'message' => 'PublicRoleShopResult',
        'msgid' => '1192',
        'desc' => ' 个人拍卖获得的公有店铺',
    ],
    [
        'type' => 'send',
        'message' => 'ShopInfoReq',
        'msgid' => '1144',
        'desc' => ' 个人拍卖获得的公有店铺',
    ],
    [
        'type' => 'rec',
        'message' => 'ShopInfoResult',
        'msgid' => '1196',
        'desc' => ' 个人拍卖获得的公有店铺',
    ],
    [
        'type' => 'send',
        'message' => 'NoBodyShopReq',
        'msgid' => '1158',
        'desc' => ' 获取所有无主店铺',
    ],
    [
        'type' => 'rec',
        'message' => 'NoBodyShopResult',
        'msgid' => '1211',
        'desc' => ' 获取无主店铺',
    ],
    [
        'type' => 'send',
        'message' => 'PurchaseShopReq',
        'msgid' => '1159',
        'desc' => ' 购买无主店铺',
    ],
    [
        'type' => 'rec',
        'message' => 'PurchaseShopResult',
        'msgid' => '1212',
        'desc' => ' 购买无主店铺',
    ],
    [
        'type' => 'send',
        'message' => 'BiddingAhReq',
        'msgid' => '1064',
        'desc' => ' 竞价拍卖行中的商品',
    ],
    [
        'type' => 'rec',
        'message' => 'BiddingAhResult',
        'msgid' => '1094',
        'desc' => ' 竞标拍卖行中的商品返回',
    ],
    [
        'type' => 'send',
        'message' => 'BiddingGoodsReq',
        'msgid' => '1057',
        'desc' => ' 商品竞价请求',
    ],
    [
        'type' => 'rec',
        'message' => 'BiddingGoodsResult',
        'msgid' => '1088',
        'desc' => ' 商品竞价返回',
    ],
    [
        'type' => 'send',
        'message' => 'BuildAdvReq',
        'msgid' => '1016',
        'desc' => ' 店铺宣传请求',
    ],
    [
        'type' => 'rec',
        'message' => 'BuildAdvResult',
        'msgid' => '1000',
        'desc' => ' 店铺宣传请求返回',
    ],
    [
        'type' => 'rec',
        'message' => 'BuildAdvFailedResult',
        'msgid' => '1001',
        'desc' => ' 宣传失败返回',
    ],
    [
        'type' => 'send',
        'message' => 'BuildExtendReq',
        'msgid' => '1017',
        'desc' => ' 店铺扩建',
    ],
    [
        'type' => 'rec',
        'message' => 'BuildExtendResult',
        'msgid' => '1002',
        'desc' => ' 店铺扩建成功',
    ],
    [
        'type' => 'rec',
        'message' => 'BuildExtendFailedResult',
        'msgid' => '1003',
        'desc' => ' 店铺扩建失败',
    ],
    [
        'type' => 'send',
        'message' => 'BuildLvUpReq',
        'msgid' => '1018',
        'desc' => ' 建筑升级',
    ],
    [
        'type' => 'rec',
        'message' => 'BuildLvUpResult',
        'msgid' => '1004',
        'desc' => ' 建筑升级',
    ],
    [
        'type' => 'rec',
        'message' => 'BuildLvUpFailedResult',
        'msgid' => '1005',
        'desc' => ' 建筑升级',
    ],
    [
        'type' => 'send',
        'message' => 'SendMsgToChannelReq',
        'msgid' => '1019',
        'desc' => ' 向频道中发送消息',
    ],
    [
        'type' => 'rec',
        'message' => 'SendMsgToChannelResult',
        'msgid' => '1006',
        'desc' => ' 向频道中发送消息',
    ],
    [
        'type' => 'rec',
        'message' => 'TCRecMsgFromChannelResult',
        'msgid' => '1007',
        'desc' => ' 主动下发消息到频道中',
    ],
    [
        'type' => 'rec',
        'message' => 'TCRecMsgHorseResult',
        'msgid' => '1008',
        'desc' => ' 跑马灯消息 系统消息',
    ],
    [
        'type' => 'rec',
        'message' => 'AuctionEndStartResult',
        'msgid' => '1186',
        'desc' => ' 跑马灯消息 系统消息',
    ],
    [
        'type' => 'rec',
        'message' => 'TCRecSystemMsgResult',
        'msgid' => '1130',
        'desc' => ' 系统消息',
    ],
    [
        'type' => 'rec',
        'message' => 'TextShopEndMsgResult',
        'msgid' => '1204',
        'desc' => ' 私有店铺拍卖',
    ],
    [
        'type' => 'send',
        'message' => 'CKApiReq',
        'msgid' => '1165',
        'desc' => ' 请求创客数据',
    ],
    [
        'type' => 'rec',
        'message' => 'CKErrResult',
        'msgid' => '1219',
        'desc' => ' 错误返回',
    ],
    [
        'type' => 'rec',
        'message' => 'CkTeamResult',
        'msgid' => '1220',
        'desc' => ' 错误返回',
    ],
    [
        'type' => 'rec',
        'message' => 'CkGetRmbResult',
        'msgid' => '1229',
        'desc' => ' 创客提现返回',
    ],
    [
        'type' => 'rec',
        'message' => 'CkPayResult',
        'msgid' => '1224',
        'desc' => ' 创客支付返回',
    ],
    [
        'type' => 'rec',
        'message' => 'CKRichResult',
        'msgid' => '1221',
        'desc' => ' 创客支付返回',
    ],
    [
        'type' => 'rec',
        'message' => 'CKPayLogResult',
        'msgid' => '1222',
        'desc' => ' 创客支付日志',
    ],
    [
        'type' => 'rec',
        'message' => 'CKApiResult',
        'msgid' => '1223',
        'desc' => ' 请求创客数据返回',
    ],
    [
        'type' => 'send',
        'message' => 'CKConnectReq',
        'msgid' => '1164',
        'desc' => ' 创客连接请求',
    ],
    [
        'type' => 'rec',
        'message' => 'CKConnectResult',
        'msgid' => '1218',
        'desc' => ' 创客连接请求返回',
    ],
    [
        'type' => 'send',
        'message' => 'DataCountReq',
        'msgid' => '1105',
        'desc' => ' 请求数据统计数据',
    ],
    [
        'type' => 'rec',
        'message' => 'DataCountResult',
        'msgid' => '1144',
        'desc' => ' 数据统计数据返回',
    ],
    [
        'type' => 'send',
        'message' => 'DelMailsReq',
        'msgid' => '1080',
        'desc' => ' 删除邮件请求',
    ],
    [
        'type' => 'rec',
        'message' => 'DelMailsResult',
        'msgid' => '1113',
        'desc' => ' 删除邮件返回',
    ],
    [
        'type' => 'send',
        'message' => 'DropShopReq',
        'msgid' => '1074',
        'desc' => ' 商城商店',
    ],
    [
        'type' => 'rec',
        'message' => 'DropShopResult',
        'msgid' => '1106',
        'desc' => ' 返回商城商店信息',
    ],
    [
        'type' => 'send',
        'message' => 'SeedShopReq',
        'msgid' => '1071',
        'desc' => ' 种子商店',
    ],
    [
        'type' => 'rec',
        'message' => 'SeedShopResult',
        'msgid' => '1103',
        'desc' => ' 种子商店',
    ],
    [
        'type' => 'send',
        'message' => 'DropShopPingReq',
        'msgid' => '1075',
        'desc' => ' 掉落库的商品购买',
    ],
    [
        'type' => 'rec',
        'message' => 'DropShopPingResult',
        'msgid' => '1107',
        'desc' => ' 掉落库的商品购买',
    ],
    [
        'type' => 'send',
        'message' => 'SeedShopPingReq',
        'msgid' => '1076',
        'desc' => ' 购买种子商店',
    ],
    [
        'type' => 'rec',
        'message' => 'SeedShopPingResult',
        'msgid' => '1108',
        'desc' => ' 购买种子商店',
    ],
    [
        'type' => 'send',
        'message' => 'RefDropShopReq',
        'msgid' => '1077',
        'desc' => ' 刷新商城商品',
    ],
    [
        'type' => 'rec',
        'message' => 'RefDropShopResult',
        'msgid' => '1109',
        'desc' => ' 刷新商城商品',
    ],
    [
        'type' => 'send',
        'message' => 'ShopAllReq',
        'msgid' => '1106',
        'desc' => ' 加载所有商店',
    ],
    [
        'type' => 'rec',
        'message' => 'ShopAllResult',
        'msgid' => '1145',
        'desc' => ' 加载所有商店',
    ],
    [
        'type' => 'send',
        'message' => 'ModelClothesReq',
        'msgid' => '1150',
        'desc' => ' 购买时装',
    ],
    [
        'type' => 'rec',
        'message' => 'ModelClothesResult',
        'msgid' => '1203',
        'desc' => ' 购买时装',
    ],
    [
        'type' => 'send',
        'message' => 'FriendAwardReq',
        'msgid' => '1117',
        'desc' => ' 一键领取好友奖励请求',
    ],
    [
        'type' => 'rec',
        'message' => 'FriendAwardResult',
        'msgid' => '1161',
        'desc' => ' 请求返回',
    ],
    [
        'type' => 'send',
        'message' => 'FriendApplyReq',
        'msgid' => '1021',
        'desc' => ' 添加好友申请',
    ],
    [
        'type' => 'rec',
        'message' => 'FriendApplyResult',
        'msgid' => '1011',
        'desc' => ' 添加好友申请返回',
    ],
    [
        'type' => 'send',
        'message' => 'FriendAddReq',
        'msgid' => '1022',
        'desc' => ' 添加好友',
    ],
    [
        'type' => 'send',
        'message' => 'FriendRemoveReq',
        'msgid' => '1023',
        'desc' => ' 删除好友',
    ],
    [
        'type' => 'rec',
        'message' => 'FriendRemoveResult',
        'msgid' => '1012',
        'desc' => ' 删除好友返回',
    ],
    [
        'type' => 'rec',
        'message' => 'FriendAddResult',
        'msgid' => '1013',
        'desc' => ' 添加好友返回',
    ],
    [
        'type' => 'rec',
        'message' => 'FriendListResult',
        'msgid' => '1014',
        'desc' => '',
    ],
    [
        'type' => 'rec',
        'message' => 'FriendUpdateResult',
        'msgid' => '1015',
        'desc' => ' 好友状态更新',
    ],
    [
        'type' => 'send',
        'message' => 'FriendSearchReq',
        'msgid' => '1024',
        'desc' => '推荐玩家',
    ],
    [
        'type' => 'rec',
        'message' => 'FriendSearchResult',
        'msgid' => '1016',
        'desc' => '推荐返回',
    ],
    [
        'type' => 'send',
        'message' => 'FriendApplyClearReq',
        'msgid' => '1025',
        'desc' => ' 清空好友申请',
    ],
    [
        'type' => 'rec',
        'message' => 'FriendApplyClearResult',
        'msgid' => '1017',
        'desc' => ' 清空好友申请',
    ],
    [
        'type' => 'send',
        'message' => 'FriendAddBlackReq',
        'msgid' => '1026',
        'desc' => ' 添加到黑名单',
    ],
    [
        'type' => 'rec',
        'message' => 'FriendAddBlackResult',
        'msgid' => '1018',
        'desc' => ' 添加到黑名单返回',
    ],
    [
        'type' => 'send',
        'message' => 'FriendRemoveBlackReq',
        'msgid' => '1027',
        'desc' => ' 从黑名单中移除',
    ],
    [
        'type' => 'rec',
        'message' => 'FriendRemoveBlackResult',
        'msgid' => '1019',
        'desc' => ' 从黑名单中移除返回',
    ],
    [
        'type' => 'rec',
        'message' => 'FriendOnlineResult',
        'msgid' => '1020',
        'desc' => ' 好友上线下线',
    ],
    [
        'type' => 'rec',
        'message' => 'FriendBaseResult',
        'msgid' => '1232',
        'desc' => ' ',
    ],
    [
        'type' => 'rec',
        'message' => 'FriendValueUpdateResult',
        'msgid' => '1170',
        'desc' => ' 好友友情值更新',
    ],
    [
        'type' => 'send',
        'message' => 'FriendInteractiveReq',
        'msgid' => '1129',
        'desc' => ' 好友互动操作',
    ],
    [
        'type' => 'rec',
        'message' => 'FriendInteractiveResult',
        'msgid' => '1175',
        'desc' => ' 好友互动操作返回',
    ],
    [
        'type' => 'send',
        'message' => 'FruitsDataReq',
        'msgid' => '1031',
        'desc' => ' 加载水果机物品',
    ],
    [
        'type' => 'rec',
        'message' => 'FruitsDataResult',
        'msgid' => '1030',
        'desc' => ' 返回加载水果机物品',
    ],
    [
        'type' => 'send',
        'message' => 'RaffleFruitsReq',
        'msgid' => '1035',
        'desc' => ' 抽奖',
    ],
    [
        'type' => 'rec',
        'message' => 'RaffleFruitsResult',
        'msgid' => '1035',
        'desc' => ' 返回抽奖信息',
    ],
    [
        'type' => 'send',
        'message' => 'BuyFurnitureReq',
        'msgid' => '1107',
        'desc' => ' 购买家具',
    ],
    [
        'type' => 'rec',
        'message' => 'BuyFurnitureResult',
        'msgid' => '1146',
        'desc' => ' 购买家具返回 返回变化的道具',
    ],
    [
        'type' => 'send',
        'message' => 'SellFurnitureReq',
        'msgid' => '1108',
        'desc' => ' 出售家具',
    ],
    [
        'type' => 'rec',
        'message' => 'SellFurnitureResult',
        'msgid' => '1147',
        'desc' => ' 出售家具返回',
    ],
    [
        'type' => 'send',
        'message' => 'FurnitureStarReq',
        'msgid' => '1109',
        'desc' => ' 家具升星',
    ],
    [
        'type' => 'rec',
        'message' => 'FurnitureStarResult',
        'msgid' => '1148',
        'desc' => ' 家具升星返回',
    ],
    [
        'type' => 'send',
        'message' => 'AddFurnReq',
        'msgid' => '1112',
        'desc' => ' 家具升星返回',
    ],
    [
        'type' => 'rec',
        'message' => 'AddFurnResult',
        'msgid' => '1151',
        'desc' => ' 家具升星返回',
    ],
    [
        'type' => 'rec',
        'message' => 'UpdateFurnitureResult',
        'msgid' => '1153',
        'desc' => ' 更新家具',
    ],
    [
        'type' => 'send',
        'message' => 'GetMailItemsReq',
        'msgid' => '1065',
        'desc' => ' 获取邮件中的物品',
    ],
    [
        'type' => 'rec',
        'message' => 'GetMailItemsResult',
        'msgid' => '1095',
        'desc' => ' 获取邮件中的物品',
    ],
    [
        'type' => 'rec',
        'message' => 'GetMailItemsFailedResult',
        'msgid' => '1112',
        'desc' => ' 获取邮件中的物品失败处理 ',
    ],
    [
        'type' => 'send',
        'message' => 'GetPrivateLandReq',
        'msgid' => '1138',
        'desc' => ' 获取私有土地请求',
    ],
    [
        'type' => 'rec',
        'message' => 'GetPrivateLandResult',
        'msgid' => '1185',
        'desc' => ' 获取私有土地请求返回',
    ],
    [
        'type' => 'send',
        'message' => 'ItemBuyReq',
        'msgid' => '1028',
        'desc' => ' 道具购买',
    ],
    [
        'type' => 'rec',
        'message' => 'ItemBuyResult',
        'msgid' => '1021',
        'desc' => ' 道具购买返回',
    ],
    [
        'type' => 'rec',
        'message' => 'UpdateItemResult',
        'msgid' => '1022',
        'desc' => ' 道具更新',
    ],
    [
        'type' => 'send',
        'message' => 'LoadingGoldReq',
        'msgid' => '1029',
        'desc' => '',
    ],
    [
        'type' => 'rec',
        'message' => 'LoadingGoldResult',
        'msgid' => '1023',
        'desc' => '',
    ],
    [
        'type' => 'send',
        'message' => 'MailReq',
        'msgid' => '1058',
        'desc' => ' 邮件协议',
    ],
    [
        'type' => 'rec',
        'message' => 'MailResult',
        'msgid' => '1089',
        'desc' => ' 邮件协议',
    ],
    [
        'type' => 'send',
        'message' => 'ReadMailReq',
        'msgid' => '1081',
        'desc' => ' 阅读邮件请求',
    ],
    [
        'type' => 'rec',
        'message' => 'ReadMailResult',
        'msgid' => '1114',
        'desc' => ' 阅读邮件返回',
    ],
    [
        'type' => 'send',
        'message' => 'MakeReq',
        'msgid' => '1052',
        'desc' => '',
    ],
    [
        'type' => 'rec',
        'message' => 'MakeResult',
        'msgid' => '1081',
        'desc' => ' 返回制作成功的道具和数量',
    ],
    [
        'type' => 'send',
        'message' => 'RequestManorReq',
        'msgid' => '1053',
        'desc' => ' 请求庄园',
    ],
    [
        'type' => 'rec',
        'message' => 'RequestManorResult',
        'msgid' => '1082',
        'desc' => ' 请求庄园',
    ],
    [
        'type' => 'send',
        'message' => 'InitiativeRequestManorReq',
        'msgid' => '1063',
        'desc' => ' 种子成熟主动请求刷新',
    ],
    [
        'type' => 'rec',
        'message' => 'InitiativeRequestManorResult',
        'msgid' => '1093',
        'desc' => ' 种子成熟主动请求刷新返回',
    ],
    [
        'type' => 'send',
        'message' => 'ClearStateReq',
        'msgid' => '1054',
        'desc' => ' 客户端返回要清除异常状态的id',
    ],
    [
        'type' => 'rec',
        'message' => 'ClearStateResult',
        'msgid' => '1084',
        'desc' => '  除草 浇水 收获  种植',
    ],
    [
        'type' => 'send',
        'message' => 'GrowPlantsReq',
        'msgid' => '1055',
        'desc' => ' 种植植物',
    ],
    [
        'type' => 'rec',
        'message' => 'GrowPlantsResult',
        'msgid' => '1085',
        'desc' => ' 返回种植成功的植物编号和地皮的id',
    ],
    [
        'type' => 'send',
        'message' => 'HarvestPlantReq',
        'msgid' => '1056',
        'desc' => ' 收获',
    ],
    [
        'type' => 'rec',
        'message' => 'HarvestPlanResult',
        'msgid' => '1086',
        'desc' => ' 收获',
    ],
    [
        'type' => 'send',
        'message' => 'StealSemenReq',
        'msgid' => '1061',
        'desc' => ' 偷取植物 ',
    ],
    [
        'type' => 'rec',
        'message' => 'StealSemenResult',
        'msgid' => '1091',
        'desc' => ' 偷取植物 ',
    ],
    [
        'type' => 'send',
        'message' => 'DismantleReq',
        'msgid' => '1062',
        'desc' => ' 拆除植物',
    ],
    [
        'type' => 'rec',
        'message' => 'DismantleResult',
        'msgid' => '1092',
        'desc' => ' 拆除植物',
    ],
    [
        'type' => 'send',
        'message' => 'AddSoilReq',
        'msgid' => '1078',
        'desc' => ' 添加土地',
    ],
    [
        'type' => 'rec',
        'message' => 'AddSoilResult',
        'msgid' => '1110',
        'desc' => ' 添加土地',
    ],
    [
        'type' => 'send',
        'message' => 'RefFitnessReq',
        'msgid' => '1104',
        'desc' => ' 刷新状态',
    ],
    [
        'type' => 'rec',
        'message' => 'RefFitnessResult',
        'msgid' => '1143',
        'desc' => ' 刷新状态',
    ],
    [
        'type' => 'send',
        'message' => 'AKeyMatureReq',
        'msgid' => '1124',
        'desc' => '一键成熟',
    ],
    [
        'type' => 'rec',
        'message' => 'AKeyMatureResult',
        'msgid' => '1172',
        'desc' => ' 一键成熟',
    ],
    [
        'type' => 'send',
        'message' => 'UpgradeLandLevelReq',
        'msgid' => '1125',
        'desc' => ' 升级土地等级',
    ],
    [
        'type' => 'rec',
        'message' => 'UpgradeLandLevelResult',
        'msgid' => '1171',
        'desc' => ' 升级土地等级',
    ],
    [
        'type' => 'rec',
        'message' => 'ManorVisitInfoTipResult',
        'msgid' => '1200',
        'desc' => ' 纪录提示',
    ],
    [
        'type' => 'send',
        'message' => 'ManorVisitInfoReq',
        'msgid' => '1148',
        'desc' => ' 获取拜访纪录',
    ],
    [
        'type' => 'rec',
        'message' => 'ManorVisitInfoResult',
        'msgid' => '1201',
        'desc' => ' 拜访纪录返回',
    ],
    [
        'type' => 'rec',
        'message' => 'MissionResult',
        'msgid' => '1025',
        'desc' => ' 任务相关信息',
    ],
    [
        'type' => 'rec',
        'message' => 'CreateRoadOpenResult',
        'msgid' => '1024',
        'desc' => ' 创客之路开启',
    ],
    [
        'type' => 'send',
        'message' => 'CreateRoadRewardReq',
        'msgid' => '1048',
        'desc' => ' 领取创客之路奖励',
    ],
    [
        'type' => 'rec',
        'message' => 'CreateRoadRewardResult',
        'msgid' => '1079',
        'desc' => ' 领取创客之路奖励返回',
    ],
    [
        'type' => 'send',
        'message' => 'MissionVitalityGetReq',
        'msgid' => '1049',
        'desc' => ' 领取活跃度奖励',
    ],
    [
        'type' => 'rec',
        'message' => 'MissionVitalityGetResult',
        'msgid' => '1077',
        'desc' => ' 领取活跃度奖励返回',
    ],
    [
        'type' => 'rec',
        'message' => 'MissionVitalityResult',
        'msgid' => '1076',
        'desc' => ' 活跃度更新',
    ],
    [
        'type' => 'send',
        'message' => 'MissionGetRewardReq',
        'msgid' => '1030',
        'desc' => ' 领取任务奖励',
    ],
    [
        'type' => 'rec',
        'message' => 'MissionGetRewardResult',
        'msgid' => '1026',
        'desc' => ' 领取任务奖励返回',
    ],
    [
        'type' => 'rec',
        'message' => 'MissionCompleteResult',
        'msgid' => '1027',
        'desc' => ' 完成任务',
    ],
    [
        'type' => 'rec',
        'message' => 'MissionNewResult',
        'msgid' => '1028',
        'desc' => ' 新任务',
    ],
    [
        'type' => 'rec',
        'message' => 'MissionDataResult',
        'msgid' => '1029',
        'desc' => '更新',
    ],
    [
        'type' => 'send',
        'message' => 'MissionFirstCompleteReq',
        'msgid' => '1149',
        'desc' => ' 快速完成任务',
    ],
    [
        'type' => 'rec',
        'message' => 'MissionFirstCompleteResult',
        'msgid' => '1202',
        'desc' => ' 快速完成任务',
    ],
    [
        'type' => 'send',
        'message' => 'MoneyChangeReq',
        'msgid' => '1079',
        'desc' => ' 货币兑换请求',
    ],
    [
        'type' => 'rec',
        'message' => 'MoneyChangeResult',
        'msgid' => '1111',
        'desc' => ' 货币兑换返回',
    ],
    [
        'type' => 'send',
        'message' => 'NpcFavorabilityReq',
        'msgid' => '1036',
        'desc' => ' 加载NPC好感度',
    ],
    [
        'type' => 'rec',
        'message' => 'NpcFavorabilityResult',
        'msgid' => '1037',
        'desc' => ' NPC好感度',
    ],
    [
        'type' => 'send',
        'message' => 'NpcRelationAdvanceReq',
        'msgid' => '1037',
        'desc' => ' NPC好感度提升',
    ],
    [
        'type' => 'rec',
        'message' => 'NpcRelationAdvanceResult',
        'msgid' => '1038',
        'desc' => ' NPC好感度提升',
    ],
    [
        'type' => 'send',
        'message' => 'AddNpcRelationAdvanceReq',
        'msgid' => '1038',
        'desc' => ' 添加好感度',
    ],
    [
        'type' => 'rec',
        'message' => 'AddNpcRelationAdvanceResult',
        'msgid' => '1133',
        'desc' => ' 添加好感度',
    ],
    [
        'type' => 'send',
        'message' => 'ProcurementReq',
        'msgid' => '1039',
        'desc' => ' ',
    ],
    [
        'type' => 'rec',
        'message' => 'ProcurementResult',
        'msgid' => '1039',
        'desc' => ' 初始化返回数据',
    ],
    [
        'type' => 'send',
        'message' => 'ConsumeReq',
        'msgid' => '1040',
        'desc' => ' 获取客户端需要消耗的店铺id',
    ],
    [
        'type' => 'rec',
        'message' => 'ConsumeResult',
        'msgid' => '1040',
        'desc' => ' 收取后返回收取多少金钱',
    ],
    [
        'type' => 'send',
        'message' => 'ShopBasisReq',
        'msgid' => '1161',
        'desc' => ' 返回店铺的客流',
    ],
    [
        'type' => 'rec',
        'message' => 'ShopBasisResult',
        'msgid' => '1215',
        'desc' => ' 返回店铺的加成后的所有客流',
    ],
    [
        'type' => 'send',
        'message' => 'HarvestPublicShopReq',
        'msgid' => '1145',
        'desc' => ' 收取公共地图的金币',
    ],
    [
        'type' => 'rec',
        'message' => 'HarvestPublicShopResult',
        'msgid' => '1197',
        'desc' => ' 收取公共地图的金币',
    ],
    [
        'type' => 'send',
        'message' => 'PurchaseReq',
        'msgid' => '1041',
        'desc' => ' 客户端返回采购需要的参数采购',
    ],
    [
        'type' => 'rec',
        'message' => 'PurchaseResult',
        'msgid' => '1041',
        'desc' => ' ',
    ],
    [
        'type' => 'send',
        'message' => 'StrategyStrikeReq',
        'msgid' => '1067',
        'desc' => ' 策略打击',
    ],
    [
        'type' => 'send',
        'message' => 'GetUserShopReq',
        'msgid' => '1160',
        'desc' => ' 返回请求别人的店铺',
    ],
    [
        'type' => 'rec',
        'message' => 'GetUserShopResult',
        'msgid' => '1214',
        'desc' => ' 返回请求别人的店铺',
    ],
    [
        'type' => 'send',
        'message' => 'RandomPosReq',
        'msgid' => '1099',
        'desc' => ' 随机取得地块坐标请求',
    ],
    [
        'type' => 'rec',
        'message' => 'RandomPosResult',
        'msgid' => '1137',
        'desc' => ' 随机取得地块坐标返回',
    ],
    [
        'type' => 'send',
        'message' => 'RankingReq',
        'msgid' => '1094',
        'desc' => ' 排行榜查看请求',
    ],
    [
        'type' => 'rec',
        'message' => 'RankingResult',
        'msgid' => '1132',
        'desc' => ' 排行榜查看请求返回',
    ],
    [
        'type' => 'send',
        'message' => 'GetRankingReq',
        'msgid' => '1095',
        'desc' => ' 获取个人排名',
    ],
    [
        'type' => 'rec',
        'message' => 'GetRankingResult',
        'msgid' => '1131',
        'desc' => ' 获取个人排名返回',
    ],
    [
        'type' => 'rec',
        'message' => 'Get2RedPacketResult',
        'msgid' => '1159',
        'desc' => ' 获取红包',
    ],
    [
        'type' => 'send',
        'message' => 'UpdateRedPacketRecordReq',
        'msgid' => '1118',
        'desc' => ' 获取红包',
    ],
    [
        'type' => 'rec',
        'message' => 'UpdateRedPacketRecordResult',
        'msgid' => '1162',
        'desc' => ' 获取红包',
    ],
    [
        'type' => 'send',
        'message' => 'GetRedPacketReq',
        'msgid' => '1116',
        'desc' => ' 获取红包',
    ],
    [
        'type' => 'rec',
        'message' => 'GetRedPacketResult',
        'msgid' => '1154',
        'desc' => ' 获取红包',
    ],
    [
        'type' => 'send',
        'message' => 'ReceiveRedPacketReq',
        'msgid' => '1113',
        'desc' => ' 领红包',
    ],
    [
        'type' => 'rec',
        'message' => 'ReceiveRedPacketResult',
        'msgid' => '1155',
        'desc' => ' 领红包',
    ],
    [
        'type' => 'rec',
        'message' => 'LoadResultRedPacket',
        'msgid' => '1156',
        'desc' => ' 返回发红包信息',
    ],
    [
        'type' => 'send',
        'message' => 'RefreshAHReq',
        'msgid' => '1066',
        'desc' => ' 刷新，浏览拍卖行请求',
    ],
    [
        'type' => 'rec',
        'message' => 'RefreshAHResult',
        'msgid' => '1096',
        'desc' => ' 刷新，浏览拍卖行返回',
    ],
    [
        'type' => 'send',
        'message' => 'RefreshDealGoodsReq',
        'msgid' => '1050',
        'desc' => ' 刷新交易市场请求',
    ],
    [
        'type' => 'rec',
        'message' => 'RefreshDealGoodsResult',
        'msgid' => '1083',
        'desc' => ' 更新寄卖消息',
    ],
    [
        'type' => 'rec',
        'message' => 'DealGoodsUpdateResult',
        'msgid' => '1099',
        'desc' => ' 单个商品更新消息',
    ],
    [
        'type' => 'send',
        'message' => 'RefStaffReq',
        'msgid' => '1082',
        'desc' => ' 抽卡NPC',
    ],
    [
        'type' => 'rec',
        'message' => 'RefStaffResult',
        'msgid' => '1117',
        'desc' => ' 返回抽卡ID',
    ],
    [
        'type' => 'send',
        'message' => 'LoadStaffReq',
        'msgid' => '1083',
        'desc' => ' 加载所有员工',
    ],
    [
        'type' => 'rec',
        'message' => 'LoadStaffResult',
        'msgid' => '1118',
        'desc' => ' 返回所有员工',
    ],
    [
        'type' => 'send',
        'message' => 'TypeCountStaffReq',
        'msgid' => '1147',
        'desc' => ' 加载免费抽奖的次数和Cd时间',
    ],
    [
        'type' => 'rec',
        'message' => 'TypeCountStaffResult',
        'msgid' => '1199',
        'desc' => ' 加载免费抽奖的次数和Cd时间',
    ],
    [
        'type' => 'send',
        'message' => 'EmployeesCardReq',
        'msgid' => '1084',
        'desc' => ' 员工工作证',
    ],
    [
        'type' => 'rec',
        'message' => 'EmployeesCardResult',
        'msgid' => '1119',
        'desc' => ' 返回员工工作证',
    ],
    [
        'type' => 'send',
        'message' => 'LevelUpEmployeeReq',
        'msgid' => '1085',
        'desc' => ' 升级员工',
    ],
    [
        'type' => 'rec',
        'message' => 'LevelUpEmployeeResult',
        'msgid' => '1120',
        'desc' => ' 返回升级员工信息',
    ],
    [
        'type' => 'send',
        'message' => 'CultivateEmployeeReq',
        'msgid' => '1086',
        'desc' => ' 培训员工',
    ],
    [
        'type' => 'rec',
        'message' => 'CultivateEmployeeResult',
        'msgid' => '1121',
        'desc' => ' 返回培训员工信息',
    ],
    [
        'type' => 'send',
        'message' => 'DismissalEmployeeReq',
        'msgid' => '1087',
        'desc' => ' 解雇员工',
    ],
    [
        'type' => 'rec',
        'message' => 'DismissalEmployeeResult',
        'msgid' => '1122',
        'desc' => ' 返回解雇员工信息',
    ],
    [
        'type' => 'send',
        'message' => 'ComeOutEmployeeReq',
        'msgid' => '1091',
        'desc' => ' 获取前台传来的铺id和人数是调入还是调出',
    ],
    [
        'type' => 'rec',
        'message' => 'ComeOutEmployeeResult',
        'msgid' => '1126',
        'desc' => ' 返回店铺信息和员工信息',
    ],
    [
        'type' => 'send',
        'message' => 'RequestGoodsDownReq',
        'msgid' => '1167',
        'desc' => ' 商品请求下架',
    ],
    [
        'type' => 'rec',
        'message' => 'RequestGoodsDownResult',
        'msgid' => '1227',
        'desc' => ' 请求下架返回 ',
    ],
    [
        'type' => 'send',
        'message' => 'OnGetMyGoodsReq',
        'msgid' => '1168',
        'desc' => ' 获取自己上架的商品列表',
    ],
    [
        'type' => 'rec',
        'message' => 'OnGetMyGoodsResult',
        'msgid' => '1228',
        'desc' => ' 获取自己的上架商品列表返回',
    ],
    [
        'type' => 'send',
        'message' => 'ResidentDelegateReq',
        'msgid' => '1096',
        'desc' => ' 加载居名委托任务',
    ],
    [
        'type' => 'rec',
        'message' => 'ResidentDelegateResult',
        'msgid' => '1134',
        'desc' => ' 返回居民委托任务',
    ],
    [
        'type' => 'send',
        'message' => 'RefResidentDelegateReq',
        'msgid' => '1097',
        'desc' => ' 刷新任务',
    ],
    [
        'type' => 'rec',
        'message' => 'RefResidentDelegateResult',
        'msgid' => '1115',
        'desc' => ' 刷新任务',
    ],
    [
        'type' => 'send',
        'message' => 'AccomplishResidentDelegateReq',
        'msgid' => '1098',
        'desc' => ' 完成任务',
    ],
    [
        'type' => 'rec',
        'message' => 'AccomplishResidentDelegateResult',
        'msgid' => '1135',
        'desc' => ' 完成任务',
    ],
    [
        'type' => 'send',
        'message' => 'RoomReq',
        'msgid' => '1042',
        'desc' => ' 客户端请求用户的房间信息',
    ],
    [
        'type' => 'rec',
        'message' => 'RoomResult',
        'msgid' => '1042',
        'desc' => ' 返回给客户端的房间信息',
    ],
    [
        'type' => 'rec',
        'message' => 'RoomListResult',
        'msgid' => '1225',
        'desc' => ' 客户端当前房间列表信息',
    ],
    [
        'type' => 'send',
        'message' => 'RoomVisitInfoReq',
        'msgid' => '1059',
        'desc' => ' 获取拜访纪录',
    ],
    [
        'type' => 'rec',
        'message' => 'RoomVisitInfoResult',
        'msgid' => '1087',
        'desc' => ' 拜访纪录返回',
    ],
    [
        'type' => 'rec',
        'message' => 'RoomVisitInfoTipResult',
        'msgid' => '1188',
        'desc' => ' 纪录提示',
    ],
    [
        'type' => 'send',
        'message' => 'RoomConfigUpdateReq',
        'msgid' => '1043',
        'desc' => ' 请求更新房间配置',
    ],
    [
        'type' => 'rec',
        'message' => 'RoomConfigUpdateResult',
        'msgid' => '1043',
        'desc' => ' 请求更新房间配置',
    ],
    [
        'type' => 'send',
        'message' => 'RoomBuyReq',
        'msgid' => '1044',
        'desc' => '升级',
    ],
    [
        'type' => 'rec',
        'message' => 'RoomBuyResult',
        'msgid' => '1044',
        'desc' => '升级',
    ],
    [
        'type' => 'send',
        'message' => 'RoomSellReq',
        'msgid' => '1045',
        'desc' => ' 房间出售',
    ],
    [
        'type' => 'rec',
        'message' => 'RoomSellResult',
        'msgid' => '1045',
        'desc' => ' 房间出售',
    ],
    [
        'type' => 'send',
        'message' => 'RoomLiveReq',
        'msgid' => '1166',
        'desc' => ' 居住房屋',
    ],
    [
        'type' => 'rec',
        'message' => 'RoomLiveResult',
        'msgid' => '1226',
        'desc' => ' 居住房屋返回',
    ],
    [
        'type' => 'send',
        'message' => 'RoomVisitReq',
        'msgid' => '1046',
        'desc' => ' 拜访用户房间',
    ],
    [
        'type' => 'rec',
        'message' => 'RoomVisitResult',
        'msgid' => '1046',
        'desc' => ' 拜访用户房间',
    ],
    [
        'type' => 'send',
        'message' => 'RoomUpdateReq',
        'msgid' => '1119',
        'desc' => ' 房屋升级请求',
    ],
    [
        'type' => 'rec',
        'message' => 'RoomUpdateResult',
        'msgid' => '1163',
        'desc' => ' 房屋升级请求',
    ],
    [
        'type' => 'send',
        'message' => 'SavingGoldReq',
        'msgid' => '1047',
        'desc' => ' 存款请求',
    ],
    [
        'type' => 'rec',
        'message' => 'SavingGoldResult',
        'msgid' => '1047',
        'desc' => ' 存款返回',
    ],
    [
        'type' => 'send',
        'message' => 'LoadLoansReq',
        'msgid' => '1156',
        'desc' => ' 加载贷款信息',
    ],
    [
        'type' => 'rec',
        'message' => 'LoadLoansResult',
        'msgid' => '1209',
        'desc' => ' 加载贷款信息',
    ],
    [
        'type' => 'send',
        'message' => 'LoansReq',
        'msgid' => '1152',
        'desc' => ' 贷款请求',
    ],
    [
        'type' => 'rec',
        'message' => 'LoansResult',
        'msgid' => '1205',
        'desc' => ' 贷款返回',
    ],
    [
        'type' => 'send',
        'message' => 'GoldRepaymentReq',
        'msgid' => '1153',
        'desc' => ' 用金币返款请求',
    ],
    [
        'type' => 'rec',
        'message' => 'GoldRepaymentResult',
        'msgid' => '1206',
        'desc' => ' 用金币还款返回',
    ],
    [
        'type' => 'send',
        'message' => 'StaffRepaymentReq',
        'msgid' => '1154',
        'desc' => ' 用员工返款请求',
    ],
    [
        'type' => 'rec',
        'message' => 'StaffRepaymentResult',
        'msgid' => '1207',
        'desc' => ' 用员工还款返回',
    ],
    [
        'type' => 'send',
        'message' => 'ShopRepaymentReq',
        'msgid' => '1155',
        'desc' => ' 店铺返款请求',
    ],
    [
        'type' => 'rec',
        'message' => 'ShopRepaymentResult',
        'msgid' => '1208',
        'desc' => ' 店铺员工还款返回',
    ],
    [
        'type' => 'send',
        'message' => 'ItemRepaymentReq',
        'msgid' => '1157',
        'desc' => ' 道具返款请求',
    ],
    [
        'type' => 'rec',
        'message' => 'ItemRepaymentResult',
        'msgid' => '1210',
        'desc' => ' 道具员工还款返回',
    ],
    [
        'type' => 'send',
        'message' => 'SevenDaysReq',
        'msgid' => '1123',
        'desc' => ' 返回7天登陆',
    ],
    [
        'type' => 'rec',
        'message' => 'SevenDaysResult',
        'msgid' => '1166',
        'desc' => ' 返回7天登陆',
    ],
    [
        'type' => 'send',
        'message' => 'PickUpSevenDaysReq',
        'msgid' => '1120',
        'desc' => '领取奖励',
    ],
    [
        'type' => 'rec',
        'message' => 'PickUpSevenDaysResult',
        'msgid' => '1167',
        'desc' => ' 领取奖励',
    ],
    [
        'type' => 'send',
        'message' => 'SignReq',
        'msgid' => '1121',
        'desc' => ' 签到数据',
    ],
    [
        'type' => 'rec',
        'message' => 'SignResult',
        'msgid' => '1168',
        'desc' => ' 签到到数据',
    ],
    [
        'type' => 'send',
        'message' => 'DaySignReq',
        'msgid' => '1122',
        'desc' => ' 签到数据',
    ],
    [
        'type' => 'rec',
        'message' => 'DaySignResult',
        'msgid' => '1169',
        'desc' => ' 签到到数据',
    ],
    [
        'type' => 'send',
        'message' => 'DrawLotsReq',
        'msgid' => '1151',
        'desc' => ' 抽签',
    ],
    [
        'type' => 'rec',
        'message' => 'DrawLotsResult',
        'msgid' => '1213',
        'desc' => ' 返回抽签Id',
    ],
    [
        'type' => 'send',
        'message' => 'OnLineAwardsReq',
        'msgid' => '1162',
        'desc' => ' 在线奖励',
    ],
    [
        'type' => 'rec',
        'message' => 'OnLineAwardsResult',
        'msgid' => '1216',
        'desc' => ' 在线奖励',
    ],
    [
        'type' => 'send',
        'message' => 'GetOnLineAwardsReq',
        'msgid' => '1163',
        'desc' => ' 在线奖励',
    ],
    [
        'type' => 'rec',
        'message' => 'GetOnLineAwardsResult',
        'msgid' => '1217',
        'desc' => ' 在线奖励',
    ],
    [
        'type' => 'send',
        'message' => 'ShopLeaderReq',
        'msgid' => '1092',
        'desc' => ' 雇佣店长',
    ],
    [
        'type' => 'rec',
        'message' => 'ShopLeaderResult',
        'msgid' => '1128',
        'desc' => ' 雇佣店长返回',
    ],
    [
        'type' => 'rec',
        'message' => 'TCShopLeaderResult',
        'msgid' => '1127',
        'desc' => ' 被雇佣后，通知被雇佣的人',
    ],
    [
        'type' => 'send',
        'message' => 'FireLeaderReq',
        'msgid' => '1093',
        'desc' => ' 解雇店长',
    ],
    [
        'type' => 'rec',
        'message' => 'FireLeaderResult',
        'msgid' => '1129',
        'desc' => ' 解雇店长返回',
    ],
    [
        'type' => 'send',
        'message' => 'SkillReq',
        'msgid' => '1032',
        'desc' => ' 技能列表',
    ],
    [
        'type' => 'rec',
        'message' => 'SkillResult',
        'msgid' => '1031',
        'desc' => ' 技能列表返回',
    ],
    [
        'type' => 'rec',
        'message' => 'UnLockSkillResult',
        'msgid' => '1032',
        'desc' => ' 解锁技能通知',
    ],
    [
        'type' => 'send',
        'message' => 'LearnSkillReq',
        'msgid' => '1033',
        'desc' => ' 学习技能请求',
    ],
    [
        'type' => 'rec',
        'message' => 'LearnSkillResult',
        'msgid' => '1033',
        'desc' => ' 学习技能返回',
    ],
    [
        'type' => 'send',
        'message' => 'SkillLvUpReq',
        'msgid' => '1034',
        'desc' => ' 升级技能',
    ],
    [
        'type' => 'rec',
        'message' => 'SkillLvUpResult',
        'msgid' => '1034',
        'desc' => ' 升级技能返回',
    ],
    [
        'type' => 'send',
        'message' => 'TakeOutReq',
        'msgid' => '1126',
        'desc' => ' 请求打开外卖界面协议',
    ],
    [
        'type' => 'send',
        'message' => 'UpdateOutReq',
        'msgid' => '1127',
        'desc' => ' 主动刷新好友外卖喜好信息',
    ],
    [
        'type' => 'rec',
        'message' => 'TakeOutResult',
        'msgid' => '1173',
        'desc' => ' 请求打开外卖界面返回',
    ],
    [
        'type' => 'send',
        'message' => 'GiftTakeOutReq',
        'msgid' => '1128',
        'desc' => ' 给好友送外卖',
    ],
    [
        'type' => 'rec',
        'message' => 'GiftTakeOutResult',
        'msgid' => '1174',
        'desc' => ' 给好友送外卖返回',
    ],
    [
        'type' => 'send',
        'message' => 'GetTalentListReq',
        'msgid' => '1130',
        'desc' => ' 获取人才市场列表',
    ],
    [
        'type' => 'rec',
        'message' => 'GetTalentListResult',
        'msgid' => '1176',
        'desc' => ' 返回人才列表',
    ],
    [
        'type' => 'send',
        'message' => 'TalentRefreshReq',
        'msgid' => '1135',
        'desc' => ' 刷新人才市场',
    ],
    [
        'type' => 'rec',
        'message' => 'TalentRefreshResult',
        'msgid' => '1182',
        'desc' => ' 返回人才列表',
    ],
    [
        'type' => 'send',
        'message' => 'TalentHireReq',
        'msgid' => '1131',
        'desc' => ' 雇佣',
    ],
    [
        'type' => 'rec',
        'message' => 'TalentHireResult',
        'msgid' => '1177',
        'desc' => ' 雇佣返回',
    ],
    [
        'type' => 'send',
        'message' => 'TalentFireReq',
        'msgid' => '1132',
        'desc' => ' 解雇',
    ],
    [
        'type' => 'rec',
        'message' => 'TalentFireResult',
        'msgid' => '1178',
        'desc' => ' 解雇返回',
    ],
    [
        'type' => 'send',
        'message' => 'TalentDigReq',
        'msgid' => '1133',
        'desc' => ' 挖人',
    ],
    [
        'type' => 'rec',
        'message' => 'TalentDigResult',
        'msgid' => '1179',
        'desc' => ' 挖人返回',
    ],
    [
        'type' => 'rec',
        'message' => 'TalentDigSelfResult',
        'msgid' => '1180',
        'desc' => ' 被挖人返回提示',
    ],
    [
        'type' => 'send',
        'message' => 'TalentLeaveReq',
        'msgid' => '1134',
        'desc' => ' 离职',
    ],
    [
        'type' => 'rec',
        'message' => 'TalentLeaveResult',
        'msgid' => '1181',
        'desc' => ' 离职返回',
    ],
    [
        'type' => 'rec',
        'message' => 'TalentChangeResult',
        'msgid' => '1184',
        'desc' => ' 状态变化返回',
    ],
    [
        'type' => 'send',
        'message' => 'ScoreShopReq',
        'msgid' => '1142',
        'desc' => ' 请求积分商店',
    ],
    [
        'type' => 'rec',
        'message' => 'ScoreShopResult',
        'msgid' => '1193',
        'desc' => ' 请求积分商店返回',
    ],
    [
        'type' => 'rec',
        'message' => 'ScoreShopRecordResult',
        'msgid' => '1195',
        'desc' => ' 积分商店日志',
    ],
    [
        'type' => 'send',
        'message' => 'ScoreShopBuyReq',
        'msgid' => '1143',
        'desc' => ' 积分商店购买商品',
    ],
    [
        'type' => 'rec',
        'message' => 'ScoreShopBuyResult',
        'msgid' => '1194',
        'desc' => ' 积分商店购买商品返回',
    ],
    [
        'type' => 'send',
        'message' => 'TalkingGroupReq',
        'msgid' => '1115',
        'desc' => ' 谈判团任命请求',
    ],
    [
        'type' => 'rec',
        'message' => 'TalkingGroupResult',
        'msgid' => '1157',
        'desc' => ' 谈判团任命返回',
    ],
    [
        'type' => 'send',
        'message' => 'TalkIngGroupChangeReq',
        'msgid' => '1114',
        'desc' => ' 谈判团换任',
    ],
    [
        'type' => 'rec',
        'message' => 'TalkIngGroupChangeResult',
        'msgid' => '1158',
        'desc' => ' 谈判团换任',
    ],
    [
        'type' => 'send',
        'message' => 'TalkingGroupPKReq',
        'msgid' => '1146',
        'desc' => ' 谈判团PK',
    ],
    [
        'type' => 'rec',
        'message' => 'TalkingGroupPKResult',
        'msgid' => '1198',
        'desc' => ' 谈判团PK返回',
    ],
    [
        'type' => 'rec',
        'message' => 'TCBuildUpdateResult',
        'msgid' => '1048',
        'desc' => ' 店铺信息更新消息',
    ],
    [
        'type' => 'rec',
        'message' => 'TCDepartmentInvestmentResult',
        'msgid' => '1049',
        'desc' => ' 更新部门投资部',
    ],
    [
        'type' => 'rec',
        'message' => 'TCDepartmentFinanceResult',
        'msgid' => '1050',
        'desc' => ' 更新部门财务部',
    ],
    [
        'type' => 'rec',
        'message' => 'TCDepartmentPersonnelResult',
        'msgid' => '1051',
        'desc' => ' 更新部门 人事部',
    ],
    [
        'type' => 'rec',
        'message' => 'TCDepartmentMarketResult',
        'msgid' => '1052',
        'desc' => ' 更新部门 市场部',
    ],
    [
        'type' => 'send',
        'message' => 'TopUpReq',
        'msgid' => '1100',
        'desc' => '',
    ],
    [
        'type' => 'rec',
        'message' => 'TopUpResult',
        'msgid' => '1139',
        'desc' => '',
    ],
    [
        'type' => 'send',
        'message' => 'TopUpGoldReq',
        'msgid' => '1101',
        'desc' => '',
    ],
    [
        'type' => 'rec',
        'message' => 'TopUpGoldResult',
        'msgid' => '1140',
        'desc' => '',
    ],
    [
        'type' => 'rec',
        'message' => 'LoadTradeDataResult',
        'msgid' => '1233',
        'desc' => ' 加载贸易数据',
    ],
    [
        'type' => 'send',
        'message' => 'AccomplisTradehReq',
        'msgid' => '1170',
        'desc' => ' 完成贸易发送港口ID到后台',
    ],
    [
        'type' => 'rec',
        'message' => 'AccomplisTradehResult',
        'msgid' => '1234',
        'desc' => ' 完成贸易',
    ],
    [
        'type' => 'send',
        'message' => 'StartTradehReq',
        'msgid' => '1171',
        'desc' => ' 开始贸易',
    ],
    [
        'type' => 'rec',
        'message' => 'StartTradehResult',
        'msgid' => '1235',
        'desc' => ' 开始贸易',
    ],
    [
        'type' => 'send',
        'message' => 'OpenPortReq',
        'msgid' => '1172',
        'desc' => ' 开港口',
    ],
    [
        'type' => 'rec',
        'message' => 'OpenPortResult',
        'msgid' => '1236',
        'desc' => ' 开港口',
    ],
    [
        'type' => 'send',
        'message' => 'UpdateRoleInfoIconReq',
        'msgid' => '1102',
        'desc' => '',
    ],
    [
        'type' => 'rec',
        'message' => 'UpdateRoleInfoIconResult',
        'msgid' => '1141',
        'desc' => '',
    ],
    [
        'type' => 'send',
        'message' => 'UpdateRoleInfoNameReq',
        'msgid' => '1103',
        'desc' => '',
    ],
    [
        'type' => 'rec',
        'message' => 'UpdateRoleInfoNameResult',
        'msgid' => '1142',
        'desc' => '',
    ],
    [
        'type' => 'send',
        'message' => 'PraiseRoleIdReq',
        'msgid' => '1110',
        'desc' => ' 点赞数',
    ],
    [
        'type' => 'rec',
        'message' => 'PraiseRoleIdResult',
        'msgid' => '1149',
        'desc' => ' 点赞数',
    ],
    [
        'type' => 'send',
        'message' => 'GetPraiseRoleIdReq',
        'msgid' => '1111',
        'desc' => ' 显示点赞数',
    ],
    [
        'type' => 'rec',
        'message' => 'GetPraiseRoleIdResult',
        'msgid' => '1150',
        'desc' => ' 显示点赞数',
    ],
    [
        'type' => 'rec',
        'message' => 'RolePraiseResult',
        'msgid' => '1152',
        'desc' => ' 别人点赞主动推送',
    ],
    [
        'type' => 'send',
        'message' => 'UserSalesReq',
        'msgid' => '1051',
        'desc' => ' 用户寄卖请求',
    ],
    [
        'type' => 'rec',
        'message' => 'UserSalesResult',
        'msgid' => '1080',
        'desc' => ' 用户寄卖返回',
    ],
    [
        'type' => 'send',
        'message' => 'UserDownGoodsReq',
        'msgid' => '1060',
        'desc' => ' 商品下架请求',
    ],
    [
        'type' => 'rec',
        'message' => 'UserDownGoodsResult',
        'msgid' => '1090',
        'desc' => ' 下架请求返回',
    ],
    [
        'type' => 'send',
        'message' => 'VipGiftReq',
        'msgid' => '1169',
        'desc' => ' vip请求',
    ],
    [
        'type' => 'rec',
        'message' => 'VipGiftResult',
        'msgid' => '1230',
        'desc' => ' vip请求返回',
    ],
    [
        'type' => 'rec',
        'message' => 'GiftTakeLogsResult',
        'msgid' => '1231',
        'desc' => ' 礼包领取记录 进入游戏传给用户',
    ],
    [
        'type' => 'rec',
        'message' => 'AddFavourLevelResult',
        'msgid' => '1136',
        'desc' => ' 更新Npc好感度等级',
    ],
    [
        'type' => 'rec',
        'message' => 'AddFavourCountResult',
        'msgid' => '1138',
        'desc' => ' 更新Npc好感度',
    ],
    [
        'type' => 'rec',
        'message' => 'GMResult',
        'msgid' => '1164',
        'desc' => ' gm命令',
    ],
    [
        'type' => 'rec',
        'message' => 'AddItemResult',
        'msgid' => '1053',
        'desc' => ' 添加道具进背包返回',
    ],
    [
        'type' => 'rec',
        'message' => 'ChangeAvatarResult',
        'msgid' => '1055',
        'desc' => '',
    ],
    [
        'type' => 'rec',
        'message' => 'CompanyExpResult',
        'msgid' => '1036',
        'desc' => ' 更新公司营收',
    ],
    [
        'type' => 'rec',
        'message' => 'ConnectingResult',
        'msgid' => '1057',
        'desc' => '',
    ],
    [
        'type' => 'rec',
        'message' => 'CreateBuildResult',
        'msgid' => '1058',
        'desc' => '',
    ],
    [
        'type' => 'rec',
        'message' => 'CreateCompanyResult',
        'msgid' => '1059',
        'desc' => '',
    ],
    [
        'type' => 'rec',
        'message' => 'CreateRoleResult',
        'msgid' => '1060',
        'desc' => ' 客户端的请求：创建新角色 返回值',
    ],
    [
        'type' => 'rec',
        'message' => 'DeleteRoleResult',
        'msgid' => '1061',
        'desc' => '',
    ],
    [
        'type' => 'rec',
        'message' => 'DestoryBuildResult',
        'msgid' => '1063',
        'desc' => '',
    ],
    [
        'type' => 'rec',
        'message' => 'GetMapResult',
        'msgid' => '1064',
        'desc' => '',
    ],
    [
        'type' => 'rec',
        'message' => 'GoldChangedResult',
        'msgid' => '1065',
        'desc' => '',
    ],
    [
        'type' => 'rec',
        'message' => 'JoinGameResult',
        'msgid' => '1066',
        'desc' => '',
    ],
    [
        'type' => 'rec',
        'message' => 'FriendAwardInfoResult',
        'msgid' => '1165',
        'desc' => '',
    ],
    [
        'type' => 'rec',
        'message' => 'LoadFinanceLogResult',
        'msgid' => '1067',
        'desc' => '',
    ],
    [
        'type' => 'rec',
        'message' => 'RemoveItemResult',
        'msgid' => '1068',
        'desc' => ' 移除物品返回',
    ],
    [
        'type' => 'rec',
        'message' => 'SellItemResult',
        'msgid' => '1069',
        'desc' => ' 出售道具返回',
    ],
    [
        'type' => 'rec',
        'message' => 'TCFinanceLogChangedResult',
        'msgid' => '1070',
        'desc' => '',
    ],
    [
        'type' => 'rec',
        'message' => 'TCLevelUpResult',
        'msgid' => '1071',
        'desc' => '',
    ],
    [
        'type' => 'rec',
        'message' => 'TCRoleBagChangeResult',
        'msgid' => '1072',
        'desc' => '',
    ],
    [
        'type' => 'rec',
        'message' => 'TCRoleInfoChangeResult',
        'msgid' => '1073',
        'desc' => '',
    ],
    [
        'type' => 'rec',
        'message' => 'UpdateAvatarResult',
        'msgid' => '1074',
        'desc' => '',
    ],
    [
        'type' => 'rec',
        'message' => 'UpdateShenjiaResult',
        'msgid' => '1075',
        'desc' => '',
    ],
    [
        'type' => 'rec',
        'message' => 'UpdateCompanyIncomeResult',
        'msgid' => '1116',
        'desc' => '',
    ],
    [
        'type' => 'rec',
        'message' => 'UseItemResult',
        'msgid' => '1078',
        'desc' => ' 使用物品返回',
    ],
    [
        'type' => 'rec',
        'message' => 'NewMsgResult',
        'msgid' => '2000',
        'desc' => '新消息返回',
    ],
    [
        'type' => 'send',
        'message' => 'ReadMsgReq',
        'msgid' => '2001',
        'desc' => '已读消息请求',
    ],
    [
        'type' => 'rec',
        'message' => 'ReadMsgResult',
        'msgid' => '2002',
        'desc' => '已读消息返回',
    ],
    [
        'type' => 'send',
        'message' => 'BankDepositReq',
        'msgid' => '2003',
        'desc' => '银行取款请求',
    ],
    [
        'type' => 'rec',
        'message' => 'BankDepositResult',
        'msgid' => '2004',
        'desc' => '银行取款返回',
    ],
    [
        'type' => 'send',
        'message' => 'GetAuctionLandReq',
        'msgid' => '2005',
        'desc' => ' 获取今日拍卖土地信息',
    ],
    [
        'type' => 'rec',
        'message' => 'GetAuctionLandResult',
        'msgid' => '2006',
        'desc' => ' 返回今日拍卖土地信息',
    ],
    [
        'type' => 'send',
        'message' => 'AuctionLandReq',
        'msgid' => '2007',
        'desc' => ' 竞拍土地请求',
    ],
    [
        'type' => 'rec',
        'message' => 'AuctionLandResult',
        'msgid' => '2008',
        'desc' => ' 返回竞拍土地',
    ],
    [
        'type' => 'send',
        'message' => 'GetMyLandInfoReq',
        'msgid' => '2009',
        'desc' => ' 已获得土地请求',
    ],
    [
        'type' => 'rec',
        'message' => 'MyLandInfoResult',
        'msgid' => '2010',
        'desc' => ' 已获得土地返回',
    ],
    [
        'type' => 'rec',
        'message' => 'ChatToChatResult',
        'msgid' => '3011',
        'desc' => '一对一聊天返回',
    ],
    [
        'type' => 'send',
        'message' => 'UseCompostReq',
        'msgid' => '2011',
        'desc' => ' 使用肥料请求',
    ],
    [
        'type' => 'rec',
        'message' => 'UseCompostResult',
        'msgid' => '2012',
        'desc' => ' 使用肥料返回',
    ],
    [
        'type' => 'send',
        'message' => 'RandManorReq',
        'msgid' => '2013',
        'desc' => '随机请求庄园请求',
    ],
    [
        'type' => 'rec',
        'message' => 'RandManorResult',
        'msgid' => '2014',
        'desc' => '随机请求庄园返回',
    ],
    [
        'type' => 'send',
        'message' => 'SalesListReq',
        'msgid' => '2015',
        'desc' => '交易行请求',
    ],
    [
        'type' => 'rec',
        'message' => 'SalesListResult',
        'msgid' => '2016',
        'desc' => '交易行请求返回',
    ],
    [
        'type' => 'send',
        'message' => 'UserSalesReq',
        'msgid' => '2017',
        'desc' => '寄卖请求',
    ],
    [
        'type' => 'rec',
        'message' => 'UserSalesResult',
        'msgid' => '2018',
        'desc' => '寄卖请求返回',
    ],
    [
        'type' => 'send',
        'message' => 'UserBuyReq',
        'msgid' => '2019',
        'desc' => '购买请求',
    ],
    [
        'type' => 'rec',
        'message' => 'UserBuyResult',
        'msgid' => '2020',
        'desc' => '购买请求返回',
    ],
    [
        'type' => 'send',
        'message' => 'SoldOutReq',
        'msgid' => '2021',
        'desc' => '下架请求',
    ],
    [
        'type' => 'rec',
        'message' => 'SoldOutResult',
        'msgid' => '2022',
        'desc' => '下架请求返回',
    ],
    [
        'type' => 'send',
        'message' => 'ChatConnectingReq',
        'msgid' => '3000',
        'desc' => ' 连接聊天服务器 //完成',
    ],
    [
        'type' => 'rec',
        'message' => 'ChatConnectingResult',
        'msgid' => '3001',
        'desc' => ' 连接聊天服务器返回-1成功-2失败-失败会被踢掉-//完成',
    ],
    [
        'type' => 'send',
        'message' => 'ChatSendMsgToChannelReq',
        'msgid' => '3002',
        'desc' => ' 向频道中发送消息-//结构体有待商榷',
    ],
    [
        'type' => 'rec',
        'message' => 'ChatSendMsgToChannelResult',
        'msgid' => '3003',
        'desc' => ' 向频道中发送消息返回-//结构体有待商榷',
    ],
    [
        'type' => 'rec',
        'message' => 'ChatMsgFromChannelResult',
        'msgid' => '3004',
        'desc' => ' 主动下发消息到频道中-//结构体有待商榷',
    ],
    [
        'type' => 'rec',
        'message' => 'ChatTCRecMsgHorseResult',
        'msgid' => '3005',
        'desc' => ' 跑马灯消息 系统消息-//完成',
    ],
    [
        'type' => 'rec',
        'message' => 'ChatTCRecSystemMsgResult',
        'msgid' => '3006',
        'desc' => ' 系统消息-//完成',
    ],
    [
        'type' => 'rec',
        'message' => 'ChatNoReadResult',
        'msgid' => '3007',
        'desc' => ' 一对一聊天-返回-//完成',
    ],
    [
        'type' => 'send',
        'message' => 'ChatOneToOneReq',
        'msgid' => '3008',
        'desc' => ' 一对一聊天-发送-//完成',
    ],
    [
        'type' => 'send',
        'message' => 'ChatMesaageReadReq',
        'msgid' => '3009',
        'desc' => ' 消息已读-发送-//完成',
    ],
    [
        'type' => 'rec',
        'message' => 'ChatMessageUnreadListResult',
        'msgid' => '3010',
        'desc' => '未读消息列表',
    ],
    [
        'type' => 'send',
        'message' => 'NpcListReq',
        'msgid' =>'2023',
        'desc'=>'获取Npc列表',
    ],
    [
        'type' => 'rec',
        'message' => 'NpcListResult',
        'msgid' =>'2024',
        'desc'=>'返回npc列表',
    ],
    [
        'type' => 'send',
        'message' => 'UnlockNpcReq',
        'msgid' =>'2025',
        'desc'=>'解锁npc',
    ],
    [
        'type' => 'rec',
        'message' => 'UnlockNpcResult',
        'msgid' =>'2026',
        'desc'=>'返回解锁npc',
    ],
    [
        'type'=>'send',
        'message'=>'PkRankingReq',
        'msgid'=>'2027',
        'desc'=>'pk排行榜请求'
    ],
    [
        'type'=>'rec',
        'message'=>'PkRankingResult',
        'msgid'=>'2028',
        'desc'=>'pk排行榜返回'
    ],
    [
    'type'=>'send',
    'message'=>'SignNameReq',
    'msgid'=>'2029',
    'desc'=>'修改签名请求'
    ],
    [
        'type'=>'rec',
        'message'=>'SignNameResult',
        'msgid'=>'2030',
        'desc'=>'修改签名返回'
    ],
    [
        'type'=>'send',
        'message'=>'TalkingGroupResidentReq',
        'msgid'=>'2031',
        'desc'=>'谈判团任居民任命请求'
    ],
    [
        'type'=>'rec',
        'message'=>'TalkingGroupResidentResult',
        'msgid'=>'2032',
        'desc'=>'谈判团任居民任命返回'
    ],
    [
        'type'=>'send',
        'message'=>'TalkIngGroupResidentChangeReq',
        'msgid'=>'2033',
        'desc'=>'谈判团任居民任命请求'
    ],
    [
        'type'=>'rec',
        'message'=>'TalkIngGroupResidentChangeResult',
        'msgid'=>'2034',
        'desc'=>'谈判团任居民任命返回'
    ]

];
