<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protomsg.proto

namespace AutoMsg;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>AutoMsg.AccomplishResidentDelegateResult</code>
 */
class AccomplishResidentDelegateResult extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 Spot = 1;</code>
     */
    private $Spot = 0;
    /**
     * Generated from protobuf field <code>.AutoMsg.NpcTask NpcTask = 2;</code>
     */
    private $NpcTask = null;

    public function __construct() {
        \GPBMetadata\Protomsg::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>int32 Spot = 1;</code>
     * @return int
     */
    public function getSpot()
    {
        return $this->Spot;
    }

    /**
     * Generated from protobuf field <code>int32 Spot = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setSpot($var)
    {
        GPBUtil::checkInt32($var);
        $this->Spot = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.AutoMsg.NpcTask NpcTask = 2;</code>
     * @return \AutoMsg\NpcTask
     */
    public function getNpcTask()
    {
        return $this->NpcTask;
    }

    /**
     * Generated from protobuf field <code>.AutoMsg.NpcTask NpcTask = 2;</code>
     * @param \AutoMsg\NpcTask $var
     * @return $this
     */
    public function setNpcTask($var)
    {
        GPBUtil::checkMessage($var, \AutoMsg\NpcTask::class);
        $this->NpcTask = $var;

        return $this;
    }

}

