<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protomsg.proto

namespace AutoMsg;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>AutoMsg.AccomplishResidentDelegateResult</code>
 */
class AccomplishResidentDelegateResult extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>map<int32, .AutoMsg.LoadResidentDelegate> ItemCount = 1;</code>
     */
    private $ItemCount;
    /**
     * Generated from protobuf field <code>int32 Count = 2;</code>
     */
    private $Count = 0;

    public function __construct() {
        \GPBMetadata\Protomsg::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>map<int32, .AutoMsg.LoadResidentDelegate> ItemCount = 1;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getItemCount()
    {
        return $this->ItemCount;
    }

    /**
     * Generated from protobuf field <code>map<int32, .AutoMsg.LoadResidentDelegate> ItemCount = 1;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setItemCount($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::INT32, \Google\Protobuf\Internal\GPBType::MESSAGE, \AutoMsg\LoadResidentDelegate::class);
        $this->ItemCount = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 Count = 2;</code>
     * @return int
     */
    public function getCount()
    {
        return $this->Count;
    }

    /**
     * Generated from protobuf field <code>int32 Count = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setCount($var)
    {
        GPBUtil::checkInt32($var);
        $this->Count = $var;

        return $this;
    }

}

