<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protomsg.proto

namespace AutoMsg;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>AutoMsg.AddNpcFavorability</code>
 */
class AddNpcFavorability extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 NpcId = 1;</code>
     */
    private $NpcId = 0;
    /**
     * Generated from protobuf field <code>int32 ItemId = 2;</code>
     */
    private $ItemId = 0;
    /**
     * Generated from protobuf field <code>int32 ItemCount = 3;</code>
     */
    private $ItemCount = 0;

    public function __construct() {
        \GPBMetadata\Protomsg::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>int32 NpcId = 1;</code>
     * @return int
     */
    public function getNpcId()
    {
        return $this->NpcId;
    }

    /**
     * Generated from protobuf field <code>int32 NpcId = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setNpcId($var)
    {
        GPBUtil::checkInt32($var);
        $this->NpcId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 ItemId = 2;</code>
     * @return int
     */
    public function getItemId()
    {
        return $this->ItemId;
    }

    /**
     * Generated from protobuf field <code>int32 ItemId = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setItemId($var)
    {
        GPBUtil::checkInt32($var);
        $this->ItemId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 ItemCount = 3;</code>
     * @return int
     */
    public function getItemCount()
    {
        return $this->ItemCount;
    }

    /**
     * Generated from protobuf field <code>int32 ItemCount = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setItemCount($var)
    {
        GPBUtil::checkInt32($var);
        $this->ItemCount = $var;

        return $this;
    }

}

