<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Src/protomsg.proto

namespace AutoMsg;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>AutoMsg.BiddingGoodsReq</code>
 */
class BiddingGoodsReq extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string DealId = 1;</code>
     */
    private $DealId = '';
    /**
     * Generated from protobuf field <code>int64 GoldCount = 2;</code>
     */
    private $GoldCount = 0;

    public function __construct() {
        \GPBMetadata\Src\Protomsg::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>string DealId = 1;</code>
     * @return string
     */
    public function getDealId()
    {
        return $this->DealId;
    }

    /**
     * Generated from protobuf field <code>string DealId = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setDealId($var)
    {
        GPBUtil::checkString($var, True);
        $this->DealId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 GoldCount = 2;</code>
     * @return int|string
     */
    public function getGoldCount()
    {
        return $this->GoldCount;
    }

    /**
     * Generated from protobuf field <code>int64 GoldCount = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setGoldCount($var)
    {
        GPBUtil::checkInt64($var);
        $this->GoldCount = $var;

        return $this;
    }

}

