<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protomsg.proto

namespace AutoMsg;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>AutoMsg.BuildAdvReq</code>
 */
class BuildAdvReq extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated string BuildingIds = 1;</code>
     */
    private $BuildingIds;

    public function __construct() {
        \GPBMetadata\Protomsg::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>repeated string BuildingIds = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getBuildingIds()
    {
        return $this->BuildingIds;
    }

    /**
     * Generated from protobuf field <code>repeated string BuildingIds = 1;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setBuildingIds($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->BuildingIds = $arr;

        return $this;
    }

}

