<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protomsg.proto

namespace AutoMsg;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>AutoMsg.CKPayLogResult</code>
 */
class CKPayLogResult extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string LgId = 1;</code>
     */
    private $LgId = '';
    /**
     * Generated from protobuf field <code>string LgMemberId = 2;</code>
     */
    private $LgMemberId = '';
    /**
     * Generated from protobuf field <code>string LgMemberName = 3;</code>
     */
    private $LgMemberName = '';
    /**
     * Generated from protobuf field <code>string LgAdminName = 4;</code>
     */
    private $LgAdminName = '';
    /**
     * Generated from protobuf field <code>string LgType = 5;</code>
     */
    private $LgType = '';
    /**
     * Generated from protobuf field <code>string LgAvAmount = 6;</code>
     */
    private $LgAvAmount = '';
    /**
     * Generated from protobuf field <code>string LgFreezeAmount = 7;</code>
     */
    private $LgFreezeAmount = '';
    /**
     * Generated from protobuf field <code>string LgAddTime = 8;</code>
     */
    private $LgAddTime = '';
    /**
     * Generated from protobuf field <code>string LgDesc = 9;</code>
     */
    private $LgDesc = '';
    /**
     * Generated from protobuf field <code>string LgInviteMemberId = 10;</code>
     */
    private $LgInviteMemberId = '';
    /**
     * Generated from protobuf field <code>string LgAdminMemo = 11;</code>
     */
    private $LgAdminMemo = '';
    /**
     * Generated from protobuf field <code>string LgSourceOnly = 12;</code>
     */
    private $LgSourceOnly = '';

    public function __construct() {
        \GPBMetadata\Protomsg::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>string LgId = 1;</code>
     * @return string
     */
    public function getLgId()
    {
        return $this->LgId;
    }

    /**
     * Generated from protobuf field <code>string LgId = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setLgId($var)
    {
        GPBUtil::checkString($var, True);
        $this->LgId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string LgMemberId = 2;</code>
     * @return string
     */
    public function getLgMemberId()
    {
        return $this->LgMemberId;
    }

    /**
     * Generated from protobuf field <code>string LgMemberId = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setLgMemberId($var)
    {
        GPBUtil::checkString($var, True);
        $this->LgMemberId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string LgMemberName = 3;</code>
     * @return string
     */
    public function getLgMemberName()
    {
        return $this->LgMemberName;
    }

    /**
     * Generated from protobuf field <code>string LgMemberName = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setLgMemberName($var)
    {
        GPBUtil::checkString($var, True);
        $this->LgMemberName = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string LgAdminName = 4;</code>
     * @return string
     */
    public function getLgAdminName()
    {
        return $this->LgAdminName;
    }

    /**
     * Generated from protobuf field <code>string LgAdminName = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setLgAdminName($var)
    {
        GPBUtil::checkString($var, True);
        $this->LgAdminName = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string LgType = 5;</code>
     * @return string
     */
    public function getLgType()
    {
        return $this->LgType;
    }

    /**
     * Generated from protobuf field <code>string LgType = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setLgType($var)
    {
        GPBUtil::checkString($var, True);
        $this->LgType = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string LgAvAmount = 6;</code>
     * @return string
     */
    public function getLgAvAmount()
    {
        return $this->LgAvAmount;
    }

    /**
     * Generated from protobuf field <code>string LgAvAmount = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setLgAvAmount($var)
    {
        GPBUtil::checkString($var, True);
        $this->LgAvAmount = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string LgFreezeAmount = 7;</code>
     * @return string
     */
    public function getLgFreezeAmount()
    {
        return $this->LgFreezeAmount;
    }

    /**
     * Generated from protobuf field <code>string LgFreezeAmount = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setLgFreezeAmount($var)
    {
        GPBUtil::checkString($var, True);
        $this->LgFreezeAmount = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string LgAddTime = 8;</code>
     * @return string
     */
    public function getLgAddTime()
    {
        return $this->LgAddTime;
    }

    /**
     * Generated from protobuf field <code>string LgAddTime = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setLgAddTime($var)
    {
        GPBUtil::checkString($var, True);
        $this->LgAddTime = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string LgDesc = 9;</code>
     * @return string
     */
    public function getLgDesc()
    {
        return $this->LgDesc;
    }

    /**
     * Generated from protobuf field <code>string LgDesc = 9;</code>
     * @param string $var
     * @return $this
     */
    public function setLgDesc($var)
    {
        GPBUtil::checkString($var, True);
        $this->LgDesc = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string LgInviteMemberId = 10;</code>
     * @return string
     */
    public function getLgInviteMemberId()
    {
        return $this->LgInviteMemberId;
    }

    /**
     * Generated from protobuf field <code>string LgInviteMemberId = 10;</code>
     * @param string $var
     * @return $this
     */
    public function setLgInviteMemberId($var)
    {
        GPBUtil::checkString($var, True);
        $this->LgInviteMemberId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string LgAdminMemo = 11;</code>
     * @return string
     */
    public function getLgAdminMemo()
    {
        return $this->LgAdminMemo;
    }

    /**
     * Generated from protobuf field <code>string LgAdminMemo = 11;</code>
     * @param string $var
     * @return $this
     */
    public function setLgAdminMemo($var)
    {
        GPBUtil::checkString($var, True);
        $this->LgAdminMemo = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string LgSourceOnly = 12;</code>
     * @return string
     */
    public function getLgSourceOnly()
    {
        return $this->LgSourceOnly;
    }

    /**
     * Generated from protobuf field <code>string LgSourceOnly = 12;</code>
     * @param string $var
     * @return $this
     */
    public function setLgSourceOnly($var)
    {
        GPBUtil::checkString($var, True);
        $this->LgSourceOnly = $var;

        return $this;
    }

}

