<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Src/protomsg.proto

namespace AutoMsg;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>AutoMsg.ClearStateResult</code>
 */
class ClearStateResult extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 Id = 1;</code>
     */
    private $Id = 0;
    /**
     * Generated from protobuf field <code>int32 State = 2;</code>
     */
    private $State = 0;
    /**
     * Generated from protobuf field <code>int32 SemenId = 3;</code>
     */
    private $SemenId = 0;
    /**
     * Generated from protobuf field <code>int32 Count = 4;</code>
     */
    private $Count = 0;

    public function __construct() {
        \GPBMetadata\Src\Protomsg::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>int32 Id = 1;</code>
     * @return int
     */
    public function getId()
    {
        return $this->Id;
    }

    /**
     * Generated from protobuf field <code>int32 Id = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkInt32($var);
        $this->Id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 State = 2;</code>
     * @return int
     */
    public function getState()
    {
        return $this->State;
    }

    /**
     * Generated from protobuf field <code>int32 State = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setState($var)
    {
        GPBUtil::checkInt32($var);
        $this->State = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 SemenId = 3;</code>
     * @return int
     */
    public function getSemenId()
    {
        return $this->SemenId;
    }

    /**
     * Generated from protobuf field <code>int32 SemenId = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setSemenId($var)
    {
        GPBUtil::checkInt32($var);
        $this->SemenId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 Count = 4;</code>
     * @return int
     */
    public function getCount()
    {
        return $this->Count;
    }

    /**
     * Generated from protobuf field <code>int32 Count = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setCount($var)
    {
        GPBUtil::checkInt32($var);
        $this->Count = $var;

        return $this;
    }

}

