<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protomsg.proto

namespace AutoMsg;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>AutoMsg.ComeOutEmployeeReq</code>
 */
class ComeOutEmployeeReq extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string ShopId = 1;</code>
     */
    private $ShopId = '';
    /**
     * Generated from protobuf field <code>int32 ComeOutInEmployee = 2;</code>
     */
    private $ComeOutInEmployee = 0;
    /**
     *原int32改成string
     *
     * Generated from protobuf field <code>repeated string NpcCardId = 3;</code>
     */
    private $NpcCardId;

    public function __construct() {
        \GPBMetadata\Protomsg::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>string ShopId = 1;</code>
     * @return string
     */
    public function getShopId()
    {
        return $this->ShopId;
    }

    /**
     * Generated from protobuf field <code>string ShopId = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setShopId($var)
    {
        GPBUtil::checkString($var, True);
        $this->ShopId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 ComeOutInEmployee = 2;</code>
     * @return int
     */
    public function getComeOutInEmployee()
    {
        return $this->ComeOutInEmployee;
    }

    /**
     * Generated from protobuf field <code>int32 ComeOutInEmployee = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setComeOutInEmployee($var)
    {
        GPBUtil::checkInt32($var);
        $this->ComeOutInEmployee = $var;

        return $this;
    }

    /**
     *原int32改成string
     *
     * Generated from protobuf field <code>repeated string NpcCardId = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getNpcCardId()
    {
        return $this->NpcCardId;
    }

    /**
     *原int32改成string
     *
     * Generated from protobuf field <code>repeated string NpcCardId = 3;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setNpcCardId($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->NpcCardId = $arr;

        return $this;
    }

}

