<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Src/protomsg.proto

namespace AutoMsg;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>AutoMsg.CompanyExpResult</code>
 */
class CompanyExpResult extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 Exp = 1;</code>
     */
    private $Exp = 0;

    public function __construct() {
        \GPBMetadata\Src\Protomsg::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>int64 Exp = 1;</code>
     * @return int|string
     */
    public function getExp()
    {
        return $this->Exp;
    }

    /**
     * Generated from protobuf field <code>int64 Exp = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setExp($var)
    {
        GPBUtil::checkInt64($var);
        $this->Exp = $var;

        return $this;
    }

}

