<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protomsg.proto

namespace AutoMsg;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>AutoMsg.ConnectingResult</code>
 */
class ConnectingResult extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .AutoMsg.Common Common = 1;</code>
     */
    private $RoleLists;

    public function __construct() {
        \GPBMetadata\Protomsg::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>repeated .AutoMsg.Common Common = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getRoleLists()
    {
        return $this->RoleLists;
    }

    /**
     * Generated from protobuf field <code>repeated .AutoMsg.Common Common = 1;</code>
     * @param \AutoMsg\RoleLists[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setRoleLists($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \AutoMsg\RoleLists::class);
        $this->RoleLists = $arr;

        return $this;
    }

}

