<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Src/protomsg.proto

namespace AutoMsg;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>AutoMsg.CultivateEmployeeResult</code>
 */
class CultivateEmployeeResult extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .AutoMsg.LoadRefStaff CultivateStaffList = 1;</code>
     */
    private $CultivateStaffList;
    /**
     *员工id 每天培训次数
     *
     * Generated from protobuf field <code>map<int32, int32> TrainTime = 2;</code>
     */
    private $TrainTime;

    public function __construct() {
        \GPBMetadata\Src\Protomsg::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>repeated .AutoMsg.LoadRefStaff CultivateStaffList = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getCultivateStaffList()
    {
        return $this->CultivateStaffList;
    }

    /**
     * Generated from protobuf field <code>repeated .AutoMsg.LoadRefStaff CultivateStaffList = 1;</code>
     * @param \AutoMsg\LoadRefStaff[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setCultivateStaffList($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \AutoMsg\LoadRefStaff::class);
        $this->CultivateStaffList = $arr;

        return $this;
    }

    /**
     *员工id 每天培训次数
     *
     * Generated from protobuf field <code>map<int32, int32> TrainTime = 2;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getTrainTime()
    {
        return $this->TrainTime;
    }

    /**
     *员工id 每天培训次数
     *
     * Generated from protobuf field <code>map<int32, int32> TrainTime = 2;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setTrainTime($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::INT32, \Google\Protobuf\Internal\GPBType::INT32);
        $this->TrainTime = $arr;

        return $this;
    }

}

