<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protomsg.proto

namespace AutoMsg;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>AutoMsg.CultivateEmployeeResult</code>
 */
class CultivateEmployeeResult extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .AutoMsg.LoadRefStaff CultivateStaffList = 1;</code>
     */
    private $CultivateStaffList;
    /**
     * Generated from protobuf field <code>int32 TrainTime = 2;</code>
     */
    private $TrainTime = 0;

    public function __construct() {
        \GPBMetadata\Protomsg::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>repeated .AutoMsg.LoadRefStaff CultivateStaffList = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getCultivateStaffList()
    {
        return $this->CultivateStaffList;
    }

    /**
     * Generated from protobuf field <code>repeated .AutoMsg.LoadRefStaff CultivateStaffList = 1;</code>
     * @param \AutoMsg\LoadRefStaff[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setCultivateStaffList($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \AutoMsg\LoadRefStaff::class);
        $this->CultivateStaffList = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 TrainTime = 2;</code>
     * @return int
     */
    public function getTrainTime()
    {
        return $this->TrainTime;
    }

    /**
     * Generated from protobuf field <code>int32 TrainTime = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setTrainTime($var)
    {
        GPBUtil::checkInt32($var);
        $this->TrainTime = $var;

        return $this;
    }

}

