<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Src/protomsg.proto

namespace AutoMsg;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>AutoMsg.DropShopPingReq</code>
 */
class DropShopPingReq extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 DropKuId = 1;</code>
     */
    private $DropKuId = 0;
    /**
     * Generated from protobuf field <code>int32 ItemId = 2;</code>
     */
    private $ItemId = 0;
    /**
     * Generated from protobuf field <code>int32 ShopTypeId = 3;</code>
     */
    private $ShopTypeId = 0;
    /**
     * Generated from protobuf field <code>int32 GridId = 4;</code>
     */
    private $GridId = 0;

    public function __construct() {
        \GPBMetadata\Src\Protomsg::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>int32 DropKuId = 1;</code>
     * @return int
     */
    public function getDropKuId()
    {
        return $this->DropKuId;
    }

    /**
     * Generated from protobuf field <code>int32 DropKuId = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setDropKuId($var)
    {
        GPBUtil::checkInt32($var);
        $this->DropKuId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 ItemId = 2;</code>
     * @return int
     */
    public function getItemId()
    {
        return $this->ItemId;
    }

    /**
     * Generated from protobuf field <code>int32 ItemId = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setItemId($var)
    {
        GPBUtil::checkInt32($var);
        $this->ItemId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 ShopTypeId = 3;</code>
     * @return int
     */
    public function getShopTypeId()
    {
        return $this->ShopTypeId;
    }

    /**
     * Generated from protobuf field <code>int32 ShopTypeId = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setShopTypeId($var)
    {
        GPBUtil::checkInt32($var);
        $this->ShopTypeId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 GridId = 4;</code>
     * @return int
     */
    public function getGridId()
    {
        return $this->GridId;
    }

    /**
     * Generated from protobuf field <code>int32 GridId = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setGridId($var)
    {
        GPBUtil::checkInt32($var);
        $this->GridId = $var;

        return $this;
    }

}

