<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protomsg.proto

namespace AutoMsg;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>AutoMsg.DropShopPingResult</code>
 */
class DropShopPingResult extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.AutoMsg.LoadDropData LoadConsume = 1;</code>
     */
    private $LoadConsume = null;

    public function __construct() {
        \GPBMetadata\Protomsg::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>.AutoMsg.LoadDropData LoadConsume = 1;</code>
     * @return \AutoMsg\LoadDropData
     */
    public function getLoadConsume()
    {
        return $this->LoadConsume;
    }

    /**
     * Generated from protobuf field <code>.AutoMsg.LoadDropData LoadConsume = 1;</code>
     * @param \AutoMsg\LoadDropData $var
     * @return $this
     */
    public function setLoadConsume($var)
    {
        GPBUtil::checkMessage($var, \AutoMsg\LoadDropData::class);
        $this->LoadConsume = $var;

        return $this;
    }

}

