<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Src/protomsg.proto

namespace AutoMsg;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>AutoMsg.FireLeaderReq</code>
 */
class FireLeaderReq extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string BuildId = 1;</code>
     */
    private $BuildId = '';
    /**
     * Generated from protobuf field <code>string FriendId = 2;</code>
     */
    private $FriendId = '';

    public function __construct() {
        \GPBMetadata\Src\Protomsg::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>string BuildId = 1;</code>
     * @return string
     */
    public function getBuildId()
    {
        return $this->BuildId;
    }

    /**
     * Generated from protobuf field <code>string BuildId = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setBuildId($var)
    {
        GPBUtil::checkString($var, True);
        $this->BuildId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string FriendId = 2;</code>
     * @return string
     */
    public function getFriendId()
    {
        return $this->FriendId;
    }

    /**
     * Generated from protobuf field <code>string FriendId = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setFriendId($var)
    {
        GPBUtil::checkString($var, True);
        $this->FriendId = $var;

        return $this;
    }

}

