<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Src/protomsg.proto

namespace AutoMsg;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>AutoMsg.FireLeaderResult</code>
 */
class FireLeaderResult extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string BuildId = 1;</code>
     */
    private $BuildId = '';
    /**
     * Generated from protobuf field <code>int64 Money = 2;</code>
     */
    private $Money = 0;
    /**
     * Generated from protobuf field <code>int64 MoneyType = 3;</code>
     */
    private $MoneyType = 0;

    public function __construct() {
        \GPBMetadata\Src\Protomsg::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>string BuildId = 1;</code>
     * @return string
     */
    public function getBuildId()
    {
        return $this->BuildId;
    }

    /**
     * Generated from protobuf field <code>string BuildId = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setBuildId($var)
    {
        GPBUtil::checkString($var, True);
        $this->BuildId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 Money = 2;</code>
     * @return int|string
     */
    public function getMoney()
    {
        return $this->Money;
    }

    /**
     * Generated from protobuf field <code>int64 Money = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setMoney($var)
    {
        GPBUtil::checkInt64($var);
        $this->Money = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 MoneyType = 3;</code>
     * @return int|string
     */
    public function getMoneyType()
    {
        return $this->MoneyType;
    }

    /**
     * Generated from protobuf field <code>int64 MoneyType = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setMoneyType($var)
    {
        GPBUtil::checkInt64($var);
        $this->MoneyType = $var;

        return $this;
    }

}

