<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Src/protomsg.proto

namespace AutoMsg;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>AutoMsg.FriendInfo</code>
 */
class FriendInfo extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string Name = 1;</code>
     */
    private $Name = '';
    /**
     * Generated from protobuf field <code>string Icon = 2;</code>
     */
    private $Icon = '';
    /**
     * Generated from protobuf field <code>int32 VIP = 3;</code>
     */
    private $VIP = 0;
    /**
     * Generated from protobuf field <code>int64 SocialStatus = 4;</code>
     */
    private $SocialStatus = 0;
    /**
     * Generated from protobuf field <code>uint32 Status = 5;</code>
     */
    private $Status = 0;
    /**
     * Generated from protobuf field <code>int32 OnlineTime = 6;</code>
     */
    private $OnlineTime = 0;
    /**
     * Generated from protobuf field <code>int32 AddTime = 7;</code>
     */
    private $AddTime = 0;
    /**
     * Generated from protobuf field <code>int32 ApplyTime = 8;</code>
     */
    private $ApplyTime = 0;
    /**
     * Generated from protobuf field <code>string RoleId = 9;</code>
     */
    private $RoleId = '';
    /**
     * Generated from protobuf field <code>int32 Level = 10;</code>
     */
    private $Level = 0;
    /**
     * Generated from protobuf field <code>int32 FriendValue = 13;</code>
     */
    private $FriendValue = 0;
    /**
     * Generated from protobuf field <code>string WorkCompany = 14;</code>
     */
    private $WorkCompany = '';
    /**
     * Generated from protobuf field <code>int32 DigCount = 15;</code>
     */
    private $DigCount = 0;
    /**
     * Generated from protobuf field <code>string ShopId = 16;</code>
     */
    private $ShopId = '';
    /**
     * Generated from protobuf field <code>int32 HireTime = 17;</code>
     */
    private $HireTime = 0;

    public function __construct() {
        \GPBMetadata\Src\Protomsg::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>string Name = 1;</code>
     * @return string
     */
    public function getName()
    {
        return $this->Name;
    }

    /**
     * Generated from protobuf field <code>string Name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->Name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string Icon = 2;</code>
     * @return string
     */
    public function getIcon()
    {
        return $this->Icon;
    }

    /**
     * Generated from protobuf field <code>string Icon = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setIcon($var)
    {
        GPBUtil::checkString($var, True);
        $this->Icon = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 VIP = 3;</code>
     * @return int
     */
    public function getVIP()
    {
        return $this->VIP;
    }

    /**
     * Generated from protobuf field <code>int32 VIP = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setVIP($var)
    {
        GPBUtil::checkInt32($var);
        $this->VIP = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 SocialStatus = 4;</code>
     * @return int|string
     */
    public function getSocialStatus()
    {
        return $this->SocialStatus;
    }

    /**
     * Generated from protobuf field <code>int64 SocialStatus = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setSocialStatus($var)
    {
        GPBUtil::checkInt64($var);
        $this->SocialStatus = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 Status = 5;</code>
     * @return int
     */
    public function getStatus()
    {
        return $this->Status;
    }

    /**
     * Generated from protobuf field <code>uint32 Status = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkUint32($var);
        $this->Status = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 OnlineTime = 6;</code>
     * @return int
     */
    public function getOnlineTime()
    {
        return $this->OnlineTime;
    }

    /**
     * Generated from protobuf field <code>int32 OnlineTime = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setOnlineTime($var)
    {
        GPBUtil::checkInt32($var);
        $this->OnlineTime = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 AddTime = 7;</code>
     * @return int
     */
    public function getAddTime()
    {
        return $this->AddTime;
    }

    /**
     * Generated from protobuf field <code>int32 AddTime = 7;</code>
     * @param int $var
     * @return $this
     */
    public function setAddTime($var)
    {
        GPBUtil::checkInt32($var);
        $this->AddTime = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 ApplyTime = 8;</code>
     * @return int
     */
    public function getApplyTime()
    {
        return $this->ApplyTime;
    }

    /**
     * Generated from protobuf field <code>int32 ApplyTime = 8;</code>
     * @param int $var
     * @return $this
     */
    public function setApplyTime($var)
    {
        GPBUtil::checkInt32($var);
        $this->ApplyTime = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string RoleId = 9;</code>
     * @return string
     */
    public function getRoleId()
    {
        return $this->RoleId;
    }

    /**
     * Generated from protobuf field <code>string RoleId = 9;</code>
     * @param string $var
     * @return $this
     */
    public function setRoleId($var)
    {
        GPBUtil::checkString($var, True);
        $this->RoleId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 Level = 10;</code>
     * @return int
     */
    public function getLevel()
    {
        return $this->Level;
    }

    /**
     * Generated from protobuf field <code>int32 Level = 10;</code>
     * @param int $var
     * @return $this
     */
    public function setLevel($var)
    {
        GPBUtil::checkInt32($var);
        $this->Level = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 FriendValue = 13;</code>
     * @return int
     */
    public function getFriendValue()
    {
        return $this->FriendValue;
    }

    /**
     * Generated from protobuf field <code>int32 FriendValue = 13;</code>
     * @param int $var
     * @return $this
     */
    public function setFriendValue($var)
    {
        GPBUtil::checkInt32($var);
        $this->FriendValue = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string WorkCompany = 14;</code>
     * @return string
     */
    public function getWorkCompany()
    {
        return $this->WorkCompany;
    }

    /**
     * Generated from protobuf field <code>string WorkCompany = 14;</code>
     * @param string $var
     * @return $this
     */
    public function setWorkCompany($var)
    {
        GPBUtil::checkString($var, True);
        $this->WorkCompany = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 DigCount = 15;</code>
     * @return int
     */
    public function getDigCount()
    {
        return $this->DigCount;
    }

    /**
     * Generated from protobuf field <code>int32 DigCount = 15;</code>
     * @param int $var
     * @return $this
     */
    public function setDigCount($var)
    {
        GPBUtil::checkInt32($var);
        $this->DigCount = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string ShopId = 16;</code>
     * @return string
     */
    public function getShopId()
    {
        return $this->ShopId;
    }

    /**
     * Generated from protobuf field <code>string ShopId = 16;</code>
     * @param string $var
     * @return $this
     */
    public function setShopId($var)
    {
        GPBUtil::checkString($var, True);
        $this->ShopId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 HireTime = 17;</code>
     * @return int
     */
    public function getHireTime()
    {
        return $this->HireTime;
    }

    /**
     * Generated from protobuf field <code>int32 HireTime = 17;</code>
     * @param int $var
     * @return $this
     */
    public function setHireTime($var)
    {
        GPBUtil::checkInt32($var);
        $this->HireTime = $var;

        return $this;
    }

}

