<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protomsg.proto

namespace AutoMsg;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>AutoMsg.FriendBaseResult</code>
 */
class FriendBaseResult extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string RoleId = 1;</code>
     */
    private $RoleId = '';
    /**
     * Generated from protobuf field <code>int64 SocialStatus = 2;</code>
     */
    private $SocialStatus = 0;

    public function __construct() {
        \GPBMetadata\Protomsg::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>string RoleId = 1;</code>
     * @return string
     */
    public function getRoleId()
    {
        return $this->RoleId;
    }

    /**
     * Generated from protobuf field <code>string RoleId = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setRoleId($var)
    {
        GPBUtil::checkString($var, True);
        $this->RoleId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 SocialStatus = 2;</code>
     * @return int|string
     */
    public function getSocialStatus()
    {
        return $this->SocialStatus;
    }

    /**
     * Generated from protobuf field <code>int64 SocialStatus = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setSocialStatus($var)
    {
        GPBUtil::checkInt64($var);
        $this->SocialStatus = $var;

        return $this;
    }

}

