<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Src/protomsg.proto

namespace AutoMsg;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>AutoMsg.FriendAddBlackResult</code>
 */
class FriendAddBlackResult extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.AutoMsg.FriendInfo Role = 1;</code>
     */
    private $Role = null;

    public function __construct() {
        \GPBMetadata\Src\Protomsg::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>.AutoMsg.FriendInfo Role = 1;</code>
     * @return \AutoMsg\FriendInfo
     */
    public function getRole()
    {
        return $this->Role;
    }

    /**
     * Generated from protobuf field <code>.AutoMsg.FriendInfo Role = 1;</code>
     * @param \AutoMsg\FriendInfo $var
     * @return $this
     */
    public function setRole($var)
    {
        GPBUtil::checkMessage($var, \AutoMsg\FriendInfo::class);
        $this->Role = $var;

        return $this;
    }

}

