<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Src/protomsg.proto

namespace AutoMsg;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>AutoMsg.FriendSearchReq</code>
 */
class FriendSearchReq extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string Name = 1;</code>
     */
    private $Name = '';
    /**
     * Generated from protobuf field <code>bool Search = 2;</code>
     */
    private $Search = false;

    public function __construct() {
        \GPBMetadata\Src\Protomsg::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>string Name = 1;</code>
     * @return string
     */
    public function getName()
    {
        return $this->Name;
    }

    /**
     * Generated from protobuf field <code>string Name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->Name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool Search = 2;</code>
     * @return bool
     */
    public function getSearch()
    {
        return $this->Search;
    }

    /**
     * Generated from protobuf field <code>bool Search = 2;</code>
     * @param bool $var
     * @return $this
     */
    public function setSearch($var)
    {
        GPBUtil::checkBool($var);
        $this->Search = $var;

        return $this;
    }

}

