<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Src/protomsg.proto

namespace AutoMsg;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *拒绝好友申请 返回
 *
 * Generated from protobuf message <code>AutoMsg.FriendApplyClearResult</code>
 */
class FriendApplyClearResult extends \Google\Protobuf\Internal\Message
{
    /**
     *拒绝人的信息
     *
     * Generated from protobuf field <code>repeated .AutoMsg.FriendInfo Info = 1;</code>
     */
    private $Info;
    /**
     *是否是自己发出的申请
     *
     * Generated from protobuf field <code>bool To = 2;</code>
     */
    private $To = false;

    public function __construct() {
        \GPBMetadata\Src\Protomsg::initOnce();
        parent::__construct();
    }

    /**
     *拒绝人的信息
     *
     * Generated from protobuf field <code>repeated .AutoMsg.FriendInfo Info = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getInfo()
    {
        return $this->Info;
    }

    /**
     *拒绝人的信息
     *
     * Generated from protobuf field <code>repeated .AutoMsg.FriendInfo Info = 1;</code>
     * @param \AutoMsg\FriendInfo[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setInfo($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \AutoMsg\FriendInfo::class);
        $this->Info = $arr;

        return $this;
    }

    /**
     *是否是自己发出的申请
     *
     * Generated from protobuf field <code>bool To = 2;</code>
     * @return bool
     */
    public function getTo()
    {
        return $this->To;
    }

    /**
     *是否是自己发出的申请
     *
     * Generated from protobuf field <code>bool To = 2;</code>
     * @param bool $var
     * @return $this
     */
    public function setTo($var)
    {
        GPBUtil::checkBool($var);
        $this->To = $var;

        return $this;
    }

}

