<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protomsg.proto

namespace AutoMsg;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>AutoMsg.GetManagerInfoResult</code>
 */
class GetManagerInfoResult extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .AutoMsg.LoadRefStaff LoadRefStaffList = 1;</code>
     */
    private $LoadRefStaffList;

    public function __construct() {
        \GPBMetadata\Protomsg::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>repeated .AutoMsg.LoadRefStaff LoadRefStaffList = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getLoadRefStaffList()
    {
        return $this->LoadRefStaffList;
    }

    /**
     * Generated from protobuf field <code>repeated .AutoMsg.LoadRefStaff LoadRefStaffList = 1;</code>
     * @param \AutoMsg\LoadRefStaff[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setLoadRefStaffList($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \AutoMsg\LoadRefStaff::class);
        $this->LoadRefStaffList = $arr;

        return $this;
    }

}

