<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Src/protomsg.proto

namespace AutoMsg;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>AutoMsg.GetMapResult</code>
 */
class GetMapResult extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>map<int32, .AutoMsg.LoadLandInfo> LoadLandInfoDic = 1;</code>
     */
    private $LoadLandInfoDic;
    /**
     * Generated from protobuf field <code>repeated .AutoMsg.LoadBuildInfo LoadBuildInfo = 2;</code>
     */
    private $LoadBuildInfo;

    public function __construct() {
        \GPBMetadata\Src\Protomsg::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>map<int32, .AutoMsg.LoadLandInfo> LoadLandInfoDic = 1;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getLoadLandInfoDic()
    {
        return $this->LoadLandInfoDic;
    }

    /**
     * Generated from protobuf field <code>map<int32, .AutoMsg.LoadLandInfo> LoadLandInfoDic = 1;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setLoadLandInfoDic($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::INT32, \Google\Protobuf\Internal\GPBType::MESSAGE, \AutoMsg\LoadLandInfo::class);
        $this->LoadLandInfoDic = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .AutoMsg.LoadBuildInfo LoadBuildInfo = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getLoadBuildInfo()
    {
        return $this->LoadBuildInfo;
    }

    /**
     * Generated from protobuf field <code>repeated .AutoMsg.LoadBuildInfo LoadBuildInfo = 2;</code>
     * @param \AutoMsg\LoadBuildInfo[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setLoadBuildInfo($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \AutoMsg\LoadBuildInfo::class);
        $this->LoadBuildInfo = $arr;

        return $this;
    }

}

