<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protomsg.proto

namespace AutoMsg;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>AutoMsg.GetPrivateLandResult</code>
 */
class GetPrivateLandResult extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>map<int32, .AutoMsg.LoadLandInfo> LoadLandInfoDic = 1;</code>
     */
    private $LoadLandInfoDic;
    /**
     * Generated from protobuf field <code>.AutoMsg.PrivateBuildInfo PrivateBuildInfo = 2;</code>
     */
    private $PrivateBuildInfo = null;

    public function __construct() {
        \GPBMetadata\Protomsg::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>map<int32, .AutoMsg.LoadLandInfo> LoadLandInfoDic = 1;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getLoadLandInfoDic()
    {
        return $this->LoadLandInfoDic;
    }

    /**
     * Generated from protobuf field <code>map<int32, .AutoMsg.LoadLandInfo> LoadLandInfoDic = 1;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setLoadLandInfoDic($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::INT32, \Google\Protobuf\Internal\GPBType::MESSAGE, \AutoMsg\LoadLandInfo::class);
        $this->LoadLandInfoDic = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.AutoMsg.PrivateBuildInfo PrivateBuildInfo = 2;</code>
     * @return \AutoMsg\PrivateBuildInfo
     */
    public function getPrivateBuildInfo()
    {
        return $this->PrivateBuildInfo;
    }

    /**
     * Generated from protobuf field <code>.AutoMsg.PrivateBuildInfo PrivateBuildInfo = 2;</code>
     * @param \AutoMsg\PrivateBuildInfo $var
     * @return $this
     */
    public function setPrivateBuildInfo($var)
    {
        GPBUtil::checkMessage($var, \AutoMsg\PrivateBuildInfo::class);
        $this->PrivateBuildInfo = $var;

        return $this;
    }

}

