<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Src/protomsg.proto

namespace AutoMsg;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>AutoMsg.GetRmbParams</code>
 */
class GetRmbParams extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 Gold = 1;</code>
     */
    private $Gold = 0;
    /**
     * Generated from protobuf field <code>string Pwd = 2;</code>
     */
    private $Pwd = '';

    public function __construct() {
        \GPBMetadata\Src\Protomsg::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>int32 Gold = 1;</code>
     * @return int
     */
    public function getGold()
    {
        return $this->Gold;
    }

    /**
     * Generated from protobuf field <code>int32 Gold = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setGold($var)
    {
        GPBUtil::checkInt32($var);
        $this->Gold = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string Pwd = 2;</code>
     * @return string
     */
    public function getPwd()
    {
        return $this->Pwd;
    }

    /**
     * Generated from protobuf field <code>string Pwd = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setPwd($var)
    {
        GPBUtil::checkString($var, True);
        $this->Pwd = $var;

        return $this;
    }

}

