<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protomsg.proto

namespace AutoMsg;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>AutoMsg.GetRankingResult</code>
 */
class GetRankingResult extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 IncomeRanking = 1;</code>
     */
    private $IncomeRanking = 0;
    /**
     * Generated from protobuf field <code>int32 CompanyRanking = 2;</code>
     */
    private $CompanyRanking = 0;
    /**
     * Generated from protobuf field <code>int32 GoldCountRanking = 3;</code>
     */
    private $GoldCountRanking = 0;
    /**
     * Generated from protobuf field <code>int32 FeelingRanking = 4;</code>
     */
    private $FeelingRanking = 0;
    /**
     * Generated from protobuf field <code>int32 PKWin = 5;</code>
     */
    private $PKWin = 0;
    /**
     * Generated from protobuf field <code>int32 PKWinCount = 6;</code>
     */
    private $PKWinCount = 0;
    /**
     * Generated from protobuf field <code>int32 PKLostCount = 7;</code>
     */
    private $PKLostCount = 0;
    /**
     * Generated from protobuf field <code>int32 PKPingCount = 8;</code>
     */
    private $PKPingCount = 0;

    public function __construct() {
        \GPBMetadata\Protomsg::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>int32 IncomeRanking = 1;</code>
     * @return int
     */
    public function getIncomeRanking()
    {
        return $this->IncomeRanking;
    }

    /**
     * Generated from protobuf field <code>int32 IncomeRanking = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setIncomeRanking($var)
    {
        GPBUtil::checkInt32($var);
        $this->IncomeRanking = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 CompanyRanking = 2;</code>
     * @return int
     */
    public function getCompanyRanking()
    {
        return $this->CompanyRanking;
    }

    /**
     * Generated from protobuf field <code>int32 CompanyRanking = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setCompanyRanking($var)
    {
        GPBUtil::checkInt32($var);
        $this->CompanyRanking = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 GoldCountRanking = 3;</code>
     * @return int
     */
    public function getGoldCountRanking()
    {
        return $this->GoldCountRanking;
    }

    /**
     * Generated from protobuf field <code>int32 GoldCountRanking = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setGoldCountRanking($var)
    {
        GPBUtil::checkInt32($var);
        $this->GoldCountRanking = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 FeelingRanking = 4;</code>
     * @return int
     */
    public function getFeelingRanking()
    {
        return $this->FeelingRanking;
    }

    /**
     * Generated from protobuf field <code>int32 FeelingRanking = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setFeelingRanking($var)
    {
        GPBUtil::checkInt32($var);
        $this->FeelingRanking = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 PKWin = 5;</code>
     * @return int
     */
    public function getPKWin()
    {
        return $this->PKWin;
    }

    /**
     * Generated from protobuf field <code>int32 PKWin = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setPKWin($var)
    {
        GPBUtil::checkInt32($var);
        $this->PKWin = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 PKWinCount = 6;</code>
     * @return int
     */
    public function getPKWinCount()
    {
        return $this->PKWinCount;
    }

    /**
     * Generated from protobuf field <code>int32 PKWinCount = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setPKWinCount($var)
    {
        GPBUtil::checkInt32($var);
        $this->PKWinCount = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 PKLostCount = 7;</code>
     * @return int
     */
    public function getPKLostCount()
    {
        return $this->PKLostCount;
    }

    /**
     * Generated from protobuf field <code>int32 PKLostCount = 7;</code>
     * @param int $var
     * @return $this
     */
    public function setPKLostCount($var)
    {
        GPBUtil::checkInt32($var);
        $this->PKLostCount = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 PKPingCount = 8;</code>
     * @return int
     */
    public function getPKPingCount()
    {
        return $this->PKPingCount;
    }

    /**
     * Generated from protobuf field <code>int32 PKPingCount = 8;</code>
     * @param int $var
     * @return $this
     */
    public function setPKPingCount($var)
    {
        GPBUtil::checkInt32($var);
        $this->PKPingCount = $var;

        return $this;
    }

}

