<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Src/protomsg.proto

namespace AutoMsg;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>AutoMsg.GoldRepaymentReq</code>
 */
class GoldRepaymentReq extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 GoldCount = 1;</code>
     */
    private $GoldCount = 0;
    /**
     * Generated from protobuf field <code>int32 GoldType = 2;</code>
     */
    private $GoldType = 0;

    public function __construct() {
        \GPBMetadata\Src\Protomsg::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>int64 GoldCount = 1;</code>
     * @return int|string
     */
    public function getGoldCount()
    {
        return $this->GoldCount;
    }

    /**
     * Generated from protobuf field <code>int64 GoldCount = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setGoldCount($var)
    {
        GPBUtil::checkInt64($var);
        $this->GoldCount = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 GoldType = 2;</code>
     * @return int
     */
    public function getGoldType()
    {
        return $this->GoldType;
    }

    /**
     * Generated from protobuf field <code>int32 GoldType = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setGoldType($var)
    {
        GPBUtil::checkInt32($var);
        $this->GoldType = $var;

        return $this;
    }

}

