<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protomsg.proto

namespace AutoMsg;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>AutoMsg.HarvestPublicShopResult</code>
 */
class HarvestPublicShopResult extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .AutoMsg.LoadConsumeData LoadConsume = 1;</code>
     */
    private $LoadConsume;

    public function __construct() {
        \GPBMetadata\Protomsg::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>repeated .AutoMsg.LoadConsumeData LoadConsume = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getLoadConsume()
    {
        return $this->LoadConsume;
    }

    /**
     * Generated from protobuf field <code>repeated .AutoMsg.LoadConsumeData LoadConsume = 1;</code>
     * @param \AutoMsg\LoadConsumeData[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setLoadConsume($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \AutoMsg\LoadConsumeData::class);
        $this->LoadConsume = $arr;

        return $this;
    }

}

