<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protomsg.proto

namespace AutoMsg;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>AutoMsg.JoinGameResult</code>
 */
class JoinGameResult extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.AutoMsg.LoadRoleInfo LoadRoleInfo = 1;</code>
     */
    private $LoadRoleInfo = null;
    /**
     * Generated from protobuf field <code>repeated .AutoMsg.LoadUserAttr UserAttr = 2;</code>
     */
    private $UserAttr;
    /**
     * Generated from protobuf field <code>.AutoMsg.LoadBagInfo RoleBag = 3;</code>
     */
    private $RoleBag = null;
    /**
     * Generated from protobuf field <code>.AutoMsg.LoadCompanyInfo CompanyInfo = 4;</code>
     */
    private $CompanyInfo = null;
    /**
     * Generated from protobuf field <code>.AutoMsg.LoadDepartMentInfo DepartInfoInfo = 5;</code>
     */
    private $DepartInfoInfo = null;
    /**
     * Generated from protobuf field <code>repeated .AutoMsg.LoadFinanceLogInfo FinanceLogInfo = 6;</code>
     */
    private $FinanceLogInfo;
    /**
     * Generated from protobuf field <code>.AutoMsg.GetMapResult MapInfo = 7;</code>
     */
    private $MapInfo = null;
    /**
     * Generated from protobuf field <code>.AutoMsg.RoomListResult Room = 8;</code>
     */
    private $Room = null;
    /**
     * Generated from protobuf field <code>.AutoMsg.FriendListResult Friend = 9;</code>
     */
    private $Friend = null;
    /**
     * Generated from protobuf field <code>.AutoMsg.ChatNoReadResult Message = 10;</code>
     */
    private $Message = null;
    /**
     * Generated from protobuf field <code>.AutoMsg.LoadServerConfig ServerConfig = 11;</code>
     */
    private $ServerConfig = null;
    /**
     * Generated from protobuf field <code>.AutoMsg.MissionResult Mission = 12;</code>
     */
    private $Mission = null;
    /**
     * Generated from protobuf field <code>repeated .AutoMsg.SavingInfo LoadingGoldResult = 13;</code>
     */
    private $LoadingGoldResult;
    /**
     * Generated from protobuf field <code>repeated .AutoMsg.MailMsg Mails = 14;</code>
     */
    private $Mails;
    /**
     * Generated from protobuf field <code>.AutoMsg.AchievementResult Achievement = 15;</code>
     */
    private $Achievement = null;
    /**
     * Generated from protobuf field <code>.AutoMsg.DayCountInfo DayCountInfo = 16;</code>
     */
    private $DayCountInfo = null;
    /**
     * Generated from protobuf field <code>map<int32, .AutoMsg.LoadManager> ManagerList = 17;</code>
     */
    private $ManagerList;
    /**
     * Generated from protobuf field <code>.AutoMsg.LoadLeaderInfo LoadLeaderInfo = 18;</code>
     */
    private $LoadLeaderInfo = null;
    /**
     * Generated from protobuf field <code>.AutoMsg.GetRankingResult RankingValue = 19;</code>
     */
    private $RankingValue = null;
    /**
     * Generated from protobuf field <code>.AutoMsg.SkillResult SkillResult = 20;</code>
     */
    private $SkillResult = null;
    /**
     * Generated from protobuf field <code>.AutoMsg.DataCountResult DataCountResult = 21;</code>
     */
    private $DataCountResult = null;
    /**
     * Generated from protobuf field <code>repeated .AutoMsg.FriendAwardInfoResult FriendAwardInfo = 22;</code>
     */
    private $FriendAwardInfo;
    /**
     * Generated from protobuf field <code>.AutoMsg.GetPrivateLandResult PrivateMapInfo = 23;</code>
     */
    private $PrivateMapInfo = null;
    /**
     * Generated from protobuf field <code>.AutoMsg.TalentInfo TalentInfo = 25;</code>
     */
    private $TalentInfo = null;
    /**
     * Generated from protobuf field <code>repeated .AutoMsg.TalentInfo TalentDatas = 26;</code>
     */
    private $TalentDatas;
    /**
     * Generated from protobuf field <code>.AutoMsg.TypeCountStaffResult TypeCountStaff = 27;</code>
     */
    private $TypeCountStaff = null;
    /**
     * Generated from protobuf field <code>.AutoMsg.LoadLoansResult LoadLoans = 28;</code>
     */
    private $LoadLoans = null;
    /**
     * Generated from protobuf field <code>int32 TalkingPkCount = 29;</code>
     */
    private $TalkingPkCount = 0;
    /**
     * Generated from protobuf field <code>.AutoMsg.OnLineAwardsResult OnLineAwards = 30;</code>
     */
    private $OnLineAwards = null;
    /**
     * Generated from protobuf field <code>.AutoMsg.GiftTakeLogsResult GiftTakeLogs = 31;</code>
     */
    private $GiftTakeLogs = null;
    /**
     * Generated from protobuf field <code>.AutoMsg.LoadTradeDataResult LoadTradeInfo = 32;</code>
     */
    private $LoadTradeInfo = null;

    public function __construct() {
        \GPBMetadata\Protomsg::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>.AutoMsg.LoadRoleInfo LoadRoleInfo = 1;</code>
     * @return \AutoMsg\LoadRoleInfo
     */
    public function getLoadRoleInfo()
    {
        return $this->LoadRoleInfo;
    }

    /**
     * Generated from protobuf field <code>.AutoMsg.LoadRoleInfo LoadRoleInfo = 1;</code>
     * @param \AutoMsg\LoadRoleInfo $var
     * @return $this
     */
    public function setLoadRoleInfo($var)
    {
        GPBUtil::checkMessage($var, \AutoMsg\LoadRoleInfo::class);
        $this->LoadRoleInfo = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .AutoMsg.LoadUserAttr UserAttr = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getUserAttr()
    {
        return $this->UserAttr;
    }

    /**
     * Generated from protobuf field <code>repeated .AutoMsg.LoadUserAttr UserAttr = 2;</code>
     * @param \AutoMsg\LoadUserAttr[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setUserAttr($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \AutoMsg\LoadUserAttr::class);
        $this->UserAttr = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.AutoMsg.LoadBagInfo RoleBag = 3;</code>
     * @return \AutoMsg\LoadBagInfo
     */
    public function getRoleBag()
    {
        return $this->RoleBag;
    }

    /**
     * Generated from protobuf field <code>.AutoMsg.LoadBagInfo RoleBag = 3;</code>
     * @param \AutoMsg\LoadBagInfo $var
     * @return $this
     */
    public function setRoleBag($var)
    {
        GPBUtil::checkMessage($var, \AutoMsg\LoadBagInfo::class);
        $this->RoleBag = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.AutoMsg.LoadCompanyInfo CompanyInfo = 4;</code>
     * @return \AutoMsg\LoadCompanyInfo
     */
    public function getCompanyInfo()
    {
        return $this->CompanyInfo;
    }

    /**
     * Generated from protobuf field <code>.AutoMsg.LoadCompanyInfo CompanyInfo = 4;</code>
     * @param \AutoMsg\LoadCompanyInfo $var
     * @return $this
     */
    public function setCompanyInfo($var)
    {
        GPBUtil::checkMessage($var, \AutoMsg\LoadCompanyInfo::class);
        $this->CompanyInfo = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.AutoMsg.LoadDepartMentInfo DepartInfoInfo = 5;</code>
     * @return \AutoMsg\LoadDepartMentInfo
     */
    public function getDepartInfoInfo()
    {
        return $this->DepartInfoInfo;
    }

    /**
     * Generated from protobuf field <code>.AutoMsg.LoadDepartMentInfo DepartInfoInfo = 5;</code>
     * @param \AutoMsg\LoadDepartMentInfo $var
     * @return $this
     */
    public function setDepartInfoInfo($var)
    {
        GPBUtil::checkMessage($var, \AutoMsg\LoadDepartMentInfo::class);
        $this->DepartInfoInfo = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .AutoMsg.LoadFinanceLogInfo FinanceLogInfo = 6;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getFinanceLogInfo()
    {
        return $this->FinanceLogInfo;
    }

    /**
     * Generated from protobuf field <code>repeated .AutoMsg.LoadFinanceLogInfo FinanceLogInfo = 6;</code>
     * @param \AutoMsg\LoadFinanceLogInfo[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setFinanceLogInfo($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \AutoMsg\LoadFinanceLogInfo::class);
        $this->FinanceLogInfo = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.AutoMsg.GetMapResult MapInfo = 7;</code>
     * @return \AutoMsg\GetMapResult
     */
    public function getMapInfo()
    {
        return $this->MapInfo;
    }

    /**
     * Generated from protobuf field <code>.AutoMsg.GetMapResult MapInfo = 7;</code>
     * @param \AutoMsg\GetMapResult $var
     * @return $this
     */
    public function setMapInfo($var)
    {
        GPBUtil::checkMessage($var, \AutoMsg\GetMapResult::class);
        $this->MapInfo = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.AutoMsg.RoomListResult Room = 8;</code>
     * @return \AutoMsg\RoomListResult
     */
    public function getRoom()
    {
        return $this->Room;
    }

    /**
     * Generated from protobuf field <code>.AutoMsg.RoomListResult Room = 8;</code>
     * @param \AutoMsg\RoomListResult $var
     * @return $this
     */
    public function setRoom($var)
    {
        GPBUtil::checkMessage($var, \AutoMsg\RoomListResult::class);
        $this->Room = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.AutoMsg.FriendListResult Friend = 9;</code>
     * @return \AutoMsg\FriendListResult
     */
    public function getFriend()
    {
        return $this->Friend;
    }

    /**
     * Generated from protobuf field <code>.AutoMsg.FriendListResult Friend = 9;</code>
     * @param \AutoMsg\FriendListResult $var
     * @return $this
     */
    public function setFriend($var)
    {
        GPBUtil::checkMessage($var, \AutoMsg\FriendListResult::class);
        $this->Friend = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.AutoMsg.ChatNoReadResult Message = 10;</code>
     * @return \AutoMsg\ChatNoReadResult
     */
    public function getMessage()
    {
        return $this->Message;
    }

    /**
     * Generated from protobuf field <code>.AutoMsg.ChatNoReadResult Message = 10;</code>
     * @param \AutoMsg\ChatNoReadResult $var
     * @return $this
     */
    public function setMessage($var)
    {
        GPBUtil::checkMessage($var, \AutoMsg\ChatNoReadResult::class);
        $this->Message = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.AutoMsg.LoadServerConfig ServerConfig = 11;</code>
     * @return \AutoMsg\LoadServerConfig
     */
    public function getServerConfig()
    {
        return $this->ServerConfig;
    }

    /**
     * Generated from protobuf field <code>.AutoMsg.LoadServerConfig ServerConfig = 11;</code>
     * @param \AutoMsg\LoadServerConfig $var
     * @return $this
     */
    public function setServerConfig($var)
    {
        GPBUtil::checkMessage($var, \AutoMsg\LoadServerConfig::class);
        $this->ServerConfig = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.AutoMsg.MissionResult Mission = 12;</code>
     * @return \AutoMsg\MissionResult
     */
    public function getMission()
    {
        return $this->Mission;
    }

    /**
     * Generated from protobuf field <code>.AutoMsg.MissionResult Mission = 12;</code>
     * @param \AutoMsg\MissionResult $var
     * @return $this
     */
    public function setMission($var)
    {
        GPBUtil::checkMessage($var, \AutoMsg\MissionResult::class);
        $this->Mission = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .AutoMsg.SavingInfo LoadingGoldResult = 13;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getLoadingGoldResult()
    {
        return $this->LoadingGoldResult;
    }

    /**
     * Generated from protobuf field <code>repeated .AutoMsg.SavingInfo LoadingGoldResult = 13;</code>
     * @param \AutoMsg\SavingInfo[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setLoadingGoldResult($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \AutoMsg\SavingInfo::class);
        $this->LoadingGoldResult = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .AutoMsg.MailMsg Mails = 14;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getMails()
    {
        return $this->Mails;
    }

    /**
     * Generated from protobuf field <code>repeated .AutoMsg.MailMsg Mails = 14;</code>
     * @param \AutoMsg\MailMsg[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setMails($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \AutoMsg\MailMsg::class);
        $this->Mails = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.AutoMsg.AchievementResult Achievement = 15;</code>
     * @return \AutoMsg\AchievementResult
     */
    public function getAchievement()
    {
        return $this->Achievement;
    }

    /**
     * Generated from protobuf field <code>.AutoMsg.AchievementResult Achievement = 15;</code>
     * @param \AutoMsg\AchievementResult $var
     * @return $this
     */
    public function setAchievement($var)
    {
        GPBUtil::checkMessage($var, \AutoMsg\AchievementResult::class);
        $this->Achievement = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.AutoMsg.DayCountInfo DayCountInfo = 16;</code>
     * @return \AutoMsg\DayCountInfo
     */
    public function getDayCountInfo()
    {
        return $this->DayCountInfo;
    }

    /**
     * Generated from protobuf field <code>.AutoMsg.DayCountInfo DayCountInfo = 16;</code>
     * @param \AutoMsg\DayCountInfo $var
     * @return $this
     */
    public function setDayCountInfo($var)
    {
        GPBUtil::checkMessage($var, \AutoMsg\DayCountInfo::class);
        $this->DayCountInfo = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>map<int32, .AutoMsg.LoadManager> ManagerList = 17;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getManagerList()
    {
        return $this->ManagerList;
    }

    /**
     * Generated from protobuf field <code>map<int32, .AutoMsg.LoadManager> ManagerList = 17;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setManagerList($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::INT32, \Google\Protobuf\Internal\GPBType::MESSAGE, \AutoMsg\LoadManager::class);
        $this->ManagerList = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.AutoMsg.LoadLeaderInfo LoadLeaderInfo = 18;</code>
     * @return \AutoMsg\LoadLeaderInfo
     */
    public function getLoadLeaderInfo()
    {
        return $this->LoadLeaderInfo;
    }

    /**
     * Generated from protobuf field <code>.AutoMsg.LoadLeaderInfo LoadLeaderInfo = 18;</code>
     * @param \AutoMsg\LoadLeaderInfo $var
     * @return $this
     */
    public function setLoadLeaderInfo($var)
    {
        GPBUtil::checkMessage($var, \AutoMsg\LoadLeaderInfo::class);
        $this->LoadLeaderInfo = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.AutoMsg.GetRankingResult RankingValue = 19;</code>
     * @return \AutoMsg\GetRankingResult
     */
    public function getRankingValue()
    {
        return $this->RankingValue;
    }

    /**
     * Generated from protobuf field <code>.AutoMsg.GetRankingResult RankingValue = 19;</code>
     * @param \AutoMsg\GetRankingResult $var
     * @return $this
     */
    public function setRankingValue($var)
    {
        GPBUtil::checkMessage($var, \AutoMsg\GetRankingResult::class);
        $this->RankingValue = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.AutoMsg.SkillResult SkillResult = 20;</code>
     * @return \AutoMsg\SkillResult
     */
    public function getSkillResult()
    {
        return $this->SkillResult;
    }

    /**
     * Generated from protobuf field <code>.AutoMsg.SkillResult SkillResult = 20;</code>
     * @param \AutoMsg\SkillResult $var
     * @return $this
     */
    public function setSkillResult($var)
    {
        GPBUtil::checkMessage($var, \AutoMsg\SkillResult::class);
        $this->SkillResult = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.AutoMsg.DataCountResult DataCountResult = 21;</code>
     * @return \AutoMsg\DataCountResult
     */
    public function getDataCountResult()
    {
        return $this->DataCountResult;
    }

    /**
     * Generated from protobuf field <code>.AutoMsg.DataCountResult DataCountResult = 21;</code>
     * @param \AutoMsg\DataCountResult $var
     * @return $this
     */
    public function setDataCountResult($var)
    {
        GPBUtil::checkMessage($var, \AutoMsg\DataCountResult::class);
        $this->DataCountResult = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .AutoMsg.FriendAwardInfoResult FriendAwardInfo = 22;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getFriendAwardInfo()
    {
        return $this->FriendAwardInfo;
    }

    /**
     * Generated from protobuf field <code>repeated .AutoMsg.FriendAwardInfoResult FriendAwardInfo = 22;</code>
     * @param \AutoMsg\FriendAwardInfoResult[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setFriendAwardInfo($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \AutoMsg\FriendAwardInfoResult::class);
        $this->FriendAwardInfo = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.AutoMsg.GetPrivateLandResult PrivateMapInfo = 23;</code>
     * @return \AutoMsg\GetPrivateLandResult
     */
    public function getPrivateMapInfo()
    {
        return $this->PrivateMapInfo;
    }

    /**
     * Generated from protobuf field <code>.AutoMsg.GetPrivateLandResult PrivateMapInfo = 23;</code>
     * @param \AutoMsg\GetPrivateLandResult $var
     * @return $this
     */
    public function setPrivateMapInfo($var)
    {
        GPBUtil::checkMessage($var, \AutoMsg\GetPrivateLandResult::class);
        $this->PrivateMapInfo = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.AutoMsg.TalentInfo TalentInfo = 25;</code>
     * @return \AutoMsg\TalentInfo
     */
    public function getTalentInfo()
    {
        return $this->TalentInfo;
    }

    /**
     * Generated from protobuf field <code>.AutoMsg.TalentInfo TalentInfo = 25;</code>
     * @param \AutoMsg\TalentInfo $var
     * @return $this
     */
    public function setTalentInfo($var)
    {
        GPBUtil::checkMessage($var, \AutoMsg\TalentInfo::class);
        $this->TalentInfo = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .AutoMsg.TalentInfo TalentDatas = 26;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getTalentDatas()
    {
        return $this->TalentDatas;
    }

    /**
     * Generated from protobuf field <code>repeated .AutoMsg.TalentInfo TalentDatas = 26;</code>
     * @param \AutoMsg\TalentInfo[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setTalentDatas($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \AutoMsg\TalentInfo::class);
        $this->TalentDatas = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.AutoMsg.TypeCountStaffResult TypeCountStaff = 27;</code>
     * @return \AutoMsg\TypeCountStaffResult
     */
    public function getTypeCountStaff()
    {
        return $this->TypeCountStaff;
    }

    /**
     * Generated from protobuf field <code>.AutoMsg.TypeCountStaffResult TypeCountStaff = 27;</code>
     * @param \AutoMsg\TypeCountStaffResult $var
     * @return $this
     */
    public function setTypeCountStaff($var)
    {
        GPBUtil::checkMessage($var, \AutoMsg\TypeCountStaffResult::class);
        $this->TypeCountStaff = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.AutoMsg.LoadLoansResult LoadLoans = 28;</code>
     * @return \AutoMsg\LoadLoansResult
     */
    public function getLoadLoans()
    {
        return $this->LoadLoans;
    }

    /**
     * Generated from protobuf field <code>.AutoMsg.LoadLoansResult LoadLoans = 28;</code>
     * @param \AutoMsg\LoadLoansResult $var
     * @return $this
     */
    public function setLoadLoans($var)
    {
        GPBUtil::checkMessage($var, \AutoMsg\LoadLoansResult::class);
        $this->LoadLoans = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 TalkingPkCount = 29;</code>
     * @return int
     */
    public function getTalkingPkCount()
    {
        return $this->TalkingPkCount;
    }

    /**
     * Generated from protobuf field <code>int32 TalkingPkCount = 29;</code>
     * @param int $var
     * @return $this
     */
    public function setTalkingPkCount($var)
    {
        GPBUtil::checkInt32($var);
        $this->TalkingPkCount = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.AutoMsg.OnLineAwardsResult OnLineAwards = 30;</code>
     * @return \AutoMsg\OnLineAwardsResult
     */
    public function getOnLineAwards()
    {
        return $this->OnLineAwards;
    }

    /**
     * Generated from protobuf field <code>.AutoMsg.OnLineAwardsResult OnLineAwards = 30;</code>
     * @param \AutoMsg\OnLineAwardsResult $var
     * @return $this
     */
    public function setOnLineAwards($var)
    {
        GPBUtil::checkMessage($var, \AutoMsg\OnLineAwardsResult::class);
        $this->OnLineAwards = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.AutoMsg.GiftTakeLogsResult GiftTakeLogs = 31;</code>
     * @return \AutoMsg\GiftTakeLogsResult
     */
    public function getGiftTakeLogs()
    {
        return $this->GiftTakeLogs;
    }

    /**
     * Generated from protobuf field <code>.AutoMsg.GiftTakeLogsResult GiftTakeLogs = 31;</code>
     * @param \AutoMsg\GiftTakeLogsResult $var
     * @return $this
     */
    public function setGiftTakeLogs($var)
    {
        GPBUtil::checkMessage($var, \AutoMsg\GiftTakeLogsResult::class);
        $this->GiftTakeLogs = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.AutoMsg.LoadTradeDataResult LoadTradeInfo = 32;</code>
     * @return \AutoMsg\LoadTradeDataResult
     */
    public function getLoadTradeInfo()
    {
        return $this->LoadTradeInfo;
    }

    /**
     * Generated from protobuf field <code>.AutoMsg.LoadTradeDataResult LoadTradeInfo = 32;</code>
     * @param \AutoMsg\LoadTradeDataResult $var
     * @return $this
     */
    public function setLoadTradeInfo($var)
    {
        GPBUtil::checkMessage($var, \AutoMsg\LoadTradeDataResult::class);
        $this->LoadTradeInfo = $var;

        return $this;
    }

}

