<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protomsg.proto

namespace AutoMsg;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>AutoMsg.LoadCompanyInfo</code>
 */
class LoadCompanyInfo extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string Name = 1;</code>
     */
    private $Name = '';
    /**
     * Generated from protobuf field <code>string Desc = 2;</code>
     */
    private $Desc = '';
    /**
     * Generated from protobuf field <code>string Icon = 3;</code>
     */
    private $Icon = '';
    /**
     * Generated from protobuf field <code>int64 CreateTime = 4;</code>
     */
    private $CreateTime = 0;
    /**
     * Generated from protobuf field <code>int64 ClientValue = 5;</code>
     */
    private $ClientValue = 0;
    /**
     * Generated from protobuf field <code>int32 StaffNumber = 6;</code>
     */
    private $StaffNumber = 0;
    /**
     * Generated from protobuf field <code>int32 ShopNumber = 7;</code>
     */
    private $ShopNumber = 0;
    /**
     * Generated from protobuf field <code>int64 CompanyValue = 8;</code>
     */
    private $CompanyValue = 0;

    public function __construct() {
        \GPBMetadata\Protomsg::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>string Name = 1;</code>
     * @return string
     */
    public function getName()
    {
        return $this->Name;
    }

    /**
     * Generated from protobuf field <code>string Name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->Name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string Desc = 2;</code>
     * @return string
     */
    public function getDesc()
    {
        return $this->Desc;
    }

    /**
     * Generated from protobuf field <code>string Desc = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setDesc($var)
    {
        GPBUtil::checkString($var, True);
        $this->Desc = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string Icon = 3;</code>
     * @return string
     */
    public function getIcon()
    {
        return $this->Icon;
    }

    /**
     * Generated from protobuf field <code>string Icon = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setIcon($var)
    {
        GPBUtil::checkString($var, True);
        $this->Icon = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 CreateTime = 4;</code>
     * @return int|string
     */
    public function getCreateTime()
    {
        return $this->CreateTime;
    }

    /**
     * Generated from protobuf field <code>int64 CreateTime = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCreateTime($var)
    {
        GPBUtil::checkInt64($var);
        $this->CreateTime = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 ClientValue = 5;</code>
     * @return int|string
     */
    public function getClientValue()
    {
        return $this->ClientValue;
    }

    /**
     * Generated from protobuf field <code>int64 ClientValue = 5;</code>
     * @param int|string $var
     * @return $this
     */
    public function setClientValue($var)
    {
        GPBUtil::checkInt64($var);
        $this->ClientValue = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 StaffNumber = 6;</code>
     * @return int
     */
    public function getStaffNumber()
    {
        return $this->StaffNumber;
    }

    /**
     * Generated from protobuf field <code>int32 StaffNumber = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setStaffNumber($var)
    {
        GPBUtil::checkInt32($var);
        $this->StaffNumber = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 ShopNumber = 7;</code>
     * @return int
     */
    public function getShopNumber()
    {
        return $this->ShopNumber;
    }

    /**
     * Generated from protobuf field <code>int32 ShopNumber = 7;</code>
     * @param int $var
     * @return $this
     */
    public function setShopNumber($var)
    {
        GPBUtil::checkInt32($var);
        $this->ShopNumber = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 CompanyValue = 8;</code>
     * @return int|string
     */
    public function getCompanyValue()
    {
        return $this->CompanyValue;
    }

    /**
     * Generated from protobuf field <code>int64 CompanyValue = 8;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCompanyValue($var)
    {
        GPBUtil::checkInt64($var);
        $this->CompanyValue = $var;

        return $this;
    }

}

