<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Src/protomsg.proto

namespace AutoMsg;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * 增加是否解锁字段
 *
 * Generated from protobuf message <code>AutoMsg.LoadNpcFavorability</code>
 */
class LoadNpcFavorability extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 NpcId = 1;</code>
     */
    private $NpcId = 0;
    /**
     * Generated from protobuf field <code>int32 CurrentFavorability = 2;</code>
     */
    private $CurrentFavorability = 0;
    /**
     * Generated from protobuf field <code>int32 FavorabilityLevel = 3;</code>
     */
    private $FavorabilityLevel = 0;
    /**
     *是否解锁
     *
     * Generated from protobuf field <code>bool Status = 4;</code>
     */
    private $Status = false;
    /**
     *是否任职
     *
     * Generated from protobuf field <code>bool Appointed = 5;</code>
     */
    private $Appointed = false;

    public function __construct() {
        \GPBMetadata\Src\Protomsg::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>int32 NpcId = 1;</code>
     * @return int
     */
    public function getNpcId()
    {
        return $this->NpcId;
    }

    /**
     * Generated from protobuf field <code>int32 NpcId = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setNpcId($var)
    {
        GPBUtil::checkInt32($var);
        $this->NpcId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 CurrentFavorability = 2;</code>
     * @return int
     */
    public function getCurrentFavorability()
    {
        return $this->CurrentFavorability;
    }

    /**
     * Generated from protobuf field <code>int32 CurrentFavorability = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setCurrentFavorability($var)
    {
        GPBUtil::checkInt32($var);
        $this->CurrentFavorability = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 FavorabilityLevel = 3;</code>
     * @return int
     */
    public function getFavorabilityLevel()
    {
        return $this->FavorabilityLevel;
    }

    /**
     * Generated from protobuf field <code>int32 FavorabilityLevel = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setFavorabilityLevel($var)
    {
        GPBUtil::checkInt32($var);
        $this->FavorabilityLevel = $var;

        return $this;
    }

    /**
     *是否解锁
     *
     * Generated from protobuf field <code>bool Status = 4;</code>
     * @return bool
     */
    public function getStatus()
    {
        return $this->Status;
    }

    /**
     *是否解锁
     *
     * Generated from protobuf field <code>bool Status = 4;</code>
     * @param bool $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkBool($var);
        $this->Status = $var;

        return $this;
    }

    /**
     *是否任职
     *
     * Generated from protobuf field <code>bool Appointed = 5;</code>
     * @return bool
     */
    public function getAppointed()
    {
        return $this->Appointed;
    }

    /**
     *是否任职
     *
     * Generated from protobuf field <code>bool Appointed = 5;</code>
     * @param bool $var
     * @return $this
     */
    public function setAppointed($var)
    {
        GPBUtil::checkBool($var);
        $this->Appointed = $var;

        return $this;
    }

}

