<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protomsg.proto

namespace AutoMsg;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>AutoMsg.LoadBagInfo</code>
 */
class LoadBagInfo extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 MaxCellNumber = 1;</code>
     */
    private $MaxCellNumber = 0;
    /**
     * Generated from protobuf field <code>int64 CurUsedCell = 2;</code>
     */
    private $CurUsedCell = 0;
    /**
     * Generated from protobuf field <code>map<int32, .AutoMsg.LoadRoleBagInfo> Items = 3;</code>
     */
    private $Items;
    /**
     * Generated from protobuf field <code>map<int32, .AutoMsg.LoadRoleBagInfo> Furnitrues = 4;</code>
     */
    private $Furnitrues;

    public function __construct() {
        \GPBMetadata\Protomsg::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>int64 MaxCellNumber = 1;</code>
     * @return int|string
     */
    public function getMaxCellNumber()
    {
        return $this->MaxCellNumber;
    }

    /**
     * Generated from protobuf field <code>int64 MaxCellNumber = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setMaxCellNumber($var)
    {
        GPBUtil::checkInt64($var);
        $this->MaxCellNumber = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 CurUsedCell = 2;</code>
     * @return int|string
     */
    public function getCurUsedCell()
    {
        return $this->CurUsedCell;
    }

    /**
     * Generated from protobuf field <code>int64 CurUsedCell = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCurUsedCell($var)
    {
        GPBUtil::checkInt64($var);
        $this->CurUsedCell = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>map<int32, .AutoMsg.LoadRoleBagInfo> Items = 3;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getItems()
    {
        return $this->Items;
    }

    /**
     * Generated from protobuf field <code>map<int32, .AutoMsg.LoadRoleBagInfo> Items = 3;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setItems($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::INT32, \Google\Protobuf\Internal\GPBType::MESSAGE, \AutoMsg\LoadRoleBagInfo::class);
        $this->Items = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>map<int32, .AutoMsg.LoadRoleBagInfo> Furnitrues = 4;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getFurnitrues()
    {
        return $this->Furnitrues;
    }

    /**
     * Generated from protobuf field <code>map<int32, .AutoMsg.LoadRoleBagInfo> Furnitrues = 4;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setFurnitrues($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::INT32, \Google\Protobuf\Internal\GPBType::MESSAGE, \AutoMsg\LoadRoleBagInfo::class);
        $this->Furnitrues = $arr;

        return $this;
    }

}

