<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protomsg.proto

namespace AutoMsg;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>AutoMsg.LoadRoleInfo</code>
 */
class LoadRoleInfo extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string RoleId = 1;</code>
     */
    private $RoleId = '';
    /**
     * Generated from protobuf field <code>int64 Exp = 2;</code>
     */
    private $Exp = 0;
    /**
     * Generated from protobuf field <code>string Icon = 3;</code>
     */
    private $Icon = '';
    /**
     * Generated from protobuf field <code>string Name = 4;</code>
     */
    private $Name = '';
    /**
     * Generated from protobuf field <code>int32 Level = 5;</code>
     */
    private $Level = 0;
    /**
     * Generated from protobuf field <code>repeated int32 Avatar = 6;</code>
     */
    private $Avatar;
    /**
     * Generated from protobuf field <code>int32 Type = 7;</code>
     */
    private $Type = 0;
    /**
     * Generated from protobuf field <code>int32 Sex = 8;</code>
     */
    private $Sex = 0;
    /**
     * Generated from protobuf field <code>string Desc = 9;</code>
     */
    private $Desc = '';
    /**
     * Generated from protobuf field <code>string VipLevel = 10;</code>
     */
    private $VipLevel = '';
    /**
     * Generated from protobuf field <code>int64 Gold = 11;</code>
     */
    private $Gold = 0;
    /**
     * Generated from protobuf field <code>int32 Intelligence = 12;</code>
     */
    private $Intelligence = 0;
    /**
     * Generated from protobuf field <code>int32 Charm = 13;</code>
     */
    private $Charm = 0;
    /**
     * Generated from protobuf field <code>int32 Affinity = 14;</code>
     */
    private $Affinity = 0;
    /**
     * Generated from protobuf field <code>int32 Concentration = 15;</code>
     */
    private $Concentration = 0;
    /**
     * Generated from protobuf field <code>int32 Constitution = 16;</code>
     */
    private $Constitution = 0;
    /**
     * Generated from protobuf field <code>int64 SocialStatus = 17;</code>
     */
    private $SocialStatus = 0;
    /**
     * Generated from protobuf field <code>repeated int32 Certificates = 18;</code>
     */
    private $Certificates;
    /**
     * Generated from protobuf field <code>repeated int32 CertificatesExp = 19;</code>
     */
    private $CertificatesExp;
    /**
     * Generated from protobuf field <code>int32 LastLoginTime = 20;</code>
     */
    private $LastLoginTime = 0;
    /**
     * Generated from protobuf field <code>int32 Power = 21;</code>
     */
    private $Power = 0;
    /**
     * Generated from protobuf field <code>int32 ActivedAchievement = 22;</code>
     */
    private $ActivedAchievement = 0;
    /**
     * Generated from protobuf field <code>int32 PraiseTime = 23;</code>
     */
    private $PraiseTime = 0;
    /**
     * Generated from protobuf field <code>repeated string RecordPraiseRole = 24;</code>
     */
    private $RecordPraiseRole;
    /**
     * Generated from protobuf field <code>int32 RoomPraiseTime = 25;</code>
     */
    private $RoomPraiseTime = 0;
    /**
     * Generated from protobuf field <code>repeated string AuctionShopId = 26;</code>
     */
    private $AuctionShopId;
    /**
     * Generated from protobuf field <code>int64 RedPacketMaxMoney = 27;</code>
     */
    private $RedPacketMaxMoney = 0;
    /**
     * Generated from protobuf field <code>int32 PkWinCount = 28;</code>
     */
    private $PkWinCount = 0;
    /**
     * Generated from protobuf field <code>int32 PkLostCount = 29;</code>
     */
    private $PkLostCount = 0;
    /**
     * Generated from protobuf field <code>int32 PkPingCount = 30;</code>
     */
    private $PkPingCount = 0;
    /**
     * Generated from protobuf field <code>int32 WhetherTheLoan = 31;</code>
     */
    private $WhetherTheLoan = 0;
    /**
     * Generated from protobuf field <code>map<int32, .AutoMsg.LoadRecordType> LoadRecordType = 32;</code>
     */
    private $LoadRecordType;

    public function __construct() {
        \GPBMetadata\Protomsg::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>string RoleId = 1;</code>
     * @return string
     */
    public function getRoleId()
    {
        return $this->RoleId;
    }

    /**
     * Generated from protobuf field <code>string RoleId = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setRoleId($var)
    {
        GPBUtil::checkString($var, True);
        $this->RoleId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 Exp = 2;</code>
     * @return int|string
     */
    public function getExp()
    {
        return $this->Exp;
    }

    /**
     * Generated from protobuf field <code>int64 Exp = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setExp($var)
    {
        GPBUtil::checkInt64($var);
        $this->Exp = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string Icon = 3;</code>
     * @return string
     */
    public function getIcon()
    {
        return $this->Icon;
    }

    /**
     * Generated from protobuf field <code>string Icon = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setIcon($var)
    {
        GPBUtil::checkString($var, True);
        $this->Icon = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string Name = 4;</code>
     * @return string
     */
    public function getName()
    {
        return $this->Name;
    }

    /**
     * Generated from protobuf field <code>string Name = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->Name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 Level = 5;</code>
     * @return int
     */
    public function getLevel()
    {
        return $this->Level;
    }

    /**
     * Generated from protobuf field <code>int32 Level = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setLevel($var)
    {
        GPBUtil::checkInt32($var);
        $this->Level = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated int32 Avatar = 6;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getAvatar()
    {
        return $this->Avatar;
    }

    /**
     * Generated from protobuf field <code>repeated int32 Avatar = 6;</code>
     * @param int[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setAvatar($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::INT32);
        $this->Avatar = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 Type = 7;</code>
     * @return int
     */
    public function getType()
    {
        return $this->Type;
    }

    /**
     * Generated from protobuf field <code>int32 Type = 7;</code>
     * @param int $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkInt32($var);
        $this->Type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 Sex = 8;</code>
     * @return int
     */
    public function getSex()
    {
        return $this->Sex;
    }

    /**
     * Generated from protobuf field <code>int32 Sex = 8;</code>
     * @param int $var
     * @return $this
     */
    public function setSex($var)
    {
        GPBUtil::checkInt32($var);
        $this->Sex = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string Desc = 9;</code>
     * @return string
     */
    public function getDesc()
    {
        return $this->Desc;
    }

    /**
     * Generated from protobuf field <code>string Desc = 9;</code>
     * @param string $var
     * @return $this
     */
    public function setDesc($var)
    {
        GPBUtil::checkString($var, True);
        $this->Desc = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string VipLevel = 10;</code>
     * @return string
     */
    public function getVipLevel()
    {
        return $this->VipLevel;
    }

    /**
     * Generated from protobuf field <code>string VipLevel = 10;</code>
     * @param string $var
     * @return $this
     */
    public function setVipLevel($var)
    {
        GPBUtil::checkString($var, True);
        $this->VipLevel = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 Gold = 11;</code>
     * @return int|string
     */
    public function getGold()
    {
        return $this->Gold;
    }

    /**
     * Generated from protobuf field <code>int64 Gold = 11;</code>
     * @param int|string $var
     * @return $this
     */
    public function setGold($var)
    {
        GPBUtil::checkInt64($var);
        $this->Gold = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 Intelligence = 12;</code>
     * @return int
     */
    public function getIntelligence()
    {
        return $this->Intelligence;
    }

    /**
     * Generated from protobuf field <code>int32 Intelligence = 12;</code>
     * @param int $var
     * @return $this
     */
    public function setIntelligence($var)
    {
        GPBUtil::checkInt32($var);
        $this->Intelligence = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 Charm = 13;</code>
     * @return int
     */
    public function getCharm()
    {
        return $this->Charm;
    }

    /**
     * Generated from protobuf field <code>int32 Charm = 13;</code>
     * @param int $var
     * @return $this
     */
    public function setCharm($var)
    {
        GPBUtil::checkInt32($var);
        $this->Charm = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 Affinity = 14;</code>
     * @return int
     */
    public function getAffinity()
    {
        return $this->Affinity;
    }

    /**
     * Generated from protobuf field <code>int32 Affinity = 14;</code>
     * @param int $var
     * @return $this
     */
    public function setAffinity($var)
    {
        GPBUtil::checkInt32($var);
        $this->Affinity = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 Concentration = 15;</code>
     * @return int
     */
    public function getConcentration()
    {
        return $this->Concentration;
    }

    /**
     * Generated from protobuf field <code>int32 Concentration = 15;</code>
     * @param int $var
     * @return $this
     */
    public function setConcentration($var)
    {
        GPBUtil::checkInt32($var);
        $this->Concentration = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 Constitution = 16;</code>
     * @return int
     */
    public function getConstitution()
    {
        return $this->Constitution;
    }

    /**
     * Generated from protobuf field <code>int32 Constitution = 16;</code>
     * @param int $var
     * @return $this
     */
    public function setConstitution($var)
    {
        GPBUtil::checkInt32($var);
        $this->Constitution = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 SocialStatus = 17;</code>
     * @return int|string
     */
    public function getSocialStatus()
    {
        return $this->SocialStatus;
    }

    /**
     * Generated from protobuf field <code>int64 SocialStatus = 17;</code>
     * @param int|string $var
     * @return $this
     */
    public function setSocialStatus($var)
    {
        GPBUtil::checkInt64($var);
        $this->SocialStatus = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated int32 Certificates = 18;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getCertificates()
    {
        return $this->Certificates;
    }

    /**
     * Generated from protobuf field <code>repeated int32 Certificates = 18;</code>
     * @param int[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setCertificates($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::INT32);
        $this->Certificates = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated int32 CertificatesExp = 19;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getCertificatesExp()
    {
        return $this->CertificatesExp;
    }

    /**
     * Generated from protobuf field <code>repeated int32 CertificatesExp = 19;</code>
     * @param int[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setCertificatesExp($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::INT32);
        $this->CertificatesExp = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 LastLoginTime = 20;</code>
     * @return int
     */
    public function getLastLoginTime()
    {
        return $this->LastLoginTime;
    }

    /**
     * Generated from protobuf field <code>int32 LastLoginTime = 20;</code>
     * @param int $var
     * @return $this
     */
    public function setLastLoginTime($var)
    {
        GPBUtil::checkInt32($var);
        $this->LastLoginTime = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 Power = 21;</code>
     * @return int
     */
    public function getPower()
    {
        return $this->Power;
    }

    /**
     * Generated from protobuf field <code>int32 Power = 21;</code>
     * @param int $var
     * @return $this
     */
    public function setPower($var)
    {
        GPBUtil::checkInt32($var);
        $this->Power = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 ActivedAchievement = 22;</code>
     * @return int
     */
    public function getActivedAchievement()
    {
        return $this->ActivedAchievement;
    }

    /**
     * Generated from protobuf field <code>int32 ActivedAchievement = 22;</code>
     * @param int $var
     * @return $this
     */
    public function setActivedAchievement($var)
    {
        GPBUtil::checkInt32($var);
        $this->ActivedAchievement = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 PraiseTime = 23;</code>
     * @return int
     */
    public function getPraiseTime()
    {
        return $this->PraiseTime;
    }

    /**
     * Generated from protobuf field <code>int32 PraiseTime = 23;</code>
     * @param int $var
     * @return $this
     */
    public function setPraiseTime($var)
    {
        GPBUtil::checkInt32($var);
        $this->PraiseTime = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string RecordPraiseRole = 24;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getRecordPraiseRole()
    {
        return $this->RecordPraiseRole;
    }

    /**
     * Generated from protobuf field <code>repeated string RecordPraiseRole = 24;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setRecordPraiseRole($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->RecordPraiseRole = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 RoomPraiseTime = 25;</code>
     * @return int
     */
    public function getRoomPraiseTime()
    {
        return $this->RoomPraiseTime;
    }

    /**
     * Generated from protobuf field <code>int32 RoomPraiseTime = 25;</code>
     * @param int $var
     * @return $this
     */
    public function setRoomPraiseTime($var)
    {
        GPBUtil::checkInt32($var);
        $this->RoomPraiseTime = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string AuctionShopId = 26;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getAuctionShopId()
    {
        return $this->AuctionShopId;
    }

    /**
     * Generated from protobuf field <code>repeated string AuctionShopId = 26;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setAuctionShopId($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->AuctionShopId = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 RedPacketMaxMoney = 27;</code>
     * @return int|string
     */
    public function getRedPacketMaxMoney()
    {
        return $this->RedPacketMaxMoney;
    }

    /**
     * Generated from protobuf field <code>int64 RedPacketMaxMoney = 27;</code>
     * @param int|string $var
     * @return $this
     */
    public function setRedPacketMaxMoney($var)
    {
        GPBUtil::checkInt64($var);
        $this->RedPacketMaxMoney = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 PkWinCount = 28;</code>
     * @return int
     */
    public function getPkWinCount()
    {
        return $this->PkWinCount;
    }

    /**
     * Generated from protobuf field <code>int32 PkWinCount = 28;</code>
     * @param int $var
     * @return $this
     */
    public function setPkWinCount($var)
    {
        GPBUtil::checkInt32($var);
        $this->PkWinCount = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 PkLostCount = 29;</code>
     * @return int
     */
    public function getPkLostCount()
    {
        return $this->PkLostCount;
    }

    /**
     * Generated from protobuf field <code>int32 PkLostCount = 29;</code>
     * @param int $var
     * @return $this
     */
    public function setPkLostCount($var)
    {
        GPBUtil::checkInt32($var);
        $this->PkLostCount = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 PkPingCount = 30;</code>
     * @return int
     */
    public function getPkPingCount()
    {
        return $this->PkPingCount;
    }

    /**
     * Generated from protobuf field <code>int32 PkPingCount = 30;</code>
     * @param int $var
     * @return $this
     */
    public function setPkPingCount($var)
    {
        GPBUtil::checkInt32($var);
        $this->PkPingCount = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 WhetherTheLoan = 31;</code>
     * @return int
     */
    public function getWhetherTheLoan()
    {
        return $this->WhetherTheLoan;
    }

    /**
     * Generated from protobuf field <code>int32 WhetherTheLoan = 31;</code>
     * @param int $var
     * @return $this
     */
    public function setWhetherTheLoan($var)
    {
        GPBUtil::checkInt32($var);
        $this->WhetherTheLoan = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>map<int32, .AutoMsg.LoadRecordType> LoadRecordType = 32;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getLoadRecordType()
    {
        return $this->LoadRecordType;
    }

    /**
     * Generated from protobuf field <code>map<int32, .AutoMsg.LoadRecordType> LoadRecordType = 32;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setLoadRecordType($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::INT32, \Google\Protobuf\Internal\GPBType::MESSAGE, \AutoMsg\LoadRecordType::class);
        $this->LoadRecordType = $arr;

        return $this;
    }

}

