<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protomsg.proto

namespace AutoMsg;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>AutoMsg.LoadListId</code>
 */
class LoadListId extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 Id = 1;</code>
     */
    private $Id = 0;
    /**
     * Generated from protobuf field <code>int32 SemenId = 2;</code>
     */
    private $SemenId = 0;
    /**
     * Generated from protobuf field <code>int64 Count = 3;</code>
     */
    private $Count = 0;
    /**
     * Generated from protobuf field <code>int32 Time = 4;</code>
     */
    private $Time = 0;

    public function __construct() {
        \GPBMetadata\Protomsg::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>int32 Id = 1;</code>
     * @return int
     */
    public function getId()
    {
        return $this->Id;
    }

    /**
     * Generated from protobuf field <code>int32 Id = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkInt32($var);
        $this->Id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 SemenId = 2;</code>
     * @return int
     */
    public function getSemenId()
    {
        return $this->SemenId;
    }

    /**
     * Generated from protobuf field <code>int32 SemenId = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setSemenId($var)
    {
        GPBUtil::checkInt32($var);
        $this->SemenId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 Count = 3;</code>
     * @return int|string
     */
    public function getCount()
    {
        return $this->Count;
    }

    /**
     * Generated from protobuf field <code>int64 Count = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCount($var)
    {
        GPBUtil::checkInt64($var);
        $this->Count = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 Time = 4;</code>
     * @return int
     */
    public function getTime()
    {
        return $this->Time;
    }

    /**
     * Generated from protobuf field <code>int32 Time = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setTime($var)
    {
        GPBUtil::checkInt32($var);
        $this->Time = $var;

        return $this;
    }

}

