<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Src/protomsg.proto

namespace AutoMsg;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>AutoMsg.LoadReceiveRedPacket</code>
 */
class LoadReceiveRedPacket extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string RoleId = 1;</code>
     */
    private $RoleId = '';
    /**
     * Generated from protobuf field <code>string Nmae = 2;</code>
     */
    private $Nmae = '';
    /**
     * Generated from protobuf field <code>int64 Price = 3;</code>
     */
    private $Price = 0;

    public function __construct() {
        \GPBMetadata\Src\Protomsg::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>string RoleId = 1;</code>
     * @return string
     */
    public function getRoleId()
    {
        return $this->RoleId;
    }

    /**
     * Generated from protobuf field <code>string RoleId = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setRoleId($var)
    {
        GPBUtil::checkString($var, True);
        $this->RoleId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string Nmae = 2;</code>
     * @return string
     */
    public function getNmae()
    {
        return $this->Nmae;
    }

    /**
     * Generated from protobuf field <code>string Nmae = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setNmae($var)
    {
        GPBUtil::checkString($var, True);
        $this->Nmae = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 Price = 3;</code>
     * @return int|string
     */
    public function getPrice()
    {
        return $this->Price;
    }

    /**
     * Generated from protobuf field <code>int64 Price = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setPrice($var)
    {
        GPBUtil::checkInt64($var);
        $this->Price = $var;

        return $this;
    }

}

