<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protomsg.proto

namespace AutoMsg;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>AutoMsg.LoansInfo</code>
 */
class LoansInfo extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string Id = 1;</code>
     */
    private $Id = '';
    /**
     * Generated from protobuf field <code>int32 LoansTime = 2;</code>
     */
    private $LoansTime = 0;
    /**
     * Generated from protobuf field <code>int32 Day = 3;</code>
     */
    private $Day = 0;
    /**
     * Generated from protobuf field <code>int64 GoldCount = 4;</code>
     */
    private $GoldCount = 0;
    /**
     * Generated from protobuf field <code>int32 GoldType = 5;</code>
     */
    private $GoldType = 0;
    /**
     * Generated from protobuf field <code>int32 WhetherTheLoan = 6;</code>
     */
    private $WhetherTheLoan = 0;

    public function __construct() {
        \GPBMetadata\Protomsg::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>string Id = 1;</code>
     * @return string
     */
    public function getId()
    {
        return $this->Id;
    }

    /**
     * Generated from protobuf field <code>string Id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkString($var, True);
        $this->Id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 LoansTime = 2;</code>
     * @return int
     */
    public function getLoansTime()
    {
        return $this->LoansTime;
    }

    /**
     * Generated from protobuf field <code>int32 LoansTime = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setLoansTime($var)
    {
        GPBUtil::checkInt32($var);
        $this->LoansTime = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 Day = 3;</code>
     * @return int
     */
    public function getDay()
    {
        return $this->Day;
    }

    /**
     * Generated from protobuf field <code>int32 Day = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setDay($var)
    {
        GPBUtil::checkInt32($var);
        $this->Day = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 GoldCount = 4;</code>
     * @return int|string
     */
    public function getGoldCount()
    {
        return $this->GoldCount;
    }

    /**
     * Generated from protobuf field <code>int64 GoldCount = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setGoldCount($var)
    {
        GPBUtil::checkInt64($var);
        $this->GoldCount = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 GoldType = 5;</code>
     * @return int
     */
    public function getGoldType()
    {
        return $this->GoldType;
    }

    /**
     * Generated from protobuf field <code>int32 GoldType = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setGoldType($var)
    {
        GPBUtil::checkInt32($var);
        $this->GoldType = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 WhetherTheLoan = 6;</code>
     * @return int
     */
    public function getWhetherTheLoan()
    {
        return $this->WhetherTheLoan;
    }

    /**
     * Generated from protobuf field <code>int32 WhetherTheLoan = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setWhetherTheLoan($var)
    {
        GPBUtil::checkInt32($var);
        $this->WhetherTheLoan = $var;

        return $this;
    }

}

