<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protomsg.proto

namespace AutoMsg;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>AutoMsg.MarketInfo</code>
 */
class MarketInfo extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 Level = 1;</code>
     */
    private $Level = 0;
    /**
     * Generated from protobuf field <code>map<int32, int32> CurDirectorCounts = 2;</code>
     */
    private $CurDirectorCounts;
    /**
     * Generated from protobuf field <code>int32 CurStaff = 3;</code>
     */
    private $CurStaff = 0;
    /**
     * Generated from protobuf field <code>float CurStoreAddtion = 4;</code>
     */
    private $CurStoreAddtion = 0.0;
    /**
     * Generated from protobuf field <code>int32 CurPropagandaCounts = 5;</code>
     */
    private $CurPropagandaCounts = 0;
    /**
     * Generated from protobuf field <code>int32 CurStrategicCounts = 6;</code>
     */
    private $CurStrategicCounts = 0;
    /**
     * Generated from protobuf field <code>int32 CurPurchaseCounts = 7;</code>
     */
    private $CurPurchaseCounts = 0;

    public function __construct() {
        \GPBMetadata\Protomsg::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>int32 Level = 1;</code>
     * @return int
     */
    public function getLevel()
    {
        return $this->Level;
    }

    /**
     * Generated from protobuf field <code>int32 Level = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setLevel($var)
    {
        GPBUtil::checkInt32($var);
        $this->Level = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>map<int32, int32> CurDirectorCounts = 2;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getCurDirectorCounts()
    {
        return $this->CurDirectorCounts;
    }

    /**
     * Generated from protobuf field <code>map<int32, int32> CurDirectorCounts = 2;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setCurDirectorCounts($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::INT32, \Google\Protobuf\Internal\GPBType::INT32);
        $this->CurDirectorCounts = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 CurStaff = 3;</code>
     * @return int
     */
    public function getCurStaff()
    {
        return $this->CurStaff;
    }

    /**
     * Generated from protobuf field <code>int32 CurStaff = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setCurStaff($var)
    {
        GPBUtil::checkInt32($var);
        $this->CurStaff = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>float CurStoreAddtion = 4;</code>
     * @return float
     */
    public function getCurStoreAddtion()
    {
        return $this->CurStoreAddtion;
    }

    /**
     * Generated from protobuf field <code>float CurStoreAddtion = 4;</code>
     * @param float $var
     * @return $this
     */
    public function setCurStoreAddtion($var)
    {
        GPBUtil::checkFloat($var);
        $this->CurStoreAddtion = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 CurPropagandaCounts = 5;</code>
     * @return int
     */
    public function getCurPropagandaCounts()
    {
        return $this->CurPropagandaCounts;
    }

    /**
     * Generated from protobuf field <code>int32 CurPropagandaCounts = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setCurPropagandaCounts($var)
    {
        GPBUtil::checkInt32($var);
        $this->CurPropagandaCounts = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 CurStrategicCounts = 6;</code>
     * @return int
     */
    public function getCurStrategicCounts()
    {
        return $this->CurStrategicCounts;
    }

    /**
     * Generated from protobuf field <code>int32 CurStrategicCounts = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setCurStrategicCounts($var)
    {
        GPBUtil::checkInt32($var);
        $this->CurStrategicCounts = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 CurPurchaseCounts = 7;</code>
     * @return int
     */
    public function getCurPurchaseCounts()
    {
        return $this->CurPurchaseCounts;
    }

    /**
     * Generated from protobuf field <code>int32 CurPurchaseCounts = 7;</code>
     * @param int $var
     * @return $this
     */
    public function setCurPurchaseCounts($var)
    {
        GPBUtil::checkInt32($var);
        $this->CurPurchaseCounts = $var;

        return $this;
    }

}

