<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protomsg.proto

namespace AutoMsg;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>AutoMsg.MissionDataResult</code>
 */
class MissionDataResult extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 MissId = 1;</code>
     */
    private $MissId = 0;
    /**
     * Generated from protobuf field <code>repeated float Progress = 2;</code>
     */
    private $Progress;
    /**
     * Generated from protobuf field <code>bool GetReward = 3;</code>
     */
    private $GetReward = false;
    /**
     * Generated from protobuf field <code>bool Complete = 4;</code>
     */
    private $Complete = false;

    public function __construct() {
        \GPBMetadata\Protomsg::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>int32 MissId = 1;</code>
     * @return int
     */
    public function getMissId()
    {
        return $this->MissId;
    }

    /**
     * Generated from protobuf field <code>int32 MissId = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setMissId($var)
    {
        GPBUtil::checkInt32($var);
        $this->MissId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated float Progress = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getProgress()
    {
        return $this->Progress;
    }

    /**
     * Generated from protobuf field <code>repeated float Progress = 2;</code>
     * @param float[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setProgress($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::FLOAT);
        $this->Progress = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool GetReward = 3;</code>
     * @return bool
     */
    public function getGetReward()
    {
        return $this->GetReward;
    }

    /**
     * Generated from protobuf field <code>bool GetReward = 3;</code>
     * @param bool $var
     * @return $this
     */
    public function setGetReward($var)
    {
        GPBUtil::checkBool($var);
        $this->GetReward = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool Complete = 4;</code>
     * @return bool
     */
    public function getComplete()
    {
        return $this->Complete;
    }

    /**
     * Generated from protobuf field <code>bool Complete = 4;</code>
     * @param bool $var
     * @return $this
     */
    public function setComplete($var)
    {
        GPBUtil::checkBool($var);
        $this->Complete = $var;

        return $this;
    }

}

