<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Src/protomsg.proto

namespace AutoMsg;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>AutoMsg.MissionResult</code>
 */
class MissionResult extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>map<int32, int32> Completes = 1;</code>
     */
    private $Completes;
    /**
     * Generated from protobuf field <code>map<int32, .AutoMsg.MissionDataResult> Doings = 2;</code>
     */
    private $Doings;
    /**
     * Generated from protobuf field <code>map<int32, bool> VitalityStatus = 3;</code>
     */
    private $VitalityStatus;
    /**
     * Generated from protobuf field <code>int32 Vitality = 4;</code>
     */
    private $Vitality = 0;
    /**
     * Generated from protobuf field <code>map<int32, int32> CreateRoadCount = 5;</code>
     */
    private $CreateRoadCount;
    /**
     * Generated from protobuf field <code>int32 CreateRoad = 6;</code>
     */
    private $CreateRoad = 0;

    public function __construct() {
        \GPBMetadata\Src\Protomsg::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>map<int32, int32> Completes = 1;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getCompletes()
    {
        return $this->Completes;
    }

    /**
     * Generated from protobuf field <code>map<int32, int32> Completes = 1;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setCompletes($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::INT32, \Google\Protobuf\Internal\GPBType::INT32);
        $this->Completes = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>map<int32, .AutoMsg.MissionDataResult> Doings = 2;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getDoings()
    {
        return $this->Doings;
    }

    /**
     * Generated from protobuf field <code>map<int32, .AutoMsg.MissionDataResult> Doings = 2;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setDoings($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::INT32, \Google\Protobuf\Internal\GPBType::MESSAGE, \AutoMsg\MissionDataResult::class);
        $this->Doings = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>map<int32, bool> VitalityStatus = 3;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getVitalityStatus()
    {
        return $this->VitalityStatus;
    }

    /**
     * Generated from protobuf field <code>map<int32, bool> VitalityStatus = 3;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setVitalityStatus($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::INT32, \Google\Protobuf\Internal\GPBType::BOOL);
        $this->VitalityStatus = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 Vitality = 4;</code>
     * @return int
     */
    public function getVitality()
    {
        return $this->Vitality;
    }

    /**
     * Generated from protobuf field <code>int32 Vitality = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setVitality($var)
    {
        GPBUtil::checkInt32($var);
        $this->Vitality = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>map<int32, int32> CreateRoadCount = 5;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getCreateRoadCount()
    {
        return $this->CreateRoadCount;
    }

    /**
     * Generated from protobuf field <code>map<int32, int32> CreateRoadCount = 5;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setCreateRoadCount($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::INT32, \Google\Protobuf\Internal\GPBType::INT32);
        $this->CreateRoadCount = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 CreateRoad = 6;</code>
     * @return int
     */
    public function getCreateRoad()
    {
        return $this->CreateRoad;
    }

    /**
     * Generated from protobuf field <code>int32 CreateRoad = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setCreateRoad($var)
    {
        GPBUtil::checkInt32($var);
        $this->CreateRoad = $var;

        return $this;
    }

}

