<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Src/protomsg.proto

namespace AutoMsg;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>AutoMsg.MoneyChangeResult</code>
 */
class MoneyChangeResult extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 Count = 1;</code>
     */
    private $Count = 0;
    /**
     * Generated from protobuf field <code>int32 ChangeTo = 2;</code>
     */
    private $ChangeTo = 0;

    public function __construct() {
        \GPBMetadata\Src\Protomsg::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>int64 Count = 1;</code>
     * @return int|string
     */
    public function getCount()
    {
        return $this->Count;
    }

    /**
     * Generated from protobuf field <code>int64 Count = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCount($var)
    {
        GPBUtil::checkInt64($var);
        $this->Count = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 ChangeTo = 2;</code>
     * @return int
     */
    public function getChangeTo()
    {
        return $this->ChangeTo;
    }

    /**
     * Generated from protobuf field <code>int32 ChangeTo = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setChangeTo($var)
    {
        GPBUtil::checkInt32($var);
        $this->ChangeTo = $var;

        return $this;
    }

}

