<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Src/protomsg.proto

namespace AutoMsg;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>AutoMsg.MsgBaseRev</code>
 */
class MsgBaseRev extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 PartitionKey = 1;</code>
     */
    private $PartitionKey = 0;
    /**
     * Generated from protobuf field <code>int32 MsgId = 2;</code>
     */
    private $MsgId = 0;
    /**
     * Generated from protobuf field <code>string SignKey = 3;</code>
     */
    private $SignKey = '';
    /**
     * Generated from protobuf field <code>bytes Data = 4;</code>
     */
    private $Data = '';

    public function __construct() {
        \GPBMetadata\Src\Protomsg::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>int32 PartitionKey = 1;</code>
     * @return int
     */
    public function getPartitionKey()
    {
        return $this->PartitionKey;
    }

    /**
     * Generated from protobuf field <code>int32 PartitionKey = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setPartitionKey($var)
    {
        GPBUtil::checkInt32($var);
        $this->PartitionKey = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 MsgId = 2;</code>
     * @return int
     */
    public function getMsgId()
    {
        return $this->MsgId;
    }

    /**
     * Generated from protobuf field <code>int32 MsgId = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setMsgId($var)
    {
        GPBUtil::checkInt32($var);
        $this->MsgId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string SignKey = 3;</code>
     * @return string
     */
    public function getSignKey()
    {
        return $this->SignKey;
    }

    /**
     * Generated from protobuf field <code>string SignKey = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setSignKey($var)
    {
        GPBUtil::checkString($var, True);
        $this->SignKey = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes Data = 4;</code>
     * @return string
     */
    public function getData()
    {
        return $this->Data;
    }

    /**
     * Generated from protobuf field <code>bytes Data = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setData($var)
    {
        GPBUtil::checkString($var, False);
        $this->Data = $var;

        return $this;
    }

}

