<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protomsg.proto

namespace AutoMsg;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *新消息 2000
 *
 * Generated from protobuf message <code>AutoMsg.NewMsgResult</code>
 */
class NewMsgResult extends \Google\Protobuf\Internal\Message
{
    /**
     *新消息列表
     *
     * Generated from protobuf field <code>repeated .AutoMsg.NewMsg NewMsgList = 1;</code>
     */
    private $NewMsgList;

    public function __construct() {
        \GPBMetadata\Protomsg::initOnce();
        parent::__construct();
    }

    /**
     *新消息列表
     *
     * Generated from protobuf field <code>repeated .AutoMsg.NewMsg NewMsgList = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getNewMsgList()
    {
        return $this->NewMsgList;
    }

    /**
     *新消息列表
     *
     * Generated from protobuf field <code>repeated .AutoMsg.NewMsg NewMsgList = 1;</code>
     * @param \AutoMsg\NewMsg[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setNewMsgList($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \AutoMsg\NewMsg::class);
        $this->NewMsgList = $arr;

        return $this;
    }

}

