<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protomsg.proto

namespace AutoMsg;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>AutoMsg.NpcFavorabilityResult</code>
 */
class NpcFavorabilityResult extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .AutoMsg.LoadNpcFavorability NpcFavorabilityData = 1;</code>
     */
    private $NpcFavorabilityData;

    public function __construct() {
        \GPBMetadata\Protomsg::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>repeated .AutoMsg.LoadNpcFavorability NpcFavorabilityData = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getNpcFavorabilityData()
    {
        return $this->NpcFavorabilityData;
    }

    /**
     * Generated from protobuf field <code>repeated .AutoMsg.LoadNpcFavorability NpcFavorabilityData = 1;</code>
     * @param \AutoMsg\LoadNpcFavorability[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setNpcFavorabilityData($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \AutoMsg\LoadNpcFavorability::class);
        $this->NpcFavorabilityData = $arr;

        return $this;
    }

}

