<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Src/protomsg.proto

namespace AutoMsg;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *居民npc和任务id
 *
 * Generated from protobuf message <code>AutoMsg.NpcTask</code>
 */
class NpcTask extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 NpcId = 1;</code>
     */
    private $NpcId = 0;
    /**
     * Generated from protobuf field <code>int32 TaskId = 2;</code>
     */
    private $TaskId = 0;

    public function __construct() {
        \GPBMetadata\Src\Protomsg::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>int32 NpcId = 1;</code>
     * @return int
     */
    public function getNpcId()
    {
        return $this->NpcId;
    }

    /**
     * Generated from protobuf field <code>int32 NpcId = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setNpcId($var)
    {
        GPBUtil::checkInt32($var);
        $this->NpcId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 TaskId = 2;</code>
     * @return int
     */
    public function getTaskId()
    {
        return $this->TaskId;
    }

    /**
     * Generated from protobuf field <code>int32 TaskId = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setTaskId($var)
    {
        GPBUtil::checkInt32($var);
        $this->TaskId = $var;

        return $this;
    }

}

