<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protomsg.proto

namespace AutoMsg;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *pk排行帮请求
 *
 * Generated from protobuf message <code>AutoMsg.PkRankingReq</code>
 */
class PkRankingReq extends \Google\Protobuf\Internal\Message
{

    public function __construct() {
        \GPBMetadata\Protomsg::initOnce();
        parent::__construct();
    }

}

