<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Src/protomsg.proto

namespace AutoMsg;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *排行榜详情
 *
 * Generated from protobuf message <code>AutoMsg.PkRankingInfo</code>
 */
class PkRankingInfo extends \Google\Protobuf\Internal\Message
{
    /**
     *名次
     *
     * Generated from protobuf field <code>int32 Ranking = 1;</code>
     */
    private $Ranking = 0;
    /**
     *玩家名词
     *
     * Generated from protobuf field <code>string Name = 2;</code>
     */
    private $Name = '';
    /**
     *身价值
     *
     * Generated from protobuf field <code>int32 Shenjiazhi = 3;</code>
     */
    private $Shenjiazhi = 0;
    /**
     *积分
     *
     * Generated from protobuf field <code>int32 Score = 4;</code>
     */
    private $Score = 0;

    public function __construct() {
        \GPBMetadata\Src\Protomsg::initOnce();
        parent::__construct();
    }

    /**
     *名次
     *
     * Generated from protobuf field <code>int32 Ranking = 1;</code>
     * @return int
     */
    public function getRanking()
    {
        return $this->Ranking;
    }

    /**
     *名次
     *
     * Generated from protobuf field <code>int32 Ranking = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setRanking($var)
    {
        GPBUtil::checkInt32($var);
        $this->Ranking = $var;

        return $this;
    }

    /**
     *玩家名词
     *
     * Generated from protobuf field <code>string Name = 2;</code>
     * @return string
     */
    public function getName()
    {
        return $this->Name;
    }

    /**
     *玩家名词
     *
     * Generated from protobuf field <code>string Name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->Name = $var;

        return $this;
    }

    /**
     *身价值
     *
     * Generated from protobuf field <code>int32 Shenjiazhi = 3;</code>
     * @return int
     */
    public function getShenjiazhi()
    {
        return $this->Shenjiazhi;
    }

    /**
     *身价值
     *
     * Generated from protobuf field <code>int32 Shenjiazhi = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setShenjiazhi($var)
    {
        GPBUtil::checkInt32($var);
        $this->Shenjiazhi = $var;

        return $this;
    }

    /**
     *积分
     *
     * Generated from protobuf field <code>int32 Score = 4;</code>
     * @return int
     */
    public function getScore()
    {
        return $this->Score;
    }

    /**
     *积分
     *
     * Generated from protobuf field <code>int32 Score = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setScore($var)
    {
        GPBUtil::checkInt32($var);
        $this->Score = $var;

        return $this;
    }

}

