<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protomsg.proto

namespace AutoMsg;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>AutoMsg.PurchaseResult</code>
 */
class PurchaseResult extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .AutoMsg.LoadPurchaseData LoadPurchase = 1;</code>
     */
    private $LoadPurchase;

    public function __construct() {
        \GPBMetadata\Protomsg::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>repeated .AutoMsg.LoadPurchaseData LoadPurchase = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getLoadPurchase()
    {
        return $this->LoadPurchase;
    }

    /**
     * Generated from protobuf field <code>repeated .AutoMsg.LoadPurchaseData LoadPurchase = 1;</code>
     * @param \AutoMsg\LoadPurchaseData[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setLoadPurchase($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \AutoMsg\LoadPurchaseData::class);
        $this->LoadPurchase = $arr;

        return $this;
    }

}

