<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protomsg.proto

namespace AutoMsg;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>AutoMsg.RankingReq</code>
 */
class RankingReq extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 RankingType = 1;</code>
     */
    private $RankingType = 0;

    public function __construct() {
        \GPBMetadata\Protomsg::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>int32 RankingType = 1;</code>
     * @return int
     */
    public function getRankingType()
    {
        return $this->RankingType;
    }

    /**
     * Generated from protobuf field <code>int32 RankingType = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setRankingType($var)
    {
        GPBUtil::checkInt32($var);
        $this->RankingType = $var;

        return $this;
    }

}

