<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protomsg.proto

namespace AutoMsg;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>AutoMsg.RankDataProto</code>
 */
class RankDataProto extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 Rank = 1;</code>
     */
    private $Rank = 0;
    /**
     * Generated from protobuf field <code>int32 Level = 2;</code>
     */
    private $Level = 0;
    /**
     * Generated from protobuf field <code>int32 Income = 3;</code>
     */
    private $Income = 0;
    /**
     * Generated from protobuf field <code>string CommerceName = 4;</code>
     */
    private $CommerceName = '';
    /**
     * Generated from protobuf field <code>string Win = 5;</code>
     */
    private $Win = '';
    /**
     * Generated from protobuf field <code>string RoleId = 6;</code>
     */
    private $RoleId = '';
    /**
     * Generated from protobuf field <code>string Name = 7;</code>
     */
    private $Name = '';
    /**
     * Generated from protobuf field <code>string Icon = 8;</code>
     */
    private $Icon = '';
    /**
     * Generated from protobuf field <code>int32 PKPingCount = 9;</code>
     */
    private $PKPingCount = 0;

    public function __construct() {
        \GPBMetadata\Protomsg::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>int32 Rank = 1;</code>
     * @return int
     */
    public function getRank()
    {
        return $this->Rank;
    }

    /**
     * Generated from protobuf field <code>int32 Rank = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setRank($var)
    {
        GPBUtil::checkInt32($var);
        $this->Rank = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 Level = 2;</code>
     * @return int
     */
    public function getLevel()
    {
        return $this->Level;
    }

    /**
     * Generated from protobuf field <code>int32 Level = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setLevel($var)
    {
        GPBUtil::checkInt32($var);
        $this->Level = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 Income = 3;</code>
     * @return int
     */
    public function getIncome()
    {
        return $this->Income;
    }

    /**
     * Generated from protobuf field <code>int32 Income = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setIncome($var)
    {
        GPBUtil::checkInt32($var);
        $this->Income = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string CommerceName = 4;</code>
     * @return string
     */
    public function getCommerceName()
    {
        return $this->CommerceName;
    }

    /**
     * Generated from protobuf field <code>string CommerceName = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setCommerceName($var)
    {
        GPBUtil::checkString($var, True);
        $this->CommerceName = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string Win = 5;</code>
     * @return string
     */
    public function getWin()
    {
        return $this->Win;
    }

    /**
     * Generated from protobuf field <code>string Win = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setWin($var)
    {
        GPBUtil::checkString($var, True);
        $this->Win = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string RoleId = 6;</code>
     * @return string
     */
    public function getRoleId()
    {
        return $this->RoleId;
    }

    /**
     * Generated from protobuf field <code>string RoleId = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setRoleId($var)
    {
        GPBUtil::checkString($var, True);
        $this->RoleId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string Name = 7;</code>
     * @return string
     */
    public function getName()
    {
        return $this->Name;
    }

    /**
     * Generated from protobuf field <code>string Name = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->Name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string Icon = 8;</code>
     * @return string
     */
    public function getIcon()
    {
        return $this->Icon;
    }

    /**
     * Generated from protobuf field <code>string Icon = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setIcon($var)
    {
        GPBUtil::checkString($var, True);
        $this->Icon = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 PKPingCount = 9;</code>
     * @return int
     */
    public function getPKPingCount()
    {
        return $this->PKPingCount;
    }

    /**
     * Generated from protobuf field <code>int32 PKPingCount = 9;</code>
     * @param int $var
     * @return $this
     */
    public function setPKPingCount($var)
    {
        GPBUtil::checkInt32($var);
        $this->PKPingCount = $var;

        return $this;
    }

}

