<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Src/protomsg.proto

namespace AutoMsg;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *已读消息请求 2001
 *
 * Generated from protobuf message <code>AutoMsg.ReadMsgReq</code>
 */
class ReadMsgReq extends \Google\Protobuf\Internal\Message
{
    /**
     *已读取发送人的消息
     *
     * Generated from protobuf field <code>string Fuid = 1;</code>
     */
    private $Fuid = '';

    public function __construct() {
        \GPBMetadata\Src\Protomsg::initOnce();
        parent::__construct();
    }

    /**
     *已读取发送人的消息
     *
     * Generated from protobuf field <code>string Fuid = 1;</code>
     * @return string
     */
    public function getFuid()
    {
        return $this->Fuid;
    }

    /**
     *已读取发送人的消息
     *
     * Generated from protobuf field <code>string Fuid = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setFuid($var)
    {
        GPBUtil::checkString($var, True);
        $this->Fuid = $var;

        return $this;
    }

}

