<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protomsg.proto

namespace AutoMsg;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>AutoMsg.ReceiveRedPacketResult</code>
 */
class ReceiveRedPacketResult extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.AutoMsg.LoadResultRedPacket loadRedPacket = 1;</code>
     */
    private $loadRedPacket = null;

    public function __construct() {
        \GPBMetadata\Protomsg::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>.AutoMsg.LoadResultRedPacket loadRedPacket = 1;</code>
     * @return \AutoMsg\LoadResultRedPacket
     */
    public function getLoadRedPacket()
    {
        return $this->loadRedPacket;
    }

    /**
     * Generated from protobuf field <code>.AutoMsg.LoadResultRedPacket loadRedPacket = 1;</code>
     * @param \AutoMsg\LoadResultRedPacket $var
     * @return $this
     */
    public function setLoadRedPacket($var)
    {
        GPBUtil::checkMessage($var, \AutoMsg\LoadResultRedPacket::class);
        $this->loadRedPacket = $var;

        return $this;
    }

}

