<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Src/protomsg.proto

namespace AutoMsg;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>AutoMsg.RefreshAHResult</code>
 */
class RefreshAHResult extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .AutoMsg.DealGoodsUpdate GenAhGoods = 1;</code>
     */
    private $GenAhGoods;
    /**
     * Generated from protobuf field <code>repeated .AutoMsg.DealGoodsUpdate ValAhGoods = 2;</code>
     */
    private $ValAhGoods;

    public function __construct() {
        \GPBMetadata\Src\Protomsg::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>repeated .AutoMsg.DealGoodsUpdate GenAhGoods = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getGenAhGoods()
    {
        return $this->GenAhGoods;
    }

    /**
     * Generated from protobuf field <code>repeated .AutoMsg.DealGoodsUpdate GenAhGoods = 1;</code>
     * @param \AutoMsg\DealGoodsUpdate[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setGenAhGoods($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \AutoMsg\DealGoodsUpdate::class);
        $this->GenAhGoods = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .AutoMsg.DealGoodsUpdate ValAhGoods = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getValAhGoods()
    {
        return $this->ValAhGoods;
    }

    /**
     * Generated from protobuf field <code>repeated .AutoMsg.DealGoodsUpdate ValAhGoods = 2;</code>
     * @param \AutoMsg\DealGoodsUpdate[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setValAhGoods($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \AutoMsg\DealGoodsUpdate::class);
        $this->ValAhGoods = $arr;

        return $this;
    }

}

