<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protomsg.proto

namespace AutoMsg;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>AutoMsg.RequestGoodsDownReq</code>
 */
class RequestGoodsDownReq extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string DealId = 1;</code>
     */
    private $DealId = '';

    public function __construct() {
        \GPBMetadata\Protomsg::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>string DealId = 1;</code>
     * @return string
     */
    public function getDealId()
    {
        return $this->DealId;
    }

    /**
     * Generated from protobuf field <code>string DealId = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setDealId($var)
    {
        GPBUtil::checkString($var, True);
        $this->DealId = $var;

        return $this;
    }

}

