<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protomsg.proto

namespace AutoMsg;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>AutoMsg.RoomVisitInfoResult</code>
 */
class RoomVisitInfoResult extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .AutoMsg.RoomVisitInfo Visits = 1;</code>
     */
    private $Visits;

    public function __construct() {
        \GPBMetadata\Protomsg::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>repeated .AutoMsg.RoomVisitInfo Visits = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getVisits()
    {
        return $this->Visits;
    }

    /**
     * Generated from protobuf field <code>repeated .AutoMsg.RoomVisitInfo Visits = 1;</code>
     * @param \AutoMsg\RoomVisitInfo[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setVisits($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \AutoMsg\RoomVisitInfo::class);
        $this->Visits = $arr;

        return $this;
    }

}

