<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protomsg.proto

namespace AutoMsg;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>AutoMsg.RoomVisitInfoTipResult</code>
 */
class RoomVisitInfoTipResult extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.AutoMsg.RoomVisitInfo Record = 1;</code>
     */
    private $Record = null;

    public function __construct() {
        \GPBMetadata\Protomsg::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>.AutoMsg.RoomVisitInfo Record = 1;</code>
     * @return \AutoMsg\RoomVisitInfo
     */
    public function getRecord()
    {
        return $this->Record;
    }

    /**
     * Generated from protobuf field <code>.AutoMsg.RoomVisitInfo Record = 1;</code>
     * @param \AutoMsg\RoomVisitInfo $var
     * @return $this
     */
    public function setRecord($var)
    {
        GPBUtil::checkMessage($var, \AutoMsg\RoomVisitInfo::class);
        $this->Record = $var;

        return $this;
    }

}

