<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protomsg.proto

namespace AutoMsg;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>AutoMsg.RoomUpdateResult</code>
 */
class RoomUpdateResult extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.AutoMsg.RoomResult RoomResult = 1;</code>
     */
    private $RoomResult = null;

    public function __construct() {
        \GPBMetadata\Protomsg::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>.AutoMsg.RoomResult RoomResult = 1;</code>
     * @return \AutoMsg\RoomResult
     */
    public function getRoomResult()
    {
        return $this->RoomResult;
    }

    /**
     * Generated from protobuf field <code>.AutoMsg.RoomResult RoomResult = 1;</code>
     * @param \AutoMsg\RoomResult $var
     * @return $this
     */
    public function setRoomResult($var)
    {
        GPBUtil::checkMessage($var, \AutoMsg\RoomResult::class);
        $this->RoomResult = $var;

        return $this;
    }

}

