<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Src/protomsg.proto

namespace AutoMsg;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *交易行请求
 *
 * Generated from protobuf message <code>AutoMsg.SalesListResult</code>
 */
class SalesListResult extends \Google\Protobuf\Internal\Message
{
    /**
     *所有拍卖行商品数据集合
     *
     * Generated from protobuf field <code>repeated .AutoMsg.DealGoodsUpdate Goods = 1;</code>
     */
    private $Goods;

    public function __construct() {
        \GPBMetadata\Src\Protomsg::initOnce();
        parent::__construct();
    }

    /**
     *所有拍卖行商品数据集合
     *
     * Generated from protobuf field <code>repeated .AutoMsg.DealGoodsUpdate Goods = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getGoods()
    {
        return $this->Goods;
    }

    /**
     *所有拍卖行商品数据集合
     *
     * Generated from protobuf field <code>repeated .AutoMsg.DealGoodsUpdate Goods = 1;</code>
     * @param \AutoMsg\DealGoodsUpdate[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setGoods($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \AutoMsg\DealGoodsUpdate::class);
        $this->Goods = $arr;

        return $this;
    }

}

