<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protomsg.proto

namespace AutoMsg;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>AutoMsg.ScoreShopBuyResult</code>
 */
class ScoreShopBuyResult extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 Index = 1;</code>
     */
    private $Index = 0;
    /**
     * Generated from protobuf field <code>int32 Count = 2;</code>
     */
    private $Count = 0;
    /**
     * Generated from protobuf field <code>map<int32, int32> BuyInfo = 3;</code>
     */
    private $BuyInfo;

    public function __construct() {
        \GPBMetadata\Protomsg::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>int32 Index = 1;</code>
     * @return int
     */
    public function getIndex()
    {
        return $this->Index;
    }

    /**
     * Generated from protobuf field <code>int32 Index = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setIndex($var)
    {
        GPBUtil::checkInt32($var);
        $this->Index = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 Count = 2;</code>
     * @return int
     */
    public function getCount()
    {
        return $this->Count;
    }

    /**
     * Generated from protobuf field <code>int32 Count = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setCount($var)
    {
        GPBUtil::checkInt32($var);
        $this->Count = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>map<int32, int32> BuyInfo = 3;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getBuyInfo()
    {
        return $this->BuyInfo;
    }

    /**
     * Generated from protobuf field <code>map<int32, int32> BuyInfo = 3;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setBuyInfo($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::INT32, \Google\Protobuf\Internal\GPBType::INT32);
        $this->BuyInfo = $arr;

        return $this;
    }

}

