<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Src/protomsg.proto

namespace AutoMsg;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>AutoMsg.SevenDaysResult</code>
 */
class SevenDaysResult extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .AutoMsg.SevenDaysInfo SevenDaysList = 1;</code>
     */
    private $SevenDaysList;

    public function __construct() {
        \GPBMetadata\Src\Protomsg::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>repeated .AutoMsg.SevenDaysInfo SevenDaysList = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getSevenDaysList()
    {
        return $this->SevenDaysList;
    }

    /**
     * Generated from protobuf field <code>repeated .AutoMsg.SevenDaysInfo SevenDaysList = 1;</code>
     * @param \AutoMsg\SevenDaysInfo[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setSevenDaysList($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \AutoMsg\SevenDaysInfo::class);
        $this->SevenDaysList = $arr;

        return $this;
    }

}

