<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Src/protomsg.proto

namespace AutoMsg;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>AutoMsg.ShopInfoResult</code>
 */
class ShopInfoResult extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.AutoMsg.PublicShop ShopInfo = 1;</code>
     */
    private $ShopInfo = null;

    public function __construct() {
        \GPBMetadata\Src\Protomsg::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>.AutoMsg.PublicShop ShopInfo = 1;</code>
     * @return \AutoMsg\PublicShop
     */
    public function getShopInfo()
    {
        return $this->ShopInfo;
    }

    /**
     * Generated from protobuf field <code>.AutoMsg.PublicShop ShopInfo = 1;</code>
     * @param \AutoMsg\PublicShop $var
     * @return $this
     */
    public function setShopInfo($var)
    {
        GPBUtil::checkMessage($var, \AutoMsg\PublicShop::class);
        $this->ShopInfo = $var;

        return $this;
    }

}

