<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Src/protomsg.proto

namespace AutoMsg;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>AutoMsg.ShopAuctionResult</code>
 */
class ShopAuctionResult extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.AutoMsg.PublicShop OnePublicShop = 1;</code>
     */
    private $OnePublicShop = null;

    public function __construct() {
        \GPBMetadata\Src\Protomsg::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>.AutoMsg.PublicShop OnePublicShop = 1;</code>
     * @return \AutoMsg\PublicShop
     */
    public function getOnePublicShop()
    {
        return $this->OnePublicShop;
    }

    /**
     * Generated from protobuf field <code>.AutoMsg.PublicShop OnePublicShop = 1;</code>
     * @param \AutoMsg\PublicShop $var
     * @return $this
     */
    public function setOnePublicShop($var)
    {
        GPBUtil::checkMessage($var, \AutoMsg\PublicShop::class);
        $this->OnePublicShop = $var;

        return $this;
    }

}

