<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Src/protomsg.proto

namespace AutoMsg;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>AutoMsg.ShopRepaymentReq</code>
 */
class ShopRepaymentReq extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .AutoMsg.ShopTypeInfo ShopType = 1;</code>
     */
    private $ShopType;

    public function __construct() {
        \GPBMetadata\Src\Protomsg::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>repeated .AutoMsg.ShopTypeInfo ShopType = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getShopType()
    {
        return $this->ShopType;
    }

    /**
     * Generated from protobuf field <code>repeated .AutoMsg.ShopTypeInfo ShopType = 1;</code>
     * @param \AutoMsg\ShopTypeInfo[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setShopType($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \AutoMsg\ShopTypeInfo::class);
        $this->ShopType = $arr;

        return $this;
    }

}

