<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protomsg.proto

namespace AutoMsg;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>AutoMsg.ShopTypeInfo</code>
 */
class ShopTypeInfo extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string ShopId = 1;</code>
     */
    private $ShopId = '';
    /**
     * Generated from protobuf field <code>int32 Area = 2;</code>
     */
    private $Area = 0;

    public function __construct() {
        \GPBMetadata\Protomsg::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>string ShopId = 1;</code>
     * @return string
     */
    public function getShopId()
    {
        return $this->ShopId;
    }

    /**
     * Generated from protobuf field <code>string ShopId = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setShopId($var)
    {
        GPBUtil::checkString($var, True);
        $this->ShopId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 Area = 2;</code>
     * @return int
     */
    public function getArea()
    {
        return $this->Area;
    }

    /**
     * Generated from protobuf field <code>int32 Area = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setArea($var)
    {
        GPBUtil::checkInt32($var);
        $this->Area = $var;

        return $this;
    }

}

