<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Src/protomsg.proto

namespace AutoMsg;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>AutoMsg.StartTradehReq</code>
 */
class StartTradehReq extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 Id = 1;</code>
     */
    private $Id = 0;
    /**
     * Generated from protobuf field <code>int32 ShipType = 2;</code>
     */
    private $ShipType = 0;
    /**
     * Generated from protobuf field <code>repeated string FriendId = 3;</code>
     */
    private $FriendId;

    public function __construct() {
        \GPBMetadata\Src\Protomsg::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>int32 Id = 1;</code>
     * @return int
     */
    public function getId()
    {
        return $this->Id;
    }

    /**
     * Generated from protobuf field <code>int32 Id = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkInt32($var);
        $this->Id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 ShipType = 2;</code>
     * @return int
     */
    public function getShipType()
    {
        return $this->ShipType;
    }

    /**
     * Generated from protobuf field <code>int32 ShipType = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setShipType($var)
    {
        GPBUtil::checkInt32($var);
        $this->ShipType = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string FriendId = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getFriendId()
    {
        return $this->FriendId;
    }

    /**
     * Generated from protobuf field <code>repeated string FriendId = 3;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setFriendId($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->FriendId = $arr;

        return $this;
    }

}

