<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protomsg.proto

namespace AutoMsg;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>AutoMsg.StrategyStrikeResult</code>
 */
class StrategyStrikeResult extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 Money = 1;</code>
     */
    private $Money = 0;
    /**
     * Generated from protobuf field <code>int32 Type = 2;</code>
     */
    private $Type = 0;
    /**
     * Generated from protobuf field <code>int32 Count = 3;</code>
     */
    private $Count = 0;
    /**
     * Generated from protobuf field <code>string ShopId = 4;</code>
     */
    private $ShopId = '';
    /**
     * Generated from protobuf field <code>int32 ShopCount = 5;</code>
     */
    private $ShopCount = 0;
    /**
     * Generated from protobuf field <code>int32 DelKuCun = 6;</code>
     */
    private $DelKuCun = 0;

    public function __construct() {
        \GPBMetadata\Protomsg::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>int64 Money = 1;</code>
     * @return int|string
     */
    public function getMoney()
    {
        return $this->Money;
    }

    /**
     * Generated from protobuf field <code>int64 Money = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setMoney($var)
    {
        GPBUtil::checkInt64($var);
        $this->Money = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 Type = 2;</code>
     * @return int
     */
    public function getType()
    {
        return $this->Type;
    }

    /**
     * Generated from protobuf field <code>int32 Type = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkInt32($var);
        $this->Type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 Count = 3;</code>
     * @return int
     */
    public function getCount()
    {
        return $this->Count;
    }

    /**
     * Generated from protobuf field <code>int32 Count = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setCount($var)
    {
        GPBUtil::checkInt32($var);
        $this->Count = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string ShopId = 4;</code>
     * @return string
     */
    public function getShopId()
    {
        return $this->ShopId;
    }

    /**
     * Generated from protobuf field <code>string ShopId = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setShopId($var)
    {
        GPBUtil::checkString($var, True);
        $this->ShopId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 ShopCount = 5;</code>
     * @return int
     */
    public function getShopCount()
    {
        return $this->ShopCount;
    }

    /**
     * Generated from protobuf field <code>int32 ShopCount = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setShopCount($var)
    {
        GPBUtil::checkInt32($var);
        $this->ShopCount = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 DelKuCun = 6;</code>
     * @return int
     */
    public function getDelKuCun()
    {
        return $this->DelKuCun;
    }

    /**
     * Generated from protobuf field <code>int32 DelKuCun = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setDelKuCun($var)
    {
        GPBUtil::checkInt32($var);
        $this->DelKuCun = $var;

        return $this;
    }

}

