<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protomsg.proto

namespace AutoMsg;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>AutoMsg.TakeOutP</code>
 */
class TakeOutP extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bool Status = 1;</code>
     */
    private $Status = false;
    /**
     * Generated from protobuf field <code>repeated int32 Flavor = 2;</code>
     */
    private $Flavor;

    public function __construct() {
        \GPBMetadata\Protomsg::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>bool Status = 1;</code>
     * @return bool
     */
    public function getStatus()
    {
        return $this->Status;
    }

    /**
     * Generated from protobuf field <code>bool Status = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkBool($var);
        $this->Status = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated int32 Flavor = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getFlavor()
    {
        return $this->Flavor;
    }

    /**
     * Generated from protobuf field <code>repeated int32 Flavor = 2;</code>
     * @param int[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setFlavor($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::INT32);
        $this->Flavor = $arr;

        return $this;
    }

}

