<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protomsg.proto

namespace AutoMsg;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>AutoMsg.TakeOutResult</code>
 */
class TakeOutResult extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>map<string, .AutoMsg.TakeOutP> FriendFlavor = 1;</code>
     */
    private $FriendFlavor;

    public function __construct() {
        \GPBMetadata\Protomsg::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>map<string, .AutoMsg.TakeOutP> FriendFlavor = 1;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getFriendFlavor()
    {
        return $this->FriendFlavor;
    }

    /**
     * Generated from protobuf field <code>map<string, .AutoMsg.TakeOutP> FriendFlavor = 1;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setFriendFlavor($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::MESSAGE, \AutoMsg\TakeOutP::class);
        $this->FriendFlavor = $arr;

        return $this;
    }

}

