<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Src/protomsg.proto

namespace AutoMsg;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>AutoMsg.TalentMarketInfo</code>
 */
class TalentMarketInfo extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 RefreshTime = 1;</code>
     */
    private $RefreshTime = 0;
    /**
     * Generated from protobuf field <code>int32 RefreshCount = 2;</code>
     */
    private $RefreshCount = 0;
    /**
     * Generated from protobuf field <code>int32 RefreshCountTime = 3;</code>
     */
    private $RefreshCountTime = 0;
    /**
     * Generated from protobuf field <code>int32 DigCount = 4;</code>
     */
    private $DigCount = 0;

    public function __construct() {
        \GPBMetadata\Src\Protomsg::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>int32 RefreshTime = 1;</code>
     * @return int
     */
    public function getRefreshTime()
    {
        return $this->RefreshTime;
    }

    /**
     * Generated from protobuf field <code>int32 RefreshTime = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setRefreshTime($var)
    {
        GPBUtil::checkInt32($var);
        $this->RefreshTime = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 RefreshCount = 2;</code>
     * @return int
     */
    public function getRefreshCount()
    {
        return $this->RefreshCount;
    }

    /**
     * Generated from protobuf field <code>int32 RefreshCount = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setRefreshCount($var)
    {
        GPBUtil::checkInt32($var);
        $this->RefreshCount = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 RefreshCountTime = 3;</code>
     * @return int
     */
    public function getRefreshCountTime()
    {
        return $this->RefreshCountTime;
    }

    /**
     * Generated from protobuf field <code>int32 RefreshCountTime = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setRefreshCountTime($var)
    {
        GPBUtil::checkInt32($var);
        $this->RefreshCountTime = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 DigCount = 4;</code>
     * @return int
     */
    public function getDigCount()
    {
        return $this->DigCount;
    }

    /**
     * Generated from protobuf field <code>int32 DigCount = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setDigCount($var)
    {
        GPBUtil::checkInt32($var);
        $this->DigCount = $var;

        return $this;
    }

}

