<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protomsg.proto

namespace AutoMsg;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>AutoMsg.TalentHireResult</code>
 */
class TalentHireResult extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string ShopId = 1;</code>
     */
    private $ShopId = '';
    /**
     * Generated from protobuf field <code>string RoleId = 2;</code>
     */
    private $RoleId = '';
    /**
     * Generated from protobuf field <code>.AutoMsg.TalentInfo Info = 3;</code>
     */
    private $Info = null;
    /**
     * Generated from protobuf field <code>bool Complete = 4;</code>
     */
    private $Complete = false;

    public function __construct() {
        \GPBMetadata\Protomsg::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>string ShopId = 1;</code>
     * @return string
     */
    public function getShopId()
    {
        return $this->ShopId;
    }

    /**
     * Generated from protobuf field <code>string ShopId = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setShopId($var)
    {
        GPBUtil::checkString($var, True);
        $this->ShopId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string RoleId = 2;</code>
     * @return string
     */
    public function getRoleId()
    {
        return $this->RoleId;
    }

    /**
     * Generated from protobuf field <code>string RoleId = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setRoleId($var)
    {
        GPBUtil::checkString($var, True);
        $this->RoleId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.AutoMsg.TalentInfo Info = 3;</code>
     * @return \AutoMsg\TalentInfo
     */
    public function getInfo()
    {
        return $this->Info;
    }

    /**
     * Generated from protobuf field <code>.AutoMsg.TalentInfo Info = 3;</code>
     * @param \AutoMsg\TalentInfo $var
     * @return $this
     */
    public function setInfo($var)
    {
        GPBUtil::checkMessage($var, \AutoMsg\TalentInfo::class);
        $this->Info = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool Complete = 4;</code>
     * @return bool
     */
    public function getComplete()
    {
        return $this->Complete;
    }

    /**
     * Generated from protobuf field <code>bool Complete = 4;</code>
     * @param bool $var
     * @return $this
     */
    public function setComplete($var)
    {
        GPBUtil::checkBool($var);
        $this->Complete = $var;

        return $this;
    }

}

