<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protomsg.proto

namespace AutoMsg;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *修改int=》string
 *
 * Generated from protobuf message <code>AutoMsg.TalkingGroupResult</code>
 */
class TalkingGroupResult extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated string Ids = 1;</code>
     */
    private $Ids;
    /**
     * Generated from protobuf field <code>repeated string DownId = 2;</code>
     */
    private $DownId;

    public function __construct() {
        \GPBMetadata\Protomsg::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>repeated string Ids = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getIds()
    {
        return $this->Ids;
    }

    /**
     * Generated from protobuf field <code>repeated string Ids = 1;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setIds($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->Ids = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string DownId = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getDownId()
    {
        return $this->DownId;
    }

    /**
     * Generated from protobuf field <code>repeated string DownId = 2;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setDownId($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->DownId = $arr;

        return $this;
    }

}

