<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protomsg.proto

namespace AutoMsg;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *修改类型int=》string
 *
 * Generated from protobuf message <code>AutoMsg.TalkIngGroupChangeReq</code>
 */
class TalkIngGroupChangeReq extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string UpId = 1;</code>
     */
    private $UpId = '';
    /**
     * Generated from protobuf field <code>string DownId = 2;</code>
     */
    private $DownId = '';

    public function __construct() {
        \GPBMetadata\Protomsg::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>string UpId = 1;</code>
     * @return string
     */
    public function getUpId()
    {
        return $this->UpId;
    }

    /**
     * Generated from protobuf field <code>string UpId = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setUpId($var)
    {
        GPBUtil::checkString($var, True);
        $this->UpId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string DownId = 2;</code>
     * @return string
     */
    public function getDownId()
    {
        return $this->DownId;
    }

    /**
     * Generated from protobuf field <code>string DownId = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setDownId($var)
    {
        GPBUtil::checkString($var, True);
        $this->DownId = $var;

        return $this;
    }

}

