<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Src/protomsg.proto

namespace AutoMsg;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *谈判团任居民任命请求
 *
 * Generated from protobuf message <code>AutoMsg.TalkingGroupResidentReq</code>
 */
class TalkingGroupResidentReq extends \Google\Protobuf\Internal\Message
{
    /**
     *任命
     *
     * Generated from protobuf field <code>repeated int32 Ids = 1;</code>
     */
    private $Ids;
    /**
     *是否是替换掉所有人
     *
     * Generated from protobuf field <code>bool Replace = 2;</code>
     */
    private $Replace = false;

    public function __construct() {
        \GPBMetadata\Src\Protomsg::initOnce();
        parent::__construct();
    }

    /**
     *任命
     *
     * Generated from protobuf field <code>repeated int32 Ids = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getIds()
    {
        return $this->Ids;
    }

    /**
     *任命
     *
     * Generated from protobuf field <code>repeated int32 Ids = 1;</code>
     * @param int[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setIds($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::INT32);
        $this->Ids = $arr;

        return $this;
    }

    /**
     *是否是替换掉所有人
     *
     * Generated from protobuf field <code>bool Replace = 2;</code>
     * @return bool
     */
    public function getReplace()
    {
        return $this->Replace;
    }

    /**
     *是否是替换掉所有人
     *
     * Generated from protobuf field <code>bool Replace = 2;</code>
     * @param bool $var
     * @return $this
     */
    public function setReplace($var)
    {
        GPBUtil::checkBool($var);
        $this->Replace = $var;

        return $this;
    }

}

