<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Src/protomsg.proto

namespace AutoMsg;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>AutoMsg.TCDepartmentPersonnelResult</code>
 */
class TCDepartmentPersonnelResult extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.AutoMsg.PersonnelInfo PersonnelInfo = 1;</code>
     */
    private $PersonnelInfo = null;

    public function __construct() {
        \GPBMetadata\Src\Protomsg::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>.AutoMsg.PersonnelInfo PersonnelInfo = 1;</code>
     * @return \AutoMsg\PersonnelInfo
     */
    public function getPersonnelInfo()
    {
        return $this->PersonnelInfo;
    }

    /**
     * Generated from protobuf field <code>.AutoMsg.PersonnelInfo PersonnelInfo = 1;</code>
     * @param \AutoMsg\PersonnelInfo $var
     * @return $this
     */
    public function setPersonnelInfo($var)
    {
        GPBUtil::checkMessage($var, \AutoMsg\PersonnelInfo::class);
        $this->PersonnelInfo = $var;

        return $this;
    }

}

