<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protomsg.proto

namespace AutoMsg;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>AutoMsg.TeamParams</code>
 */
class TeamParams extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string Page = 1;</code>
     */
    private $Page = '';
    /**
     * Generated from protobuf field <code>string Curpage = 2;</code>
     */
    private $Curpage = '';
    /**
     * Generated from protobuf field <code>string Sex = 3;</code>
     */
    private $Sex = '';
    /**
     * Generated from protobuf field <code>string Invite = 4;</code>
     */
    private $Invite = '';

    public function __construct() {
        \GPBMetadata\Protomsg::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>string Page = 1;</code>
     * @return string
     */
    public function getPage()
    {
        return $this->Page;
    }

    /**
     * Generated from protobuf field <code>string Page = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setPage($var)
    {
        GPBUtil::checkString($var, True);
        $this->Page = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string Curpage = 2;</code>
     * @return string
     */
    public function getCurpage()
    {
        return $this->Curpage;
    }

    /**
     * Generated from protobuf field <code>string Curpage = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setCurpage($var)
    {
        GPBUtil::checkString($var, True);
        $this->Curpage = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string Sex = 3;</code>
     * @return string
     */
    public function getSex()
    {
        return $this->Sex;
    }

    /**
     * Generated from protobuf field <code>string Sex = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setSex($var)
    {
        GPBUtil::checkString($var, True);
        $this->Sex = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string Invite = 4;</code>
     * @return string
     */
    public function getInvite()
    {
        return $this->Invite;
    }

    /**
     * Generated from protobuf field <code>string Invite = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setInvite($var)
    {
        GPBUtil::checkString($var, True);
        $this->Invite = $var;

        return $this;
    }

}

