<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Src/protomsg.proto

namespace AutoMsg;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>AutoMsg.UpdateRoleInfoIconReq</code>
 */
class UpdateRoleInfoIconReq extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string RoleIcon = 1;</code>
     */
    private $RoleIcon = '';

    public function __construct() {
        \GPBMetadata\Src\Protomsg::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>string RoleIcon = 1;</code>
     * @return string
     */
    public function getRoleIcon()
    {
        return $this->RoleIcon;
    }

    /**
     * Generated from protobuf field <code>string RoleIcon = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setRoleIcon($var)
    {
        GPBUtil::checkString($var, True);
        $this->RoleIcon = $var;

        return $this;
    }

}

