<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protomsg.proto

namespace AutoMsg;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *寄卖请求返回
 *
 * Generated from protobuf message <code>AutoMsg.UserSalesResult</code>
 */
class UserSalesResult extends \Google\Protobuf\Internal\Message
{
    /**
     *本次寄卖商品
     *
     * Generated from protobuf field <code>.AutoMsg.DealGoodsUpdate Goods = 1;</code>
     */
    private $Goods = null;

    public function __construct() {
        \GPBMetadata\Protomsg::initOnce();
        parent::__construct();
    }

    /**
     *本次寄卖商品
     *
     * Generated from protobuf field <code>.AutoMsg.DealGoodsUpdate Goods = 1;</code>
     * @return \AutoMsg\DealGoodsUpdate
     */
    public function getGoods()
    {
        return $this->Goods;
    }

    /**
     *本次寄卖商品
     *
     * Generated from protobuf field <code>.AutoMsg.DealGoodsUpdate Goods = 1;</code>
     * @param \AutoMsg\DealGoodsUpdate $var
     * @return $this
     */
    public function setGoods($var)
    {
        GPBUtil::checkMessage($var, \AutoMsg\DealGoodsUpdate::class);
        $this->Goods = $var;

        return $this;
    }

}

